### ISSUE TITLE
Upgrade Branch SDK 

### ISSUE THREAD

**Issue by geekruchika** [RodrigoSMarques/flutter_branch_sdk#10]
@RodrigoSMarques  Do you have any plans to upgrade flutter_branch_sdk as Google has announced some API changes which directly affect the Branch android implementation?

 

> A couple of months ago, Google announced that they will stop broadcasting install_referrer intents on March 1, 2020. Branch uses this data to help power our deep linking and attribution services on Android devices.
> 
> Fortunately, Google has also introduced the Play Install Referrer API to provide the same data. This API provides better performance, and there is a good chance it is already configured in your app. However, Google has recently contacted several Branch customers about this, so we wanted to proactively reach out and help you confirm your configuration in advance of the cutoff date.
> 
> REQUIRED ACTIONS
> 
> Branch Android SDK: please do EITHER of the following for your Android app:
> 
> 1. Ensure you've linked the Play Install Referrer Library as a Gradle dependency. To do this, please add this directive to your build.gradle file (it is not necessary to implement any of the other steps on this page, as the Branch SDK will handle the rest for you). 
> 
> OR
> 
> 2. Update to the most recent version of the SDK (v4.3.2), which bundles the Play Install Referrer Library automatically.
> 
> TUNE Android SDK: Please update to the most recent version of the SDK (v6.1.2, currently only available on JCenter). The TUNE Android SDK already bundles the Play Install Referrer Library, but older versions contain a rare bug that can cause a background thread to pause for up to 60 seconds while waiting for install_referrer data to be returned.
> 
> In addition, we recommend confirming that the following entry has been removed from your AndroidManifest.xml file:
> 
> Branch SDK
> 
> <receiver android:name="io.branch.referral.InstallListener" android:exported="true">
>    <intent-filter>
>    <action android:name="com.android.vending.INSTALL_REFERRER" />
>    </intent-filter>
> </receiver>

As I have used this SDK in one of my ongoing project, this one is critical for me.
Thanks in advance.

**Comment by RodrigoSMarques** [comment]
Hi @geekruchika .
The plugin was created considering the latest version of Branch SDK 4.3.x.
It is already following the new standard, which bundles the Play Install Referrer Library automatically.

In a project I am building, it is using the latest versions of the Branch SDK.
![Capture](https://user-images.githubusercontent.com/17687286/73744779-45024380-4730-11ea-8fd6-fb469eb11638.PNG)

What is your feedback on the plugin? Was it easy to implement and use?

**Comment by geekruchika** [comment]
Thanks, @RodrigoSMarques.
