### ISSUE TITLE
NullPointerException when leaving the app

### ISSUE THREAD

**Issue by jgadsby** [RodrigoSMarques/flutter_branch_sdk#100]
When I trigger a url to open (using the url_launcher package), the app crashes. Here's my log:

`E/AndroidRuntime(10748): java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.EventChannel$EventSink.error(java.lang.String, java.lang.String, java.lang.Object)' on a null object reference
E/AndroidRuntime(10748): 	at br.com.rsmarques.flutter_branch_sdk.FlutterBranchSdkPlugin$MainThreadEventSink$2.run(FlutterBranchSdkPlugin.java:759)
E/AndroidRuntime(10748): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(10748): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(10748): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(10748): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(10748): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10748): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(10748): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
`

Any ideas why this is?

**Comment by jgadsby** [comment]
Maybe you need to check if eventSink != null in the error callback in addition to the success callback?

**Comment by RodrigoSMarques** [comment]
The fix will be available in the next release. PR #99

**Comment by jgadsby** [comment]
> The fix will be available in the next release. PR #99

Oh awesome! When is that rolling out?

**Comment by RodrigoSMarques** [comment]
I plan, until the beginning of next week.
