### ISSUE TITLE
validateSDKIntegration not working on iOS simulator

### ISSUE THREAD

**Issue by Tomo-Xin** [RodrigoSMarques/flutter_branch_sdk#105]
flutter version: 1.22.2
COCOAPODS: 1.10.1

flutter_branch_sdk: ^1.4.0
PODS:
- Branch (1.38.0)
- flutter_branch_sdk (1.3.2):
    - Branch (~> 1.38.0)
    - Flutter

Once I use the `FlutterBranchSdk.validateSDKIntegration();` and try to launch the app on iOS simulator it always show **the network request is invalid**
<img width="233" alt="Screen Shot 2021-05-26 at 4 36 58 PM" src="https://user-images.githubusercontent.com/81205403/119629468-9e6c1580-be40-11eb-823a-5de65ccd3ea1.png">

**Comment by RodrigoSMarques** [comment]
Did you follow setup [instructions for iOS](https://help.branch.io/developers-hub/docs/ios-basic-integration)?

Has the `branch_key` been configured correctly in `INFO.PLIST`?

If so, open a ticket on Branch support, as the `FlutterBranchSdk.validateSDKIntegration()` method calls a method in the Branch Native iOS SDK. 
The support will know what is wrong with the iOS setup.

**Comment by Tomo-Xin** [comment]
Hi @RodrigoSMarques ,

I followed the configuration except the CocoaPods part and Swift codes as I thought these parts will be covered by flutter plugin. Am I right?

for the branch_key part, yes. I configured in info.plist
```
<key>branch_key</key>
<string>{live key from branch dashboard}</string>
<key>branch_universal_link_domains</key>
<array>
  <string>{domain from branch dashboard}</string>
  <string>{alternate domain from branch dashboard}</string>
<array>
```

**Comment by RodrigoSMarques** [comment]
Did you solve your problem?

**Comment by Tomo-Xin** [comment]
Yes, It's solved. thanks for tracking

**Comment by djadu** [comment]
@Tomo-Xin how was this solved? I'm having the same issue

**Comment by Tomo-Xin** [comment]
Fixed, thanks
