### ISSUE TITLE
Using alternate link domain instead of default link domain

### ISSUE THREAD

**Issue by maxbuchan** [RodrigoSMarques/flutter_branch_sdk#109]
My default link domain works as expected for deep link sharing of my app on most platforms, but is blocked by Facebook and Instagram. However, if I manually change my default link domain to my alternate link domain (for example, change XXX.app.link/YYY to XXX-alternate.app.link/YYY), I can share and send deep links without issue on both.

I've poked around my code for a while now and cannot figure out a way to generate a deep link with my alternate link domain.

How can I always use my alternate link domain when I generate a deep link?

Cheers

**Comment by RodrigoSMarques** [comment]
Hi. I won't know how to answer you.
Try to contact Branch support.
Explain what is happening with the main link as well. They can guide you better.

**Comment by RodrigoSMarques** [comment]
Have you contacted Branch support?
Can I close the issue?

**Comment by maxbuchan** [comment]
@RodrigoSMarques Yeah you're free to close this issue now. The solution was to contact Facebook themselves to request to have the default domain link unblocked. Thanks!
