### ISSUE TITLE
View and Redeem Credits 

### ISSUE THREAD

**Issue by ajsatam** [RodrigoSMarques/flutter_branch_sdk#11]
The Branch SDK has the functionality to view and redeem credits generated by referrals using the below native code. Is there any way we can use it using this module. 

```
Branch.getInstance(getApplicationContext()).loadRewards(new BranchReferralStateChangedListener() {
    @Override
    public void onStateChanged(boolean changed, Branch.BranchError error) {
        // changed boolean will indicate if the balance changed from what is currently in memory

        if (error == null) {
            String bucket = "myBucket";
            Branch.getInstance(getApplicationContext()).getCreditsForBucket(bucket);
        }
    }
});
```

Below is a reference link:
[referrals](https://docs.branch.io/viral/referrals/)

**Comment by RodrigoSMarques** [comment]
Hi @ajsatam.
This function is not available. I didn't build it because it was never used and I didn't understand how it works.
The implementation is not complex. I will work on this in the next few days.
I'll keep the issue open and as soon as it's available I'll let you know here.
I believe that with this functionality the plugin has all the functionality of the native SDK.

**Comment by ajsatam** [comment]
Hi @RodrigoSMarques,
Thank you very much :) 
This functionality is useful for referral system, branch.io has. 
Having this will complete all the functionalities the Native SDK contains.

**Comment by RodrigoSMarques** [comment]
@ajsatam 
When I'm done, I'll make the change available on a Git branch.
Can you help me with the tests before publishing the plugin?

**Comment by ajsatam** [comment]
I've never done it. But will surely try. 
Do let me know once you are ready.

**Comment by RodrigoSMarques** [comment]
Hi @ajsatam 
If you want to test, but I will still adjust some for error handling.
The sample application has been updated with the new functions.

In pubspec.yaml change:
```dart
flutter_branch_sdk: ^0.1.5
```
to
```dart
flutter_branch_sdk:
    git: 
       url: https://github.com/RodrigoSMarques/flutter_branch_sdk.git
       ref: enhancement
```

**Comment by RodrigoSMarques** [comment]
Hi @ajsatam 
All functions were developed and made available in the sample app.
I will make the new package available in the coming days.

**Comment by RodrigoSMarques** [comment]
Hi @ajsatam.
Version 0.2.0 available with View and Redeem Credits Functions
