### ISSUE TITLE
Image not showing in whatsapp

### ISSUE THREAD

**Issue by slorop41314** [RodrigoSMarques/flutter_branch_sdk#120]
**Describe the bug**
We tried to share with an image.
If i share it to telegram, the image will showed.
If we share it to whatsapp, no imaged showed.

**To Reproduce**
1. create buo with imageUrl
2. create the branch link properties
3. Share with FlutterBranchSdk.showShareSheet
4. Choose whatsapp and share it
5. Image not shown

**Expected behavior**
Image should be shown too in whatsapp

**Screenshots**
![IMG_20210825_160652](https://user-images.githubusercontent.com/52713279/130768421-2a43c573-b420-4ebd-a6b1-6df55f036191.jpg)
![IMG_20210825_160710](https://user-images.githubusercontent.com/52713279/130768434-870dad51-3352-47ad-8cc7-d10c14265b8a.jpg)

** Code
BranchUniversalObject buo = BranchUniversalObject(
      canonicalIdentifier: 'xxx
      title: 'xxx,
      imageUrl: 'https://gokampus.com/assets/images/logo.png',
      contentDescription: 'xxx,
      publiclyIndex: true,
      locallyIndex: true,
      contentMetadata: BranchContentMetaData()
        ..addCustomMetadata(somedata here)
    );

**Desktop (please complete the following information):**
Flutter (Channel stable, 2.2.3, on macOS 11.2.3 20D91 darwin-arm, locale
    en-ID)
 - Package version: 3.4.0
 - OS: android

**Comment by RodrigoSMarques** [comment]
it is not a bug in the package.  See the links below:

https://help.branch.io/faq/docs/why-are-some-quick-link-thumbnails-not-shown-in-whatsapp

https://stackoverflow.com/questions/38961422/branch-io-link-not-showing-image-thumb-in-whatsapp/38980743#38980743

**Comment by slorop41314** [comment]
got it, thanks
