### ISSUE TITLE
+clicked_branch_link always return false on iOS when open a push notification

### ISSUE THREAD

**Issue by ousvat** [RodrigoSMarques/flutter_branch_sdk#122]
**Describe the bug**
When I receive a push notification with branch io deep link and I open the notification, the app is opening but not navigating to the page I want. I took a look at parameters I got from branch io and all iI have is `{+is_first_session: false, +clicked_branch_link: false}` and no other parameters I expect.

On android everything works fine, and also on iOS when I open the link from WhatsApp or notes app. The problem appear on push notification side.

**To Reproduce**
Steps to reproduce the behaviour:
1. Receive a push notification with branch io link
2. Tap the notification
3. App is opened but not on the correct page

**Expected behaviour**
The app should navigate to the specific page.

**Smartphone (please complete the following information):**
 - Flutter: version:  2.2.3
 - Package version: ^3.2.0
 - Device: iPhone 7
 - OS: iOS 14.7.1

**Additional context**
I use OneSignal service for push notification.

**Comment by RodrigoSMarques** [comment]
Which version of OneSignal is being used?

**Comment by ousvat** [comment]
> Which version of OneSignal is being used?

I use  `onesignal_flutter: ^3.2.3`

**Comment by ousvat** [comment]
**UPDATE:** 
I have the same issue when I open a branch io link from a website. 😢

**Comment by RodrigoSMarques** [comment]
> **UPDATE:**
> I have the same issue when I open a branch io link from a website on my iPhone. 😢

Did you run the FlutterBranchSdk.validateSDKIntegration() command?

Have you verified that you are using the correct branch_key in INFO.PLIST? 

Test link with test key. Live link with live key?

See also the comments on this issue: [https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/issues/1057#issuecomment-893078789](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/issues/1057#issuecomment-893078789)

**Comment by ousvat** [comment]
> > **UPDATE:**
> > I have the same issue when I open a branch io link from a website on my iPhone. 😢
> 
> Did you run the FlutterBranchSdk.validateSDKIntegration() command?
> 
> Have you verified that you are using the correct branch_key in INFO.PLIST?
> 
> Test link with test key. Live link with live key?
> 
> See also the comments on this issue: [BranchMetrics/ios-branch-deep-linking-attribution#1057 (comment)](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/issues/1057#issuecomment-893078789)

`FlutterBranchSdk.validateSDKIntegration()` show me that all tests passes.

Yes. In the `Info.plist` I have the correct branch_key.

As I mentioned before the links are opened correctly when they are launch from whatsapp or from notes app. The issue is when I launch the links from push notification and a website. 

I tried to add  `appclips:` links but no luck 😞 .

**Comment by ousvat** [comment]
If you have some other ideas.. would be awesome 🤟🏻

**Comment by RodrigoSMarques** [comment]
The code needed to receive deeplink by notification is already implemented in the code.

[Instructions](https://help.branch.io/developers-hub/docs/ios-basic-integration#apps-not-using-scenes)
[Code](https://github.com/RodrigoSMarques/flutter_branch_sdk/blob/6fed397961f3e8492c66052860627d572a89a90f/ios/Classes/SwiftFlutterBranchSdkPlugin.swift#L110)

I will have to set up a project with OneSinal to evaluate.

But check this instruction [here](https://help.branch.io/developers-hub/docs/ios-advanced-features#handle-push-notifications)

**Comment by ousvat** [comment]
> The code needed to receive deeplink by notification is already implemented in the code.
> 
> [Instructions](https://help.branch.io/developers-hub/docs/ios-basic-integration#apps-not-using-scenes)
> [Code](https://github.com/RodrigoSMarques/flutter_branch_sdk/blob/6fed397961f3e8492c66052860627d572a89a90f/ios/Classes/SwiftFlutterBranchSdkPlugin.swift#L110)
> 
> I will have to set up a project with OneSinal to evaluate.
> 
> But check this instruction [here](https://help.branch.io/developers-hub/docs/ios-advanced-features#handle-push-notifications)

I really appreciate! Looking forward to see if you can reproduce the same issue.

**Comment by RodrigoSMarques** [comment]
How are you sending the deeplink in the notification? How is the payload?

I did a test on a project using Onesignal 2.6.2, Branch 1.4.0 and Flutter 1.22.6.

As suggested in the documentation [Links, Deep-links and URLs](https://documentation.onesignal.com/docs/links), the link was sent via the OneSignal `LaunchURL` parameter.

The notification was displayed, and when clicked it opened in in-app browser (Behavior of OneSignal on iOS, described in documentation) and then opened the corresponding page in the app.

I was unable to reproduce the problem.

https://user-images.githubusercontent.com/17687286/135716466-f828995a-3546-41bf-832b-17f4fb1d522b.mp4

**Comment by ousvat** [comment]
Can you please try with flutter 2.5 and brach io 3.2.0?
