### ISSUE TITLE
clicked_branch_link is always false in flutter web

### ISSUE THREAD

**Issue by akul1994** [RodrigoSMarques/flutter_branch_sdk#126]
**Describe the bug**
I'm integrating branch for our flutter web app. 
We want users who are opening links on the desktop to be redirected to our flutter web app and do handling based on the data in the link.

However, on flutter web `clicked_branch_link ` is always false and none of the other data added to the link is being read in 

`FlutterBranchSdk.initSession().listen((data){}` 

**Expected behavior**
Should be able to read link data on flutter web

`│ 🐛 DeeplinkHelper ---- listenDeepLinkData {+clicked_branch_link: false, +is_first_session: false}
`
`🐛 DeeplinkHelper ---- listenDeepLinkData referring params {data: {"+clicked_branch_link":false,"+is_first_session":false}, data_parsed: {+clicked_branch_link: false, +is_first_session: false}, has_app: false, identity: null, developer_identity: null, referring_identity: null, referring_link: null}`

**Desktop (please complete the following information):**
 - Flutter: version: 2.5.0
 - Package version: 3.4.0
 - OS: Web
 - Browser Chrome

**Comment by RodrigoSMarques** [comment]
I'll investigate. 

Today I generated a new release and the example [application](https://flutter-branch-sdk.netlify.app) that was working started to show the same error.

**Comment by RodrigoSMarques** [comment]
Fixed in version 5.0.0.

If necessary open again.
