### ISSUE TITLE
getShortUrl creates wrong domains + incorrect data on Android

### ISSUE THREAD

**Issue by stx** [RodrigoSMarques/flutter_branch_sdk#138]
```
    BranchUniversalObject buo = BranchUniversalObject(
      canonicalIdentifier: 'referral',
      canonicalUrl: 'https://mysite.com',
      title: 'My title here',
      contentDescription: 'Use my link!',
      publiclyIndex: false,
      locallyIndex: false,
    );

    BranchLinkProperties lp = BranchLinkProperties(
      feature: 'referral',
    )..addControlParam('referring_user_id', 'asdf');

    BranchResponse<dynamic> response = await FlutterBranchSdk.getShortUrl(
      buo: buo,
      linkProperties: lp,
    );
```

On iOS, this code generates correct links with correct data:

`https://myapp.app.link/ExfEt1ggAmb`

On Android, this code creates 2 wrong types of links:

Correct domain, missing path /, wrong link with no referring_user_id data:

`https://myapp.app.link?feature=referral&type=0&duration=0&source=android&data=<long string here>`

Wrong domain, also no referring_user_id data:

`https://bnc.lt/a/key_live_abcd1234?feature=referral&type=0&duration=0&source=android&data=<long string here>`

**Comment by stx** [comment]
Looks like `FlutterBranchSdk.disableTracking(true)` is the culprit. If this is set on Android, incorrect links are generated in the Branch SDK. iOS doesn't behave this way, and generates correct links with disabled tracking. Branch SDK bug?

**Comment by RodrigoSMarques** [comment]
Please complete the following information):**
 - Flutter: version: [e.g. 2.2.3]
 - Package version: [e.g. 3.3.0]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]

**Comment by RodrigoSMarques** [comment]
If the device is not connected to the internet, links can be generated with a long url.

The configuration in AndroidManifest.xml also defines how the link will be generated: 
[https://help.branch.io/developers-hub/docs/android-troubleshooting#using-bnclt-or-a-custom-link-domain](https://help.branch.io/developers-hub/docs/android-troubleshooting#using-bnclt-or-a-custom-link-domain)

**Comment by stx** [comment]
Thanks @RodrigoSMarques! Good to know about the internet connection.

Flutter: 2.8.1
Package: 4.0.0
Device: Pixel 6
OS: Android 12

**Comment by RodrigoSMarques** [comment]
Download the sample project and run it. Check if these errors also happen in it.

**Comment by RodrigoSMarques** [comment]
> Thanks @RodrigoSMarques! Good to know about the internet connection. Still no idea why bnc.it are links are generated instead of what's in AndroidManifest. Maybe also connection related.
> 
> Flutter: 2.8.1 Package: 4.0.0 Device: Pixel 6 OS: Android 12

Physical device or emulator?

**Comment by RodrigoSMarques** [comment]
Does the problem still persist?

**Comment by stx** [comment]
Physical device.

Yes, if `FlutterBranchSdk.disableTracking(true)` is set on Android, incorrect links are generated in the Branch SDK. Works on iOS.

**Comment by jf-branch** [comment]
Hi @RodrigoSMarques and @stx, 

Justin from Branch here. When disableTracking is enabled, Branch does not make any API calls to our servers. Therefore the SDK will generate a Long Link, aka your Branch app.link, and apply all link properties as query parameters, which is the reason why you are not seeing a short link with an alias. This is expected behavior when disableTracking is enabled. It is not an incorrect link, its a Long Link.

**Comment by stx** [comment]
@jf-branch

Thanks, but we have `FlutterBranchSdk.disableTracking(true);` enabled on iOS and it works fine.

**Comment by RodrigoSMarques** [comment]
> Hi @RodrigoSMarques and @stx,
> 
> Justin from Branch here. When disableTracking is enabled, Branch does not make any API calls to our servers. Therefore the SDK will generate a Long Link, aka your Branch app.link, and apply all link properties as query parameters, which is the reason why you are not seeing a short link with an alias. This is expected behavior when disableTracking is enabled. It is not an incorrect link, its a Long Link.

Thanks for the answer @jf-branch .

**Comment by stx** [comment]
@RodrigoSMarques @jf-branch 

```
Future<void> main() async {
  FlutterBranchSdk.disableTracking(true);
  await FlutterBranchSdk.getShortUrl(buo: buo, linkProperties: lp);
}
```

Returns a short link on iOS. Logs from the Branch SDK indicate that tracking is disabled. So does it work differently on iOS, is tracking not actually being disabled, or what is going on?

**Comment by RodrigoSMarques** [comment]
> @jf-branch
> 
> Thanks, but we have `FlutterBranchSdk.disableTracking(true);` enabled on iOS and it works fine.

But this is not the correct behavior. It should be like on Android.

There may be a bug in the iOS call.

I'm going to do a test with the example project, I'll check the code and then report the result.

Here it explains about disableTracking.

[https://help.branch.io/developers-hub/docs/honoring-opt-out-of-processing-requests](https://help.branch.io/developers-hub/docs/honoring-opt-out-of-processing-requests)

**Comment by RodrigoSMarques** [comment]
> @RodrigoSMarques @jf-branch
> 
> ```
> Future<void> main() async {
>   FlutterBranchSdk.disableTracking(true);
>   await FlutterBranchSdk.getShortUrl(buo: buo, linkProperties: lp);
> }
> ```
> 
> Returns a short link on iOS. Logs from the Branch SDK indicate that tracking is disabled. So does it work differently on iOS, is tracking not actually being disabled, or what is going on?

For me it should work the same on both platforms.

This is a function of Branch SDK, I can't say if iOS is different.

@jf-branch can you confirm?

**Comment by stx** [comment]
Hmm. Seems like it is the correct behavior?

<img width="660" alt="Screen Shot 2022-01-26 at 4 47 07 PM" src="https://user-images.githubusercontent.com/1284134/151271124-5cdfbe59-6bc2-4c6e-866f-726692aafb44.png">

**Comment by stx** [comment]
It would be good to describe this difference of behavior in the disableTracking call, and maybe the getShortUrl call. It's consistent with what we found after a lot of experimentation, so I don't think there's a bug here.

**Comment by RodrigoSMarques** [comment]
I will include the link I sent you in the package documentation to facilitate understanding.

As it is a Branch SDK process, I prefer to mention the official documentation for reference.
