### ISSUE TITLE
logs gets printed when app is opened from dynamic Link even when logs are disabled

### ISSUE THREAD

**Issue by Not-Dhanraj** [RodrigoSMarques/flutter_branch_sdk#140]
**Describe the bug**
link data is logged when app is opened from link

**To Reproduce**
open App through generated link

**Expected behavior**
when logs are disabled, those logs should not logged as well

**Smartphone**
 - Flutter: version:  2.8.1
 - Package version: 4.0.0
 - OS: Android

**Comment by RodrigoSMarques** [comment]
Can you send me a print of the logs being displayed and the configuration in AndroidManifest.xml?

**Comment by Not-Dhanraj** [comment]
i am really sorry for my late response. i am currently away from my computer, i am sending android manifest now, i'll send logs after few days.

`
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.paradox.wallcanic">
    <queries>
  
  <intent>
    <action android:name="android.intent.action.VIEW" />
    <data android:scheme="https" />
  </intent>
  
  <intent>
    <action android:name="android.intent.action.SEND" />
    <data android:mimeType="*/*" />
  </intent>
</queries>
   <application
        android:label="WallCanic Walls"
        android:name=".CustomApplication"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTask"
            android:theme="@style/LaunchTheme"
            android:exported="true"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
              <intent-filter>
    <action android:name="android.intent.action.VIEW"/>
    <category android:name="android.intent.category.DEFAULT"/>
    <category android:name="android.intent.category.BROWSABLE"/>
    <data
        android:host="wallcanic.page.link"
        android:scheme="https"/>
</intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            
            <intent-filter>
                <data android:scheme="wallcanic" android:host="open"/>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
            </intent-filter>
            
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="https" android:host="flutterbranchsdk.app.link" />
                <data android:scheme="https" android:host="wallcanic-alternate.app.link" />
                <data android:scheme="https" android:host="wallcanic-alternate.test-app.link" />
                <data android:scheme="https" android:host="wallcanic.test-app.link" />
            </intent-filter>
        </activity>
        <activity
    android:name="com.yalantis.ucrop.UCropActivity"
    android:screenOrientation="portrait"
    android:theme="@style/Theme.AppCompat.Light.NoActionBar"/>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
        
        <meta-data
            android:name="io.branch.sdk.BranchKey"
            android:value="${branchKey}" />
        
        <meta-data
            android:name="io.branch.sdk.BranchKey.test"
            android:value="${branchKeyTest}" />
        <meta-data android:name="io.branch.sdk.TestMode" android:value="false" />
        <meta-data android:name="branch_enable_log"
            android:value="false" />
<service
    android:name="dev.fluttercommunity.plus.androidalarmmanager.AlarmService"
    android:permission="android.permission.BIND_JOB_SERVICE"
    android:exported="false"/>
<receiver
    android:name="dev.fluttercommunity.plus.androidalarmmanager.AlarmBroadcastReceiver"
    android:exported="false"/>
<receiver
    android:name="dev.fluttercommunity.plus.androidalarmmanager.RebootBroadcastReceiver"
    android:enabled="false"
    android:exported="false">
    <intent-filter>
        <action android:name="android.intent.action.BOOT_COMPLETED" />
    </intent-filter>
</receiver>
    </application>
   <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
   <uses-permission android:name="android.permission.SET_WALLPAPER" />
   <uses-permission android:name="android.permission.INTERNET" />
   <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
   <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
   <uses-permission android:name="android.permission.WAKE_LOCK"/>
   <uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM"/>
</manifest>
`

**Comment by Not-Dhanraj** [comment]
i am really sorry for my late response. I am currently away from my computer. i will send logs as soon as possible. as for now i am sending androidmanifest.xml 
https://pastebin.com/WcRtx2US

**Comment by RodrigoSMarques** [comment]
@Not-Dhanraj  

I'm waiting for your return. What logs are being displayed?

Did you see these [instructions](https://pub.dev/packages/flutter_branch_sdk#enable-logging) ?

Check your AndroidManifest, it has an error:

![Captura de Tela 2022-02-17 às 10 31 13](https://user-images.githubusercontent.com/17687286/154491972-3fb01d4d-484e-4208-9597-2cfbf881c9f4.png)

**Comment by Not-Dhanraj** [comment]
Thanks for the reminder.

yup, i did read instructions?
this manifest error was in old version which was fixed later.

Here's logs which gets printed even logs are disabled

`D/FlutterBranchSDK( 6841): BranchReferralInitListener - params: {"$og_title":"Wall42 - WallCanic Walls","thumb":"https:\/\/gitfront.io\/r\/DhanrajPriyadarshi\/95f7a960d22404692828ed3cd9bdb103b374f6d5\/Template\/raw\/Template_42.jpg","description":"This is description of a wallpaper, this should not be too long, not be too short, unique for everyone,and for deb,there is a note:Be sure that it doesn't Overflows","source":"android","$identity_id":1022901355143911730,"~stage":"share","resolution":"","~feature":"sharing","$canonical_identifier":"walllcanic:\/\/","~id":1022903741354172924,"+is_first_session":false,"~channel":"Gmail","id":"541387","$exp_date":"1645742067765","$publicly_indexable":"true","~creation_source":2,"author":"Dhanraj","$og_description":"This is description of a wallpaper, this should not be too long, not be too short, unique for everyone,and for deb,there is a note:Be sure that it doesn't Overflows","+click_timestamp":1645117545,"$uri_redirect_mode":"1","$og_image_url":"https:\/\/raw.githubusercontent.com\/Not-Dhanraj\/test-walls\/main\/icon.png","url":"https:\/\/gitfront.io\/r\/DhanrajPriyadarshi\/f89c76b660d7af37bc01504d5701f6ea60c6aa26\/Wallpapers\/raw\/Wallpapers_42.jpg","+match_guaranteed":true,"timeStamp":"2021-05-11 11:53:49.692958","size":"","+clicked_branch_link":true,"$one_time_use":false,"name":"Wall42","~referring_link":"https:\/\/wallcanic.app.link\/ERN5G9z4Inb","category":"General"}`


Also i found a weird bug in latest version of branch that When app is opened from deeplink,and when deeplink page is popped. When app is putted in background by os. after these when app is opened from recent apps then clicked_branch_link is true. Should i open a new bug for this?

**Comment by RodrigoSMarques** [comment]
> BranchReferralInitListener

This is an internal SDK log. There's no way to disable it.
It is only displayed in debug mode to make it easier to see the data that was returned by the deeplink.
In the release model it is not displayed.

Only Branch SDK logs can be turned off.

Open another issue with the details so it can be reproduced.

Do not delete the bug template and fill in the requested information.
