### ISSUE TITLE
Trouble handling ipApp links

### ISSUE THREAD

**Issue by Vedenalex** [RodrigoSMarques/flutter_branch_sdk#145]
**Describe the bug**
Fuctionality of deeplinks in application works different on emulator and on real Android Device. When I try to open the link that direct's me to the app from outside the app, everything works perfectly: on emulator and on real device. Application open's and the desired page is reached. But when I try to open the same link inside the app(using await launch()), the application act's differently: on emulator it works perfectly, onNewIntent is called and necessary page is opened. On the real Android Device the situation is different: when i try to open the link, instead of onNewIntent, the onActivityStopped, onActivityCreated and onActivityStarted are called.
Also there is another thing I wanted to ask about. There is a documentation that is created to help with branch setup. In this documentation, there is a paragraph that should help handle inApp links(https://help.branch.io/developers-hub/docs/android-advanced-features#handle-links-in-your-own-app). Acoarding to this documentation, I added this line ( intent.putExtra("branch_force_new_session",true); ) to onNewIntent function for inApp links to work. Where should this 4 lines from the documentation should be added, if you are creating an application with Flutter?
**To Reproduce**
1. await launch('link');
2. The behaivour after is described above

**Expected behavior**
Also described above

**Screenshots**

**Desktop (please complete the following information):**
 - Flutter: version: [e.g. 2.10.0]
 - Package version: [e.g. 4.0.0]
 - OS: [e.g. Windows]
 - Browser [e.g. chrome]

**Smartphone (please complete the following information):**
 - Flutter: version: [e.g. 2.10.0]
 - Package version: [e.g. 4.0.0]
 - Device: [e.g. Android]
 - OS: [e.g. AndroidOS]

**Additional context**
-

**Comment by RodrigoSMarques** [comment]
Regarding the difference between the emulator and the real device, I don't know what it can be.
Are both devices on the same Android version?

About Handle Links in Your Own App, it is not possible to make this call in Flutter.
You would have to call Platform Channel to call native code (java/kotlin) to run that code.

**Comment by Vedenalex** [comment]
Thank you for you reply. I tested app on emulator using android 8 and
android 11 versions. On real devices versions were 8,9,10. Result was the
same. On emulator everything works perfectly on 11 version, but on Android
8 problem is the same as on real devices. On real devices all versions I
tested had this problem.

Сб, 19 февр. 2022 г. в 08:03, Rodrigo de Souza Marques <
***@***.***>:

**Comment by Vedenalex** [comment]
Updated information: launching link inside the app works fine on android
versions 10 and 11(both on emulator and real devices), but it doesn’t work
on android versions 9 and below(also both on devices and emulators)

Вс, 20 февр. 2022 г. в 18:59, Алексей Веденцов ***@***.***>:

**Comment by RodrigoSMarques** [comment]
I believe this has nothing to do with the package, but the way Android handles it in different versions.

I don't know if the url_laucher package does something different for android versions.

I will review and then get in touch.

**Comment by Vedenalex** [comment]
Thank you for your support, I already found the problem and fixed it using
platform channel. So it isn’t necessary to review this problem. Thank you
again

Ср, 23 февр. 2022 г. в 16:47, Rodrigo de Souza Marques <
***@***.***>:
