### ISSUE TITLE
Need  Last Attributed Touch Data option in SDK

### ISSUE THREAD

**Issue by jineshsoni** [RodrigoSMarques/flutter_branch_sdk#148]
We need an option to fetch  Last Attributed Touch Data from native branch SDK, as of not it's not available in flutter SDK.

Reference doc: https://help.branch.io/developers-hub/docs/retrieving-branchs-last-attributed-touch-data#web

**Comment by RodrigoSMarques** [comment]
Not Available.

I will read the documentation and evaluate

**Comment by RodrigoSMarques** [comment]
Can you help me by testing a new version with enhancement?

Update `pubspec.yaml`, as in the example below:

```dart
#flutter_branch_sdk:
flutter_branch_sdk:
    git:
      url: https://github.com/RodrigoSMarques/flutter_branch_sdk.git
      ref: dev
```

call:

```dart
    BranchResponse response =
        await FlutterBranchSdk.getLastAttributedTouchData();
    if (response.success) {
      showSnackBar(
          context: context, message: response.result.toString(), duration: 5);
    } else {
      showSnackBar(
          context: context,
          message:
              'showShareSheet Error: ${response.errorCode} - ${response.errorMessage}',
          duration: 5);
    }
```

**Comment by jineshsoni** [comment]
Hello @RodrigoSMarques, Yes i tested this and it seems working fine now.

Just add missing break statement in `FlutterBranchSdkPlugin.java`

`case "getLastAttributedTouchData":
                getLastAttributedTouchData(call, result);
                break;`

**Comment by RodrigoSMarques** [comment]
Version 5.1.0 with fix released
