### ISSUE TITLE
Infinite loop with POST requests when offline

### ISSUE THREAD

**Issue by stevenmetzger** [RodrigoSMarques/flutter_branch_sdk#153]
**Describe the bug**
Hi Rodrigo, thanks for the awesome package!

When there is no internet connection available (Wi-Fi and mobile are off) an app using flutter_branch_sdk loops forever attempting to POST to https://api2.branch.io/v1/open. The Log output is flooded (very fast) with messages saying "Unable to resolve host, 'api2.branch.io': No address associated with hostname". I could just turn off the logging, but these requests are happening way too often. Would it be possible for the SDK to slowly back-off and not attempt so many times? I'm concerned this could negatively impact the app performance or battery usage when using the app while offline.

Also note that `FlutterBranchSdk.disableTracking(true);` will stop this from happening. But I don't think this is a good fix because it disables other features of Branch that I would like to use.

```
I/BranchSDK(24089): posting to https://api2.branch.io/v1/open
I/BranchSDK(24089): Post value = {"device_fingerprint_id":"...","identity_id":"...","hardware_id":"...","is_hardware_id_real":true,"brand":"Google","model":"Pixel 5","screen_dpi":440,"screen_height":2160,"screen_width":1080,"wifi":false,"ui_mode":"UI_MODE_TYPE_NORMAL","os":"Android","os_version":32,"cpu_type":"aarch64","build":"...","locale":"en_US","device_carrier":"...","os_version_android":"12","country":"US","language":"en","partner_data":{},"app_version":"...","initial_referrer":"...","facebook_app_link_checked":false,"debug":false,"update":1,"latest_install_time":1652289483267,"latest_update_time":1652289483267,"first_install_time":1652289483267,"previous_update_time":1652289483267,"environment":"FULL_APP","metadata":{},"advertising_ids":{"aaid":"..."},"lat_val":0,"google_advertising_id":"...","instrumentation":{"v1\/open-brtt":"0","v1\/open-qwt":"0"},"sdk":"android5.1.0","branch_key":"key_live_..."}
I/BranchSDK(24089): Http connect exception: Unable to resolve host "api2.branch.io": No address associated with hostname
I/BranchSDK(24089): processNextQueueItem, req ServerRequestRegisterOpen
```

**To Reproduce**
1. Setup a Flutter app using flutter_branch_sdk
2. Turn off all internet connections for your Android phone
3. Run the app
4. Inspect the Log output in the console

**Expected behavior**
A small number of log messages indicating "Unable to resolve host, 'api2.branch.io': No address associated with hostname"

**Smartphone (please complete the following information):**
 - Flutter: version: 2.10.5
 - Package version: 5.0.0
 - Device: Pixel 5
 - OS: Android version 12

**Comment by gdeluna-branch** [comment]
Hi @stevenmetzger This was fixed as of the latest branch android sdk. @RodrigoSMarques please update to 5.1.4 . Thanks

**Comment by RodrigoSMarques** [comment]
Hello guys.

@gdeluna-branch, thanks for the answer. 

I already have a new version updated to latest version of Android SDK.

I haven't released the version yet, as I'm investigating a bug that came up after developing a new feature in the package.

I plan to make the new version available within the next few days.

@stevenmetzger 
I'll keep the issue open and let you know when it's released.

**Comment by RodrigoSMarques** [comment]
Can you help me by testing a new version with the fix?

Update `pubspec.yaml`, as in the example below:

```dart
#flutter_branch_sdk:
flutter_branch_sdk:
    git:
      url: https://github.com/RodrigoSMarques/flutter_branch_sdk.git
      ref: dev
```

**Comment by stevenmetzger** [comment]
@RodrigoSMarques The fix seems to work. If there is no Internet connection available branch will still post to https://api2.branch.io/v1/install every 1 second or so. But I'm not seeing the huge number of posts to https://api2.branch.io/v1/open that I was seeing before.

Thanks for fixing this so quickly.

**Comment by RodrigoSMarques** [comment]
Excellent. I'm waiting for the response from running tests on other issues. When completed, I will release the version

**Comment by RodrigoSMarques** [comment]
Version 5.1.0 with fix released
