### ISSUE TITLE
Share sheet crashing the app for iOS 13 and above

### ISSUE THREAD

**Issue by uddyami** [RodrigoSMarques/flutter_branch_sdk#154]
App crashes when trying to open share sheet 

crash report
```
Could not cast value of type 'Runner.SplashViewController' (0x10a7035d0) to 'FlutterViewController' (0x114d4d320).
2022-05-06 12:02:47.129337+0530 Runner[35837:193747] Could not cast value of type 'Runner.SplashViewController' (0x10a7035d0) to 'FlutterViewController' (0x114d4d320).
dyld4 config
```

**To Reproduce**

button click responds with following code
```
var response = await FlutterBranchSdk.showShareSheet(
        buo: _branchUniversalObject(),
        linkProperties: _linkProperties(referralCode: referralCode),
        messageText:
            'Hey, want check this out");
```

**Expected behavior**
share sheet open up 

**Desktop (please complete the following information):**
 - Flutter: version: 2.10.4
 - Package version: 5.0.0
 - OS: ios

**Comment by RodrigoSMarques** [comment]
Hi @uddyami .
You have made some changes to your native ios project.

I am not right? What change was made.

`SplashViewController` is not of type `FlutterViewController`

**Comment by uddyami** [comment]
we have not made any changes but code breaks 
https://github.com/RodrigoSMarques/flutter_branch_sdk/blob/master/ios/Classes/SwiftFlutterBranchSdkPlugin.swift#L265

**Comment by RodrigoSMarques** [comment]
In your project the rootViewController was changed in the StoryBoard. 

The new root is not of type FlutterViewController.

Today the cast is no longer needed, I will remove it in the next update.

**Comment by RodrigoSMarques** [comment]
Can you help me by testing a new version with the fix?

Update `pubspec.yaml`, as in the example below:

```dart
#flutter_branch_sdk:
flutter_branch_sdk:
    git:
      url: https://github.com/RodrigoSMarques/flutter_branch_sdk.git
      ref: dev
```
