### ISSUE TITLE
Trouble with handling deeplinks from other apps

### ISSUE THREAD

**Issue by Vedenalex** [RodrigoSMarques/flutter_branch_sdk#156]
**Describe the bug**
I faced an issue trying to handle deeplinks on iOS devices when I opened them from Skype. Links that are handled from Skype are totally ignored. All information I found on the web tells me that the best option is to make an ability to relocate to the application by creating a specific button on the landing page that will allow to navigate where I need. Because of some circumstances I do not have the possibility to solve the problem this way. Is there an opportunity to solve it otherwise? (uri_redirect_mode is set to 2)

**To Reproduce**
1. Send link to the Skype chat
2. Open the link

**Expected behavior**
The toast that will allow me to get to my app is apeared

**Screenshots**

**Desktop (please complete the following information):**
 - Flutter: version: 3.0.0
 - OS: iOS
 - Browser Chrome, Safari

**Smartphone (please complete the following information):**
 - Device: iPhone7 / Iphone10
 - OS:  iOS 15 / iOS 15.5

**Comment by RodrigoSMarques** [comment]
If the reported issue is a bug, it is not related to the Flutter package, but to Branch's native SDK.

I sent a message to Branch support to review your issue, but I still haven't gotten a response. If desired, open an issue in the iOS SDK repository: [https://github.com/BranchMetrics/ios-branch-deep-linking-attribution](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution)
