### ISSUE TITLE
Feature request: Enable runtime switch between test and live keys or initialization based on dart code

### ISSUE THREAD

**Issue by dzsonni** [RodrigoSMarques/flutter_branch_sdk#167]
Would it be possible to integrate the ability to switch between live and test branch keys? We would like to enable for our qa to test both prod and debug links in the same app with an app restart when switching environments.

**Comment by RodrigoSMarques** [comment]
Hi @dzsonni.
Still interested in this feature?

**Comment by RodrigoSMarques** [comment]
Functionality available in the new beta version 7.0.0: [https://pub.dev/packages/flutter_branch_sdk/versions/7.0.0-beta.0](https://pub.dev/packages/flutter_branch_sdk/versions/7.0.0-beta.0)
