### ISSUE TITLE
Freshly installed app doesn't receive links

### ISSUE THREAD

**Issue by matthewfx** [RodrigoSMarques/flutter_branch_sdk#168]
**Describe the bug**
The links work when my app is installed but when it isn't after installing it seems like no data is being passed to the freshly installed app.

**To Reproduce**
1. Click the link
2. The link takes you to the App Store
3. Install the app
4. Launch the app 
5. The app doesn't perform an action that the payload of the deep link should trigger.

**Expected behavior**
After launching the freshly installed app should trigger action triggered by the payload. That behaviour is triggered when you click the link with the app previously installed.

**Smartphone (please complete the following information):**
 - Flutter: 3.0.5
 - Package version: 6.0.0
 - Device: iPhone 13 Pro Max, iPhone Xs Max
 - OS: 15.6.1

**Comment by jf-branch** [comment]
@matthewfx Given the changes with Apple's Privacy Policy, App Tracking Transparency, Private Relay, etc, Deferred Deep Linking, or Deep Linking through the App Store is a much greater challenge. Branch did create the [NativeLink](https://help.branch.io/faq/docs/nativelink-deferred-deep-linking) feature to support Deferred Deep Linking on iOS 14.5+ at a more successful rate, however, the Apple App Store does not have an API like the Google Play Stores Install Referrer, meaning success has to depend on Probabilistic Matching or our [PREM](https://help.branch.io/using-branch/docs/predictive-modeling#overview) feature, but again, without NativeLink, there is not 100% guarantee.

**Comment by matthewfx** [comment]
@jf-branch Thank you. Actually, I've enabled the native link before (with audience rule set to all iOS traffic). Should I change the audience rule to make it work? There is one more thing at my end which might be a reason it doesn't work for me... My app just listens for deep links and when I went through your docs again I realised I should have used getFirstReferringParams(). I will check when I release a new version. Hopefully, it will work this time. BTW Please make it more prominent in your docs. :)

**Comment by matthewfx** [comment]
@jf-branch Hey, I've made that change and used `getFirstRefferingParams()`. It worked. Now I have another question/issue. The link worked after the installation but now even if I kill and launch the app not from a link it still behaves like launched by it. So it somehow preserved that initial link and keeps using it every time I launch it. Why is it happening?

**Comment by RodrigoSMarques** [comment]
@matthewfx 
You must use `FlutterBranchSdk.getLatestReferringParams()` to retrieve the parameters of the last session opened by the app.

`FlutterBranchSdk.getFirstReferringParams()` returns the parameters that were used to install the app.

You can find more information [here](https://github.com/RodrigoSMarques/flutter_branch_sdk#retrieve-session-install-or-open-parameters)

**Comment by matthewfx** [comment]
Cool wasn't aware `getFirstReferringParams()` would be preserved during subsequent launches. Thanks!

**Comment by kvenn** [comment]
I'm seeing this same issue. I can create a new issue if you'd prefer (I also saw this one recently closed: https://github.com/RodrigoSMarques/flutter_branch_sdk/issues/231)

I followed these steps on both a simulator and a physical device: https://help.branch.io/developers-hub/docs/ios-testing

When clicking the link in the Deferred Deeplink case (installing the app), getFirstReferringParams does not contain the payload (only is first sesesion = true, branch link click = false).

I tried NativeLink
1. Added `branch_check_pasteboard` to info.plist
2. Clicked my link with the query param: (example: branch.app.link/abc?$ios_nativelink=true)

But never got the prompt to paste. 

I'd love any help, thank you!

**Comment by RodrigoSMarques** [comment]
Hi @kvenn 

Are you calling the `FlutterBranchSdk.setIdentity()` method at any point?

**Comment by kvenn** [comment]
Thanks for the quick response! I am not calling `setIdentity` anywhere.

**Comment by RodrigoSMarques** [comment]
@kvenn 

if payload contains branch link click = false it is because the deeplink you clicked has a problem.

Was the link you are accessing generated by the FlutterBranchSdk.getShortUrl, FlutterBranchSdk.shareWithLPLinkMetadata or FlutterBranchSdk.showShareSheet methods?

@jf-branch 
Do you have any suggestions?

**Comment by kvenn** [comment]
It was generated on my backend (via POST to `http://api2.branch.io/v1/url`). But I've also tried using a link generated in the GUI. 

Also if I click the link after the app is installed, the `initSession` listener receives it with all the data correctly showing.

My assumption was an issue with fingerprinting, but I tried on iOS 15 when it was supposedly more reliable, and the issue persisted. 

Thank you for looking into it 🙏 Happy to provide more details and context.

**Comment by CristianCanalesAnd** [comment]
Hello I have the same problem on first install. I don't receiving any data.

{+is_first_session: true, +clicked_branch_link: false}

1.- Generated the link on the website
2.- Added branch_check_pasteboard to info.plist
3.- Added query params to my url (branch.app.link/abc?$ios_nativelink=true)
4.- Calling logout before uninstall the app to test again.

**Comment by RodrigoSMarques** [comment]
@kvenn  and @CristianCanalesAnd 

I checked if the Branch SDK implementation in the plugin code was outdated or missing something and everything is correct.

I didn't identify any problems with the Flutter plugin.

I suggest opening a support ticket to the Branch team.

Open an issue in the platform repository:

- iOS: [https://github.com/BranchMetrics/ios-branch-deep-linking-attribution](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution)
- Android: [https://github.com/BranchMetrics/android-branch-deep-linking-attribution](https://github.com/BranchMetrics/android-branch-deep-linking-attribution)

Or open a support ticket for Branch at the [link] (https://help.branch.io/using-branch/page/submit-a-ticket)

**Comment by kvenn** [comment]
In your testing of a sample app, have you observed a different behavior? Is getFirstReferringParams returning a value for you given the repro steps I provided?

**Comment by RodrigoSMarques** [comment]
> Thanks for the response.
> 
> 
> 
> In your testing, have you observed a different behavior? Is getFirstReferringParams returning a value for you given the repro steps I provided?

Today I don't have any published applications to test. 

I'll see if Apple agrees to publish the example application to test it.

**Comment by kvenn** [comment]
In this guide, it suggests that it's possible to test without having the app in the app store: https://help.branch.io/developers-hub/docs/ios-testing (Test Deferred Deep Link section)

**Comment by kvenn** [comment]
I've seen other people experience issues. I'm not sure if there's something internal to the library. Or if it's in my implementation of it.

https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/issues/936#issuecomment-1356318234
https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/issues/1041#issuecomment-777155804
https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/issues/1057#issuecomment-1562588980

**Comment by RodrigoSMarques** [comment]
@kvenn 

I ran the test on the example application and got the same error.

During application installation, the deeplink is recognized from the clipboard, but no data is returned.

I need to run some more tests.

@jf-branch Do you have any suggestions or guidance?

**Comment by kvenn** [comment]
Great, sounds like you're making progress on the issue. Please let me know if I can help! This is a big one for us.

**Comment by RodrigoSMarques** [comment]
I developed a native application in Swift. 
the same problem occurred: does not retrieve link data on install.
I will make direct contact with Branch Support

**Comment by jf-branch** [comment]
Hi all, as mentioned in my initial comment: 

> Given the changes with Apple's Privacy Policy, App Tracking Transparency, Private Relay, etc, Deferred Deep Linking, or Deep Linking through the App Store is a much greater challenge. Branch did create the [NativeLink](https://help.branch.io/faq/docs/nativelink-deferred-deep-linking) feature to support Deferred Deep Linking on iOS 14.5+ at a more successful rate, however, the Apple App Store does not have an API like the Google Play Stores Install Referrer, meaning success has to depend on Probabilistic Matching or our [PREM](https://help.branch.io/using-branch/docs/predictive-modeling#overview) feature, but again, without NativeLink, there is not 100% guarantee.

Unfortunately iOS doesn't provide an Install Referrer API like Google does for the Playstore, so there is no guarantee Branch can match and return deep link data on first opens / installs. 

I highly recommend if you run into these scenarios to go through our support team, where specific Flutter feature gaps or bugs can be done through GH issues. This also goes with our other SDKs, but product gaps and bugs are best suited to go through our support team. You can do so through our ticket submission portal: https://help.branch.io/using-branch/page/submit-a-ticket

**Comment by kvenn** [comment]
Hi Justin! Thanks for your reply! I'm VERY excited about finding a resolution to this problem. 

I tried to submit a ticket through support, but unfortunately I just see an empty page whenever I click "Submit". So I tried here and the Github Issues for Flutter and iOS.
I'm on Chrome, btw.

<img width="1408" alt="SCR-20230928-lzyv" src="https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/1782467/ddc1ea82-f60f-4390-a254-b36b7b65fe02">

**Comment by RodrigoSMarques** [comment]
Hey guys.

I ran several tests and identified a strange behavior in version 6.8.0 of the package that does not occur in version 7.0.0 (which will be released this week in beta).

In version 6.8.0 of the package, the application is installed, the prompt appears asking for permission to copy, initSession returns _["+is_first_session": true, "+clicked_branch_link": false]_, but the installation deeplink data is not retrieved with _getFirstReferringParams()_;

In version 7.0.0, the data is returned successfully. I have already compared the code between the two versions and there is no difference.

@kvenn and @CristianCanalesAnd 
Can you test the new version in your project and check if the behavior is correct?

Update the `pubspec.yaml`:

```dart
#flutter_branch_sdk:
flutter_branch_sdk:
    git:
      url: https://github.com/RodrigoSMarques/flutter_branch_sdk.git
      ref: version7
```

Update `main` for call `init` (check optional parameters if necessary):
```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await FlutterBranchSdk.init( );
  runApp(const MyApp());
}
```

**Comment by RodrigoSMarques** [comment]
New version available in beta, which in my tests did not present any problems:

- [https://pub.dev/packages/flutter_branch_sdk/versions/7.0.0-beta.0](https://pub.dev/packages/flutter_branch_sdk/versions/7.0.0-beta.0)
- [https://pub.dev/packages/flutter_branch_sdk/versions/7.0.0-beta.0/changelog](https://pub.dev/packages/flutter_branch_sdk/versions/7.0.0-beta.0/changelog)

**Comment by RodrigoSMarques** [comment]
Release 7.0.0 available

**Comment by korolkir** [comment]
Hello @kvenn @matthewfx Were you guys able to resolve the issue? I believe I'm experience the exactly same problem with the latest version of the plugin.

**Comment by kvenn** [comment]
I've updated the plugin and am _also_ still seeing this issue still.

When testing locally on a physical device (using the technique mentioned in this thread), I wasn't seeing any data on version 6.x. After updating to 7.x, I _do_ see data.

But I've observed in production a much higher failure rate for installs. 

I this screenshot below, you can see Branch saw the click, missed the install, and then got an open. We got 280 installs in this time period, 100% of which came from a branch link. I'd be happy if at least the installs and opens matched up. Also, these are unique counts (not totals). So installs really should match opens.

<img width="1058" alt="SCR-20231219-ogrj" src="https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/1782467/5d542512-eb9e-4951-8737-386213196284">

**Comment by RodrigoSMarques** [comment]
> I've updated the plugin and am _also_ still seeing this issue still.
> 
> When testing locally on a physical device (using the technique mentioned in this thread), I wasn't seeing any data on version 6.x. After updating to 7.x, I _do_ see data.
> 
> But I've observed in production a much higher failure rate for installs.
> 
> I this screenshot below, you can see Branch saw the click, missed the install, and then got an open. We got 280 installs in this time period, 100% of which came from a branch link. I'd be happy if at least the installs and opens matched up. Also, these are unique counts (not totals). So installs really should match opens.
> 
> <img alt="SCR-20231219-ogrj" width="1058" src="https://private-user-images.githubusercontent.com/1782467/291921910-5d542512-eb9e-4951-8737-386213196284.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwODQyNjksIm5iZiI6MTcwMzA4Mzk2OSwicGF0aCI6Ii8xNzgyNDY3LzI5MTkyMTkxMC01ZDU0MjUxMi1lYjllLTQ5NTEtODczNy0zODYyMTMxOTYyODQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjBUMTQ1MjQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2ZlY2QwOWI5MWM1ZWFhYTZlMjY4MmI2YzhiYWUzYmQwYzFmMmY2ZWIyMmM1ZjEzMDI3YmIxODM4YjlhNDY3YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kZGeXlOBSdOo0uwbY0VTc6p12MKnUbhCrzfixqubsjc">
> My team and I are investigating further. We're playing around with network connectivity being the issue. In testing 10 times locally, we dropped only 1 install. And we're seeing a MUCH higher rate of dropped install events in prod.

Hi @jf-branch 

Can you make any comments about this item.
