### ISSUE TITLE
get ANDROID_ID  before Privacy Agreement dialog show

### ISSUE THREAD

**Issue by shingohu** [RodrigoSMarques/flutter_branch_sdk#171]
**Describe the bug**
The plugin will get ANDROID_ID  before Privacy Agreement dialog show,and will be reject by app store like huawei ,xiaomi 

**To Reproduce**
at io.branch.referral.SystemObserver$UniqueId.<init>(SystemObserver.java:558)
E/PrivacyMethodHookProvider(22105): 	at io.branch.referral.SystemObserver.getUniqueID(SystemObserver.java:70)
E/PrivacyMethodHookProvider(22105): 	at io.branch.referral.DeviceInfo.getHardwareID(DeviceInfo.java:282)
E/PrivacyMethodHookProvider(22105): 	at io.branch.referral.DeviceInfo.updateRequestWithV1Params(DeviceInfo.java:50)
E/PrivacyMethodHookProvider(22105): 	at io.branch.referral.ServerRequest.setPost(ServerRequest.java:198)
E/PrivacyMethodHookProvider(22105): 	at io.branch.referral.ServerRequestInitSession.setPost(ServerRequestInitSession.java:48)
E/PrivacyMethodHookProvider(22105): 	at io.branch.referral.ServerRequestRegisterOpen.<init>(ServerRequestRegisterOpen.java:30)
E/PrivacyMethodHookProvider(22105): 	at io.branch.referral.Branch.getInstallOrOpenRequest(Branch.java:1959)
E/PrivacyMethodHookProvider(22105): 	at io.branch.referral.Branch$InitSessionBuilder.init(Branch.java:3129)
E/PrivacyMethodHookProvider(22105): 	at br.com.rsmarques.flutter_branch_sdk.FlutterBranchSdkPlugin.onActivityStarted(FlutterBranchSdkPlugin.java:180)
E/PrivacyMethodHookProvider(22105): 	at android.app.Application.dispatchActivityStarted(Application.java:413)
E/PrivacyMethodHookProvider(22105): 	at android.app.Activity.dispatchActivityStarted(Activity.java:1293)
E/PrivacyMethodHookProvider(22105): 	at android.app.Activity.onStart(Activity.java:1790)
E/PrivacyMethodHookProvider(22105): 	at io.flutter.embedding.android.FlutterActivity.onStart(FlutterActivity.java:589)

**Expected behavior**
not get ANDROID_ID  before init

**Smartphone (please complete the following information):**
 - Flutter: version 2.10.5
 - Package version: 5.1.1
 - Device: All Android

**Comment by RodrigoSMarques** [comment]
could you explain to me about this consent screen?

I don't understand what screen this is.

**Comment by shingohu** [comment]
> could you explain to me about this consent screen?
> 
> I don't understand what screen this is.

The privacy agreement dialog means that after entering the app for the first time, the user needs to be informed of what user related information the app has obtained, and can enter the app only after the user agrees. China's app stores require that user information, such as Android, IMEI, advertising ID and other important information, cannot be obtained before the privacy agreement dialog show



![31662517671_ pic](https://user-images.githubusercontent.com/4944887/188775060-099ed4ef-86d5-4110-8b96-7b7d55b80c04.jpg)

**Comment by RodrigoSMarques** [comment]
See those instructions [here](https://github.com/RodrigoSMarques/flutter_branch_sdk#enable-or-disable-user-tracking)

Maybe you should disable tracking at app start and enable it again only after consent.

More information [here](https://help.branch.io/developers-hub/docs/honoring-opt-out-of-processing-requests)

**Comment by shingohu** [comment]
> See those instructions [here](https://github.com/RodrigoSMarques/flutter_branch_sdk#enable-or-disable-user-tracking)
> 
> Maybe you should disable tracking at app start and enable it again only after consent.
> 
> More information [here](https://help.branch.io/developers-hub/docs/honoring-opt-out-of-processing-requests)

This is useless. It can't prevent getting ANDROID_ID
The plugin will get ANDROID_ID on onActivityStarted
this is the call stack：

```
at io.branch.referral.SystemObserver$UniqueId.(SystemObserver.java:558)
E/PrivacyMethodHookProvider(22105): at io.branch.referral.SystemObserver.getUniqueID(SystemObserver.java:70)
E/PrivacyMethodHookProvider(22105): at io.branch.referral.DeviceInfo.getHardwareID(DeviceInfo.java:282)
E/PrivacyMethodHookProvider(22105): at io.branch.referral.DeviceInfo.updateRequestWithV1Params(DeviceInfo.java:50)
E/PrivacyMethodHookProvider(22105): at io.branch.referral.ServerRequest.setPost(ServerRequest.java:198)
E/PrivacyMethodHookProvider(22105): at io.branch.referral.ServerRequestInitSession.setPost(ServerRequestInitSession.java:48)
E/PrivacyMethodHookProvider(22105): at io.branch.referral.ServerRequestRegisterOpen.(ServerRequestRegisterOpen.java:30)
E/PrivacyMethodHookProvider(22105): at io.branch.referral.Branch.getInstallOrOpenRequest(Branch.java:1959)
E/PrivacyMethodHookProvider(22105): at io.branch.referral.Branch$InitSessionBuilder.init(Branch.java:3129)
E/PrivacyMethodHookProvider(22105): at br.com.rsmarques.flutter_branch_sdk.FlutterBranchSdkPlugin.onActivityStarted(FlutterBranchSdkPlugin.java:180)
E/PrivacyMethodHookProvider(22105): at android.app.Application.dispatchActivityStarted(Application.java:413)
E/PrivacyMethodHookProvider(22105): at android.app.Activity.dispatchActivityStarted(Activity.java:1293)
E/PrivacyMethodHookProvider(22105): at android.app.Activity.onStart(Activity.java:1790)
E/PrivacyMethodHookProvider(22105): at io.flutter.embedding.android.FlutterActivity.onStart(FlutterActivity.java:589)
```

**Comment by RodrigoSMarques** [comment]
@shingohu 

I contacted the Branch team and were asked to open a support ticket with them reporting your case.

[https://help.branch.io/using-branch/page/submit-a-ticket](https://help.branch.io/using-branch/page/submit-a-ticket)

**Comment by shingohu** [comment]
> @shingohu
> 
> I contacted the Branch team and were asked to open a support ticket with them reporting your case.
> 
> https://help.branch.io/using-branch/page/submit-a-ticket

Thanks 

but Is it possible to provide an API for delay initialization

this is the api for branch sdk 
https://help.branch.io/developers-hub/docs/android-advanced-features#delay-branch-initialization

**Comment by RodrigoSMarques** [comment]
> > @shingohu
> > I contacted the Branch team and were asked to open a support ticket with them reporting your case.
> > https://help.branch.io/using-branch/page/submit-a-ticket
> 
> Thanks
> 
> but Is it possible to provide an API for delay initialization
> 
> this is the api for branch sdk https://help.branch.io/developers-hub/docs/android-advanced-features#delay-branch-initialization

I will evaluate. I have to do some tests

**Comment by RodrigoSMarques** [comment]
Hi @shingohu .
Still interested in this feature?

**Comment by RodrigoSMarques** [comment]
Functionality available in the new beta version: 

- [https://pub.dev/packages/flutter_branch_sdk/versions/7.0.0-beta.0](https://pub.dev/packages/flutter_branch_sdk/versions/7.0.0-beta.0)
- [https://pub.dev/packages/flutter_branch_sdk/versions/7.0.0-beta.0/changelog](https://pub.dev/packages/flutter_branch_sdk/versions/7.0.0-beta.0/changelog)

**Comment by ahkela21** [comment]
@shingohu may i know what is your workaround for this?
