### ISSUE TITLE
App Links do not open app on IOS, always takes to AppStore instead

### ISSUE THREAD

**Issue by amani27** [RodrigoSMarques/flutter_branch_sdk#175]
**Describe the bug**
Links generated do not open app even when app is installed on iOS.
Though this works nicely on Android

**To Reproduce**
1. Click on the link generated
2. Takes to browser
3. On clicking go to app takes to AppStore

**Expected behavior**
The link should open app and route to a specific screen.

**Screenshots**
<img width="282" alt="Screenshot 2022-09-24 at 12 10 36 PM" src="https://user-images.githubusercontent.com/41122543/192082927-66332537-4dd2-42a3-9443-f56830cd7250.png">

**Desktop (please complete the following information):**
 - Flutter: version: 2.10.2
 - Package version: 5.1.0
 - OS: iOS

**Smartphone (please complete the following information):**
 - Flutter: version: [e.g. 2.2.3]
 - Package version: [e.g. 3.3.0]

**Comment by RodrigoSMarques** [comment]
Check the instructions on the Branch troubleshooting page at this [link](https://help.branch.io/developers-hub/docs/ios-troubleshooting)

**Comment by amani27** [comment]
> Check the instructions on the Branch troubleshooting page at this [link](https://help.branch.io/developers-hub/docs/ios-troubleshooting)

I did follow the instructions, used the Use [AASA validator](https://branch.io/resources/aasa-validator/) and it did pass.
What else could be causing this issue?

**Comment by RodrigoSMarques** [comment]
I suggest you open a ticket to Branch support: 

https://help.branch.io/using-branch/page/submit-a-ticket

**Comment by amani27** [comment]
> Links generated do not open app even when app is installed on iOS.
> Though this works nicely on Android

Thanks, just opened one.

**Comment by tejHackerDEV** [comment]
@amani27 sorry for replying on closed issue. I have also the same issue as yours, can you tell me what you have done to fix it?
