### ISSUE TITLE
context.getPackageName() is null for Android platform

### ISSUE THREAD

**Issue by rob-gioia-branch** [RodrigoSMarques/flutter_branch_sdk#179]
**Describe the bug**
I integrated the Branch Flutter SDK into two apps, and ran into one issue, only occurring on Android. I am getting the following error when running the app on Android: 
`java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference`

**To Reproduce**
1. Create a new Flutter app
2. Integrate the Branch SDK
3. Observe the error on Android

**Expected behavior**
No error when the app launches

**Screenshots**
![Screen Shot 2022-09-27 at 3 21 45 PM (1)](https://user-images.githubusercontent.com/87081315/194905261-e304dd35-34ca-4698-9b00-11ced55dbb48.png)

**Smartphone (Please complete the following information. remove session if not platform):**
 - Flutter: version: 3.3.2
 - Package version: 6.1.0 (flutter_branch_sdk)
 - Device: Pixel 5 API 30 Emulator
 - OS: Android

**Comment by RodrigoSMarques** [comment]
This is usually related to the wrongly positioned tags in the `AndroidManifest.xml`

The `package` tag is not being recognized.

**Comment by rob-gioia-branch** [comment]
@RodrigoSMarques thank you for your response. I have the package tag in the <manifest> element up top: 
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.master_proserve_flutter_app">
```
Is there some additional configuration it is expecting? I tried starting a new Android project and followed the steps but am still getting the same issue when I run the app.

**Comment by RodrigoSMarques** [comment]
> @RodrigoSMarques thank you for your response. I have the package tag in the element up top:
> 
> ```
> <manifest xmlns:android="http://schemas.android.com/apk/res/android"
>     package="com.example.master_proserve_flutter_app">
> ```
> 
> Is there some additional configuration it is expecting? I tried starting a new Android project and followed the steps but am still getting the same issue when I run the app.

Send your complete `AndroidManifest.xml` to analysis.

This same problem has already occurred here #151

**Comment by rob-gioia-branch** [comment]
@RodrigoSMarques ok thanks, here is the full AndroidManifest.xml: 

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.master_proserve_flutter_app">
   <application
        android:label="master_proserve_flutter_app"
        android:name="${applicationName}"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTask"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>

            <!-- Branch URI Scheme -->
            <intent-filter>
                <!-- If utilizing $deeplink_path please explicitly declare your hosts, or utilize a wildcard(*) -->
                <data android:scheme="psmaster" android:host="open" />
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
            </intent-filter>

            <!-- Branch App Links -->
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="https" android:host="psmaster.app.link" />
                <!-- example-alternate domain is required for App Links when the Journeys/Web SDK and Deepviews are used inside your website.  -->
                <data android:scheme="https" android:host="psmaster-alternate.app.link" />
            </intent-filter>

            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="https" android:host="psmaster.test-app.link" />
                <!-- example-alternate domain is required for App Links when the Journeys/Web SDK and Deepviews are used inside your website.  -->
                <data android:scheme="https" android:host="psmaster-alternate.test-app.link" />
            </intent-filter>

        <!-- Branch init -->
        <meta-data android:name="io.branch.sdk.BranchKey" android:value="key_live_ccQ8piFdCMPVysh8TLmEhghmuCk162Rr" />
        <meta-data android:name="io.branch.sdk.BranchKey.test" android:value="key_test_hcGYfaAnBPHUutc7SRmrSgjdCrgZ30RL" />
        <meta-data android:name="io.branch.sdk.TestMode" android:value="false" />     <!-- Set to true to use Branch_Test_Key (useful when simulating installs and/or switching between debug and production flavors) -->

        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>
```

**Comment by RodrigoSMarques** [comment]
The lines below are inside the `activity` session and should be outside, at the end of the file before `</application>

See the sample application file [here](https://github.com/RodrigoSMarques/flutter_branch_sdk/blob/master/example/android/app/src/main/AndroidManifest.xml).

Make an adjustment and test again.


`

        <meta-data android:name="io.branch.sdk.BranchKey" android:value="key_live_ccQ8piFdCMPVysh8TLmEhghmuCk162Rr" />
        <meta-data android:name="io.branch.sdk.BranchKey.test" android:value="key_test_hcGYfaAnBPHUutc7SRmrSgjdCrgZ30RL" />
        <meta-data android:name="io.branch.sdk.TestMode" android:value="false" />     
`

**Comment by RodrigoSMarques** [comment]
Your package name is using the `com.example` domain.

This is a generic name and some services cannot recognize it.

I suggest putting another domain, a domain of your own.

**Comment by rob-gioia-branch** [comment]
> The lines below are inside the `activity` session and should be outside, at the end of the file before `
> 
> See the sample application file [here](https://github.com/RodrigoSMarques/flutter_branch_sdk/blob/master/example/android/app/src/main/AndroidManifest.xml).
> 
> Make an adjustment and test again.
> 
> ```java
> 
>         <meta-data android:name="io.branch.sdk.BranchKey" android:value="key_live_ccQ8piFdCMPVysh8TLmEhghmuCk162Rr" />
>         <meta-data android:name="io.branch.sdk.BranchKey.test" android:value="key_test_hcGYfaAnBPHUutc7SRmrSgjdCrgZ30RL" />
>         <meta-data android:name="io.branch.sdk.TestMode" android:value="false" />     
> ```

@RodrigoSMarques this fixed it, thanks!

**Comment by quetool** [comment]
Hey @rob-gioia-branch could you tell me what did you do exactly? Cause I can't fix it

**Comment by rob-gioia-branch** [comment]
> 

Yeah sure thing. If you look at where you put these lines:
```
<!-- Branch init -->
        <meta-data android:name="io.branch.sdk.BranchKey" android:value="key_live_ccQ8piFdCMPVysh8TLmEhghmuCk162Rr" />
        <meta-data android:name="io.branch.sdk.BranchKey.test" android:value="key_test_hcGYfaAnBPHUutc7SRmrSgjdCrgZ30RL" />
        <meta-data android:name="io.branch.sdk.TestMode" android:value="false" />     <!-- Set to true to use Branch_Test_Key (useful when simulating installs and/or switching between debug and production flavors) -->
```
You want to make sure that they aren't inside of the <activity>, just the <application>. For example:

The following is incorrect because the meta-data tags are placed before the closing activity tag </activity>
...
          <meta-data android:name="io.branch.sdk.TestMode" android:value="false" />  
     </activity>
</application>

The following is correct:
...
     </activity>
     <meta-data android:name="io.branch.sdk.TestMode" android:value="false" />  
</application>
