### ISSUE TITLE
User test-app.link instead of app.link

### ISSUE THREAD

**Issue by quetool** [RodrigoSMarques/flutter_branch_sdk#187]
Hello! How do I use my `xxxxxxxxxxx.test-app.link` for testing purposes? I have flavoured targets and I would want to use the test-app.link in some of them.

**Comment by RodrigoSMarques** [comment]
On iOS, you need to update the test key in `INFO.PLIST`

Example [here](https://github.com/RodrigoSMarques/flutter_branch_sdk/blob/708aaa27901a95b420e424fa40d63422cc6066bc/example/ios/Runner/Info.plist#L70)

On Android, you need to update AndroidManifest.xml.


```xml
<meta-data android:name="io.branch.sdk.TestMode" android:value="true" />
```

Example [here](https://github.com/RodrigoSMarques/flutter_branch_sdk/blob/708aaa27901a95b420e424fa40d63422cc6066bc/example/android/app/src/main/AndroidManifest.xml#L57)

In a next version it will be possible to change the configuration by commands

**Comment by quetool** [comment]
Hello Rodrigo! Thanks for your answer!

I have added the test key on my test flavours but links are still generated with `app.link`.

Based on the example Info.plist you linked I can see only one difference: on The example you are using `branch_app_domain` key while I'm using `branch_universal_link_domains`. Could that be related?

![Screenshot 2022-11-01 at 09 10 21](https://user-images.githubusercontent.com/14978705/199188548-e281ed90-53cc-43be-a65d-db431b350ace.png)

**Comment by RodrigoSMarques** [comment]
In your project, inside the `branch_key` section, you created a new `test` dictionary.

See the example project configuration below:

```xml
	<key>branch_key</key>
	<string>key_test_ipQTteg11ENANDeCzSXgqdgfuycWoXYH</string>
```
In the current version it is not possible to define whether you are using the `test` or `live` key.

Then you need to enter the key directly, outside the `test` session or `live`.

![Captura de Tela 2022-11-01 às 08 34 18](https://user-images.githubusercontent.com/17687286/199224066-5b7fa812-0332-4141-8890-e45081390a54.png)

in the next version this configuration will be possible, according to the native documents.

**Comment by quetool** [comment]
Ohhh shouldn't be a <dict>! Nice, I will try that, many thanks and great package, Rodrigo!

**Comment by quetool** [comment]
It worked great! Thanks!

**Comment by pawanDreemz** [comment]
@quetool 
Just to confirm,

For android
`<meta-data android:name="io.branch.sdk.TestMode" android:value="true" />`
This identifies the test environment

For ios is it?
The combination of bundleId and branch_key(test)

**Comment by devpawann** [comment]
@quetool 

Just to confirm,

For android
<meta-data android:name="io.branch.sdk.TestMode" android:value="true" />
This identifies the test environment

For ios is it?
The combination of bundleId and branch_key(test)
