### ISSUE TITLE
getTrackingAuthorizationStatus will open the iOS-dialog to requestTrackingAuthorization

### ISSUE THREAD

**Issue by maxiklinke** [RodrigoSMarques/flutter_branch_sdk#190]
**Describe the bug**
On an new app install, I want to get the trackingAuthorizationStatus using the function FlutterBranchSdk.getTrackingAuthorizationStatus.
This will trigger the iOS-Dialog where the user has to select if he allows on not allows app tracking.
In my opinion this should only be triggered, if I call the function requestTrackingAuthorization.

Is this intentional or a bug?

**To Reproduce**
1. Uninstall the app and then reinstall it again to reset the trackingAuthorizationStatus.
2. Call FlutterBranchSdk.getTrackingAuthorizationStatus without calling FlutterBranchSdk.requestTrackingAuthorization on a button click. This will open the iOS-Dialog.

**Smartphone (Please complete the following information. remove session if not platform):**
 - Flutter: version: 3.3.1
 - Package version: 6.2.1
 - Device: iPhone 13
 - OS: iOS 16.0

**Comment by RodrigoSMarques** [comment]
Hi @maxiklinke 

it's a bug. I made the correction. I'm preparing a new version that will be released in the next few days.

**Comment by RodrigoSMarques** [comment]
Fix completed - Version 6.3.0.
