### ISSUE TITLE
Not opening app from Instagram story in Android

### ISSUE THREAD

**Issue by inpingolearn** [RodrigoSMarques/flutter_branch_sdk#196]
I have configured Universal Link for android and ios, 
The link opens the app when shared via WhatsApp, Telegram or Slack, but it always redirect to playstore when opened from an Instagram story

**Comment by RodrigoSMarques** [comment]
Hi @inpingolearn 

According to the documentation available [here](https://help.branch.io/using-branch/docs/creating-a-deep-link#expected-link-behavior), the app should be opened by Instagram Stories.

I suggest that you open a support ticket for the Branch team to verify your project.

[https://help.branch.io/using-branch/page/submit-a-ticket](https://help.branch.io/using-branch/page/submit-a-ticket)

**Comment by RodrigoSMarques** [comment]
@inpingolearn 
I can't say. 

This Flutter plugin calls Branch's native SDK across platforms. 

I don't know what the SDK's native code does.

**Comment by RodrigoSMarques** [comment]
Can I close the issue?
