### ISSUE TITLE
Branch can call the initSession callback too soon

### ISSUE THREAD

**Issue by robsonfingo** [RodrigoSMarques/flutter_branch_sdk#2]
Branch can call the initSession callback before the flutter code has a chance to start listening to the stream. This will cause the flutter app to miss the deep link.

**Comment by RodrigoSMarques** [comment]
Have you tested? This issue was due to an error in some newer versions of Branch SDK.
I had an issue open and so it took me a long time to make the plugin available.
Send logcat filtering for text "FlutterBranchSDK

**Comment by RodrigoSMarques** [comment]
Fix in new release 0.1.0
