### ISSUE TITLE
BranchUniversalObject.imageUrl isn't shown in iOS Messages app

### ISSUE THREAD

**Issue by yaroslav-kahaniak** [RodrigoSMarques/flutter_branch_sdk#202]
**Describe the bug**
The branch link (generated with FlutterBranchSdk.getShortUrl) preview image isn't shown in the iOS Messages app

**To Reproduce**
1. Generate a link
```
    var properties = BranchLinkProperties().addControlParam('dummy', 'dummy');
    var link = await FlutterBranchSdk.getShortUrl(
      buo: BranchUniversalObject(
        canonicalIdentifier: 'test',
        imageUrl: 'https://sienaconstruction.com/wp-content/uploads/2017/05/test-image.jpg',
      ),
      linkProperties: properties,
    ).then((response) => response.result);
```
2. Send the link through the iOS Messages app
3. Despite the imageUrl being specified during the link generation, the preview image doesn't show up. Screenshot:
![telegram-cloud-document-2-5355040674343298824](https://user-images.githubusercontent.com/79097999/213800425-62219daa-643c-440b-9930-8a2131771ab5.jpg)

**Smartphone:**
 - Flutter: 3.3.10 • channel stable
 - flutter_branch_sdk: 5.1.1
 - OS: iOS16.2
 - Device: iPhone 8
 
**Additional context**
I have noticed that the preview image loads in the Messages app if it is added with the addCustomMetadata method, instead of being added through BranchUniversalObject.imageUrl (screenshot attached below):
```
    var properties = BranchLinkProperties().addControlParam('dummy', 'dummy');
    var contentMetaData = BranchContentMetaData()
      ..addCustomMetadata('og:image',
          'https://sienaconstruction.com/wp-content/uploads/2017/05/test-image.jpg');
    var link = await FlutterBranchSdk.getShortUrl(
      buo: BranchUniversalObject(
        canonicalIdentifier: 'test',
        contentMetadata: contentMetaData,
      ),
      linkProperties: properties,
    ).then((response) => response.result);
```
![IMG_3683](https://user-images.githubusercontent.com/79097999/213807403-6aac09d1-04dd-4fc4-bcdb-0b05eea79c3f.PNG)

At the same time, if I add the image URL through the addCustomMetadata the preview image isn't shown a preview image, and instead is shown as a logo in Telegram:
![telegram-cloud-document-2-5357292474156982522](https://user-images.githubusercontent.com/79097999/213808015-e6a40857-352b-4a18-a1f4-2b90f95236ff.jpg)

Is there a simple way to add a preview image, that would get shown both in social media apps (Facebook, Instagram, Telegram) and iOS Messages app?

**Comment by RodrigoSMarques** [comment]
I believe this is not a bug in the SDK, but the way Messenger and also other apps interpret the URL image.

Try specifying the **$og_image_width** and **$og_image_height** parameters in **addCustomMetadata**.

- [https://help.branch.io/using-branch/docs/deep-link-data-options](https://help.branch.io/using-branch/docs/deep-link-data-options)
- [https://help.branch.io/using-branch/docs/creating-a-deep-link#open-graph](https://help.branch.io/using-branch/docs/creating-a-deep-link#open-graph)
- [https://www.branch.io/resources/blog/how-to-configure-your-apps-sharing-for-ios-10s-imessage-update/](https://www.branch.io/resources/blog/how-to-configure-your-apps-sharing-for-ios-10s-imessage-update/)
- [https://stackoverflow.com/questions/38961422/branch-io-link-not-showing-image-thumb-in-whatsapp](https://stackoverflow.com/questions/38961422/branch-io-link-not-showing-image-thumb-in-whatsapp)


You can also open a ticket at Branch support as it might be a limitation of the native SDK and not the Flutter package: [https://help.branch.io/using-branch/page/submit-a-ticket](https://help.branch.io/using-branch/page/submit-a-ticket)

**Comment by jf-branch** [comment]
@RodrigoSMarques That's correct, with iOS 13, Apple introduce LPLinkMetadata (https://developer.apple.com/documentation/linkpresentation/lplinkmetadata) Essentially this new protocol handles the previews. 

We do have handling of that in the underlying iOS SDK: https://help.branch.io/developers-hub/docs/ios-advanced-features#share-with-lplinkmetadata

**Comment by yaroslav-kahaniak** [comment]
Sorry, but I don't understand why BranchUniversalObject.imageUrl doesn't set the link preview image in the iOS Messages app. I thought that the purpose of this parameter is to ease the developer's work so that he wouldn't have to read the documentation of all the apps he is sharing links to (or at least popular onces) to figure out how to set the link preview image.

Please, correct me, if I misunderstand the purpose of the BranchUniversalObject.imageUrl

**Comment by RodrigoSMarques** [comment]
> @RodrigoSMarques That's correct, with iOS 13, Apple introduce LPLinkMetadata (https://developer.apple.com/documentation/linkpresentation/lplinkmetadata) Essentially this new protocol handles the previews.
> 
> We do have handling of that in the underlying iOS SDK: https://help.branch.io/developers-hub/docs/ios-advanced-features#share-with-lplinkmetadata

Thanks @jf-branch 

In the SDK for Flutter it is:
[https://github.com/RodrigoSMarques/flutter_branch_sdk#show-share-sheet-with-lplinkmetadata](https://github.com/RodrigoSMarques/flutter_branch_sdk#show-share-sheet-with-lplinkmetadata)

**Comment by jf-branch** [comment]
And just to clarify, the LPLinkMetadata.icon controls what the icon image is on Messages app. 

> here a simple way to add a preview image, that would get shown both in social media apps (Facebook, Instagram, Telegram) and iOS Messages app?
@yaroslav-kahaniak Each messages app displayed content different, some foster open graph, others don't. 

In terms of why image_url is not mapping to og_image_url, i will look into this further.

**Comment by jf-branch** [comment]
okay so on our native iOS SDK, regardless if you set image_url or add content metadata with og_image_url, it populates the same field in the payload request. 

@yaroslav-kahaniak Could you enable branch logging and share the POST request body for api2.branch.io/v1/url for both routes you have taken?

**Comment by yaroslav-kahaniak** [comment]
A small note: I have actually used the **og_image** metatag, not the **$og_Image_url** (as I followed the information stated here: https://developer.apple.com/library/archive/technotes/tn2444/_index.html), so let's look why **image_url** doesn't get mapped to **og_image**

**Comment by jf-branch** [comment]
it's strange, in my testing i am seeing the exact opposite. 

Successful Image Previews: 
- set imageUrl via BUO 
- maps to `data.$og_image_url` 

As according to: https://help.branch.io/using-branch/docs/creating-a-deep-link#open-graph 

When we receive that field in the payload the link creating service injects that value and others as og metadata.

**Comment by yaroslav-kahaniak** [comment]
> A small note: I have actually used the **og_image** metadata, not the **$og_Image_url** (as I followed the information stated here: https://developer.apple.com/library/archive/technotes/tn2444/_index.html), so let's look why **image_url** doesn't get mapped to **og_image**

Could you check, if imageUrl via BUO gets mapped to og_image? (not the $og_Image_url)

**Comment by jf-branch** [comment]
I can confirm BUO.imageURL maps to $og_image_url. 

<img width="847" alt="Screen Shot 2023-01-20 at 6 23 30 PM" src="https://user-images.githubusercontent.com/61431395/213822434-ac5910ab-9872-4f8e-b5de-51721be62e38.png">

Returned link with working preview: 
https://psmaster.app.link/YTEFHSbQKwb

**Comment by jf-branch** [comment]
I can confirm BUO.imageUrl is mapped to $og_image_url
<img width="1216" alt="Screen Shot 2023-01-20 at 4 15 31 PM" src="https://user-images.githubusercontent.com/61431395/213822590-391a84b1-7df4-4012-bc30-e32ed4bdd2d6.png">

Returned link with proper preview: 
https://psmaster.app.link/bqZEF8lQKwb

**Comment by jf-branch** [comment]
I can confirm BUO.imageUrl maps to $og_image_url (which is the expected parameter based on our API) 
<img width="1177" alt="Screen Shot 2023-01-20 at 6 25 05 PM" src="https://user-images.githubusercontent.com/61431395/213822659-0aa854fa-8754-4738-9cd4-451343aa8eba.png">

Returned link with proper preview: 
https://psmaster.app.link/bqZEF8lQKwb

**Comment by yaroslav-kahaniak** [comment]
The issue wasn't caused by branch SDK so it may be closed now.
Our backend was setting the wrong Content-Type for the images, which URLs we were using as BranchUniversalObject.imageUrl

@RodrigoSMarques @jf-branch Thank you for dedicated time
