### ISSUE TITLE
Short links generated by the SDK inside the app are opens the app but not redirect to the specific screen of the app. ( Webview app )

### ISSUE THREAD

**Issue by abdulahath** [RodrigoSMarques/flutter_branch_sdk#203]
**Describe the bug**
Short links generated by the SDK inside the app are opens the app but not redirect to the specific screen of the app. ( Webview app )

**To Reproduce**

This question is regarding webview app using the package - "flutter_inappwebview: ^6.0.0-beta.22" .I am using this package to make my website into a flutter app. 
I have no android app published to playstore yet. I have done the initial integrations in the dashboard , AndroidManifest.xml and Used the code example code from "https://github.com/BranchMetrics/flutter_branch_sdk/blob/master/example/lib/main.dart" .
I believe this is not a bug, but needed guiding for achieve the functionality for redirected to a specific page inside the app.

Please refer the gists .
1. main.dart - https://gist.github.com/abdulahath/fa9b2f4a35d91d48b203d017aada01e7
2. myWebViewWidget.dart - https://gist.github.com/abdulahath/8830563b6cd8c507f695569671cc81a6
3. AndroidManifest.xml - https://gist.github.com/abdulahath/5261dbf68eac91b03f0694260c8cadd2
4. size_configs.dart - https://gist.github.com/abdulahath/9419006a5e5abe6a9cbeee431bc9f5b0
5. no_internet_screen.dart - https://gist.github.com/abdulahath/d5723dbfbf88c425285c143fd32d529d
6. branch_sdk_custom_button.dart - https://gist.github.com/abdulahath/000d43a35608562621daefaee26d7154

![Screenshot_20230205-100040](https://user-images.githubusercontent.com/87147670/216802341-c7bd501d-ddcd-4913-ba0b-940f3d145091.jpg)

**Expected behavior**
When the generated short link is clicked, app should open and redirect to the particular screen ( ie. if the app's initial page is www.example.com and particular screen page is www.example.com/sub-page ).  

**Smartphone :**
 - Flutter: version: [3.3.10]
 - flutter_branch_sdk: ^6.4.0
 - OS: Android 11 , Android 6
 - Device: Oneplus 6 , HTC one A9S
 

**Additional context**
I have sent an email to support@branch.io , but not received the reply yet. Please help.
Refer the screenshots

![Screenshot 3](https://user-images.githubusercontent.com/87147670/216802416-7616ccc5-8adf-4052-b826-9ed6cfa49c78.jpg)

**Different Approach**
Additionally , I have created a quick link in the branch dashboard and send it through Gmail to test it. When i clicked the link on my android phone , it still open the app but not redirected to the specific page (website).

![quicklink_linkdata](https://user-images.githubusercontent.com/87147670/216802822-13d56091-6766-4d04-bb28-e7e3cdf52988.jpg)

![quicklink _ Redirects](https://user-images.githubusercontent.com/87147670/216802825-76577107-1183-4ec4-b0f7-cfe0418591cf.jpg)

**Comment by RodrigoSMarques** [comment]
Redirection to a page is not automatic.

When you create the link through the Dashboard, in the "Link Data" section, you add key/value pairs that you will have to retrieve when opening the application to give the necessary treatment.

In your case, I see you created the keys, $deeplink_path, $og_type, $canonical_url in your link.

So when opening the application, you must use the FlutterBranchSdk.initSession().listen or FlutterBranchSdk.getLatestReferringParams() methods to retrieve the key/value values that you added to your link and give the necessary treatment, which in your case is the redirect to a page on your website.

**Comment by abdulahath** [comment]
Thanks for the response Rodrigo. Apologies for the delayed reply.

I found a way to redirect to the particular page and it's working fine. When I clicked the "branch_sdk" created link in another android phone , if the user is not installed the app, then it's redirecting to the google playstore (used a dummy link). If the user already have the app installed , it's redirecting to the particular sub webpage. I used the FlutterBranchSdk.initSession().listen method to achieve this .

However Today I'm going to publish my app to Google play store  and will test the below functionality after the app is listed on the playstore. 
Functionality expected ---> If the user is not installed the app, then it's redirect to the my app's google playstore page. After installation , user open the app , it should redirect him to the particular sub webpage. 
If this functionality not achieved, then only i'll try to implement it using the "FlutterBranchSdk.getLatestReferringParams()"method to achieve it.







**Bug Report**
And also, I found a bug when testing my app.
1. on android 13 (emulator) , FlutterBranchSdk.showShareSheet() showing the share sheet with weirdly small app icons of installed apps.
![1  showing a share sheet on Android 13](https://user-images.githubusercontent.com/87147670/218248035-6fd2ecfa-e56a-4715-9d51-a1f69b0b0d35.jpg)



2. upto android 12 it's fine as per below screenshot
![3  showing a share sheet on Android 12](https://user-images.githubusercontent.com/87147670/218248052-74a6fa54-7633-4428-978b-9a925ef643c3.jpg)






**Feature Request**
flutter_branch_sdk's default share sheet is less attractive as seen on above screenshots. Is there a way to open a share sheet looks close to the native one using "share_plus" or any packages ? refer the below screenshot taken inside the chome browser. 
![2  Native share sheet on Android 13](https://user-images.githubusercontent.com/87147670/218248132-e46cf1b3-5308-4b55-b390-328cdeeeff80.jpg)



Last of all, i'm very grateful about the branch.io teams features and customer support even for the free users.
Thanks again Rodrigo.

**Comment by RodrigoSMarques** [comment]
Hi @abdulahath 

This package is a plugin that bridges the gap between Flutter and the Branch SDK.

I have no control over how Branch functionality behaves in applications.

About the two points you reported above, I ask you to open a ticket with Branch support:

[https://help.branch.io/using-branch/page/submit-a-ticket](https://help.branch.io/using-branch/page/submit-a-ticket)

They fixing the bug of the behavior of the icons in Android and improving the display of the icons, this will be available in this package.

**Comment by abdulahath** [comment]
Thanks for the reply @RodrigoSMarques 

I will submit the ticket.
