### ISSUE TITLE
Please make a flutter specific video tutorial / detailed blog post for ios implementation

### ISSUE THREAD

**Issue by abdulahath** [RodrigoSMarques/flutter_branch_sdk#205]
Branch_sdk ios implementation needs expertise than the android implementation. I have not found any ios implementation videos/blogs specific to flutter. 

Please make a flutter specific video tutorial / detailed blog post for ios implementation.

Thanks in advance.

**Comment by RodrigoSMarques** [comment]
Hi. @abdulahath 

Where did you find difficulty?

You can follow the Branch [tutorials](https://university.branch.io/training/b5023562-810b-11eb-9848-06c0361096e5/overview), the session **IOS SDk Setup**
