### ISSUE TITLE
No support for test mode on iOS

### ISSUE THREAD

**Issue by kvenn** [RodrigoSMarques/flutter_branch_sdk#208]
I see the comment that says there is no support for test mode. Or at least to get test mode working, I'd need to support flavors.  
![Screenshot 2023-02-24 at 9 34 42 AM](https://user-images.githubusercontent.com/1782467/221204766-57c24ee7-7237-4fa3-bbde-f80224c10dfe.png)

In the [iOS docs](https://help.branch.io/developers-hub/docs/ios-testing#use-test-key) there is `Branch.setUseTestBranchKey(true)` and [Android](https://help.branch.io/developers-hub/docs/android-testing#use-test-key) there is both the option to set in the manifest and programatically via `Branch.enableTestMode()`.

**Is there any plan to add programmatic support to flutter?**

Possibly via `FlutterBranchSdk.setUseTestBranchKey(true);`

Related issue: https://github.com/RodrigoSMarques/flutter_branch_sdk/issues/187

**Comment by RodrigoSMarques** [comment]
Hi @kvenn 

This functionality will be available in a new version that is under development.  the version is in the final testing phase and should be released with beta, as it brings breaking change.  I'll leave this issue open to let you know when it's available.

**Comment by kvenn** [comment]
Exciting! Thank you Rodrigo 🔥

**Comment by DDavidPrime** [comment]
@RodrigoSMarques Are there any updates on this issue? The last comment is over 4 months old.

**Comment by RodrigoSMarques** [comment]
> @RodrigoSMarques Are there any updates on this issue? The last comment is over 4 months old.

Hey @DDavidPrime , I took a break because of other personal priorities.

It's about 90% ready. I need to finish some tests and update the documentation.

I will try to release this next week.

If you can help me with tests, it would help a lot.

**Comment by feriyalsusanto** [comment]
@RodrigoSMarques Hi, are there any updates on this issue? Thanks!

**Comment by RodrigoSMarques** [comment]
Hi @feriyalsusanto.

The code is not 100% ready.
I have to include some validations to prevent methods from being called before initialization and update the documentation

For this reason, I have not released the update yet.

Using the example application, the code is 100% functional.

If you want to test it in your project

Update the `pubspec.yaml`:

```dart
#flutter_branch_sdk:
flutter_branch_sdk:
    git:
      url: https://github.com/RodrigoSMarques/flutter_branch_sdk.git
      ref: version7
```

Update `main` for call `init` with parameters:
```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await FlutterBranchSdk.init(
    useTestKey: true,
    enableLogging: true,
  );
  runApp(const MyApp());
}
```

**Comment by RodrigoSMarques** [comment]
Hi @feriyalsusanto .
Still interested in this feature?

**Comment by RodrigoSMarques** [comment]
Functionality available in the new beta version: 

- [https://pub.dev/packages/flutter_branch_sdk/versions/7.0.0-beta.0](https://pub.dev/packages/flutter_branch_sdk/versions/7.0.0-beta.0)
- [https://pub.dev/packages/flutter_branch_sdk/versions/7.0.0-beta.0/changelog](https://pub.dev/packages/flutter_branch_sdk/versions/7.0.0-beta.0/changelog)
