### ISSUE TITLE
No callback from initSession.listen in Android

### ISSUE THREAD

**Issue by petemillermultimedia** [RodrigoSMarques/flutter_branch_sdk#214]
**Describe the bug**
When launching the app on Android with a deep link the callback for initSession.listen is never called. The app is opened as expected, but no link data can be captured. Code works properly in iOS.

**To Reproduce**
Register a listener in initState, per instructions:

@override
  initState() {
    super.initState();

    // Branch.io
    StreamSubscription<Map> branchStreamSubscription = FlutterBranchSdk.initSession().listen((data) {
      DebugPrint.dprint("Branch.io callback");
      if (data.containsKey('+clicked_branch_link') && data['+clicked_branch_link'] == true) {
        if (data.containsKey('metadata')) {
          var metadata = data['metadata'];
          if (metadata.containsKey('registrationcode')) {
            DebugPrint.dprint("Branch link with reg code: ${metadata['registrationcode']}");
          }
        }
      }
    });

Run app; app is opened by clicking a link, but callback is never invoked.

**Expected behavior**
Callback is invoked.

**Smartphone (Please complete the following information. remove session if not platform):**
 - Flutter version: 3.7.5
 - Package version: 5.5.0
 - OS: Android 13
 - Device: Pixel5

**Comment by RodrigoSMarques** [comment]
please paste the result of call to **validateSDKIntegration** function.

**intent-filter** configured correctly?

How is the **launchMode** tag configured inside the **activity** section?

**Comment by petemillermultimedia** [comment]
Branch key is missing from Android manifest. This is a migration from Xamarin, where the key is stored as a string resource rather than in the manifest.
