### ISSUE TITLE
IOS not open the app only the store listing

### ISSUE THREAD

**Issue by juzejunior** [RodrigoSMarques/flutter_branch_sdk#224]
**Describe the bug**
Hello guys! I did the setup following the IOS guide and called validateSDKIntegration which gives success. But I'm getting some strange behaviors. Always that i try to access through something like: https://my_app.test-app.link/ or https://my_app.app.link/
it redirects me to the app store, even with the app installed and running. 

When I access  through something like: https://my_app.test-app.link/?bnc_validate=true, it opens the installed app but right after redirects the user to the app store listing again. This gives me the following logs:

```2
[connection] nw_read_request_report [C29] Receive failed with error "Socket is not connected"
2
[connection] nw_read_request_report [C31] Receive failed with error "Socket is not connected"
2
[connection] nw_read_request_report [C21] Receive failed with error "Socket is not connected"
2
[connection] nw_read_request_report [C25] Receive failed with error "Socket is not connected"
2
[connection] nw_read_request_report [C27] Receive failed with error "Socket is not connected"
[connection] nw_read_request_report [C1] Receive failed with error "Software caused connection abort"
[quic] quic_send_frames_for_key_state_block_invoke [C23.1.1:2] [-f48e7d6174c30a7f] unable to request outbound data
[quic] quic_send_frames_for_key_state_block_invoke [C29.1.1:2] [-d31cfff1190a8530] unable to request outbound data
[quic] quic_send_frames_for_key_state_block_invoke [C31.1.1:2] [-dea05eac07705b62] unable to request outbound data
[quic] quic_send_frames_for_key_state_block_invoke [C21.1.1:2] [-f4711077f18707c7] unable to request outbound data
[quic] quic_send_frames_for_key_state_block_invoke [C25.1.1:2] [-d1ec10616e7a3ebe] unable to request outbound data
[quic] quic_send_frames_for_key_state_block_invoke [C27.1.1:2] [-fa796ee2b4519be2] unable to request outbound data
10.7.0 - [FirebaseAnalytics][I-ACS023001] Deep Link does not contain valid required params. URL params: {
    "_branch_referrer" = "H4sIAAAAAAAAA8soKSkottLXT8vMK8tMStVNKtIrSS0u0U0sKNDLyczL1rdPykuOL0vMyUxJLEm1LSkqTQUAMYN5kDMAAAA=";
    "link_click_id" = 1194442234429970282;
}

Branch InitSession params: Optional(["+match_guaranteed": 1, "+click_timestamp": 1686018571, "~referring_link": https://finvibe-br.test-app.link/?bnc_validate=true, "+clicked_branch_link": 1, "+is_first_session": 0, "bnc_validate": true, "~id": 0, "~creation_source": 6])
10.7.0 - [FirebaseAnalytics][I-ACS800014] Cannot get flag for unregistered flag. SDK name, flag name: app_measurement, session_stitching_token_feature_enabled
Branch InitSession params: Optional(["+clicked_branch_link": 0, "+is_first_session": 0])
10.7.0 - [FirebaseAnalytics][I-ACS800014] Cannot get flag for unregistered flag. SDK name, flag name: app_measurement, session_stitching_token_feature_enabled
```

**To Reproduce**
1. Setup flutter branch IOS
2. Open your app link test or live: https://my_app.test-app.link
3. See error, it will open the app store listing

**Expected behavior**
If the app is installed it should open the app.

**Smartphone (Please complete the following information. remove session if not platform):**
 - Flutter: version: 3.10.1
 - Package version: 6.6.0
 - OS: IOS15.7.5
 - Device: Iphone 7

 
 - **Additional context**

I am not setting setUseTestBranchKey through AppDelegate, my app has multiple flavors so I just switch branch_key in info.plist file.

**Comment by RodrigoSMarques** [comment]
Hi @juzejunior 

Performing tests on IOS is more complex.

Have you checked the guidelines on this page:

[https://help.branch.io/developers-hub/docs/ios-testing](https://help.branch.io/developers-hub/docs/ios-testing)
[https://help.branch.io/using-branch/docs/add-test-devices](https://help.branch.io/using-branch/docs/add-test-devices)

**Comment by juzejunior** [comment]
Thanks man, I will check it out.

**Comment by juzejunior** [comment]
I try with both links tutorial, but still the same behavior.

**Comment by RodrigoSMarques** [comment]
checking your log, I found the message below.
 what are you using in your project?

 Firebase looks like it's trying to interpret Branch's deeplink. this could be the reason for the error.

```
10.7.0 - [FirebaseAnalytics][I-ACS023001] Deep Link does not contain valid required params. URL params: {
    "_branch_referrer" = "H4sIAAAAAAAAA8soKSkottLXT8vMK8tMStVNKtIrSS0u0U0sKNDLyczL1rdPykuOL0vMyUxJLEm1LSkqTQUAMYN5kDMAAAA=";
    "link_click_id" = 1194442234429970282;
}
```

**Comment by RodrigoSMarques** [comment]
Open a support ticket in the branch at the link below. This store redirect issue has nothing to do with the Flutter plugin.

They are able to better analyze the origin of the problem.

[https://help.branch.io/using-branch/page/submit-a-ticket](https://help.branch.io/using-branch/page/submit-a-ticket)

**Comment by juzejunior** [comment]
Thanks, I'll do that.

**Comment by juzejunior** [comment]
Fixed by adding   "applinks:" prefix with the URL at the  associated domains under signing and capabilities, I was missing that. @RodrigoSMarques thanks for the support.
