### ISSUE TITLE
Branch has been deprecated in favor of BranchSDK

### ISSUE THREAD

**Issue by Andreas409** [RodrigoSMarques/flutter_branch_sdk#226]
**Describe the bug**
No matter how we try upgrade our version of branch, a pod install shows this warning: `[!] Branch has been deprecated in favor of BranchSDK`

I tested this on a brand new flutter project and the same warning is shown.

**To Reproduce**
1. Create a new flutter project
2. `flutter pub add flutter_branch_sdk`
3. `cd ios`
4. `pod install`

**Expected behavior**
Is it intentional that the sdk depends on a deprecated version of the ios sdk?

**Screenshots**
![Screenshot 2023-06-14 at 15 18 12](https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/25475532/210bad53-f7b5-4956-8bee-3c0c5e87b837)

**Smartphone (Please complete the following information. remove session if not platform):**
 - Flutter: version: 3.10.4
 - Package version: 6.4.0 -> 6.6.0

**Comment by RodrigoSMarques** [comment]
Add the plugin to your project and set a version 6.6.0 in `pubspec.yaml`
In version 6.6 of the plugin, the Branch dependency was changed to BranchSDK.
You can check it [here](https://github.com/RodrigoSMarques/flutter_branch_sdk/blob/78c0868d042c76b485fc41e95b04e0a2cab3d183/ios/flutter_branch_sdk.podspec#L18)

**Comment by RodrigoSMarques** [comment]
I performed the same procedure and installed the correct version here. No errors

<img width="1710" alt="Captura de Tela 2023-06-14 às 23 45 05" src="https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/17687286/150fc29e-0ba3-4cee-8b4a-659c91ed5b08">

**Comment by Andreas409** [comment]
Thank I see. I think `flutter pub add flutter_branch_sdk` inserts 6.4.0. Confirmed on my new project 👍  Will tackle the dependency issues in our main project again and check 👌

**Comment by Andreas409** [comment]
Managed to get everything working after upgrading our flutter version and as suggested above.
