### ISSUE TITLE
Can't retrive data after install

### ISSUE THREAD

**Issue by Greismorr** [RodrigoSMarques/flutter_branch_sdk#228]
I've configured the SDK and it works like a charm when the app is closed, open or minimized. I've created a Quick Link with a parameter setted into the URL. The problem is retrieving the referral url when the user install the app.  I guess i've done like the documentation shows and tried to get the data immediately after install using the code below:

   
```
 Future<void> init() async {
    try {
           Map<dynamic, dynamic> params = await FlutterBranchSdk.getLatestReferringParams();
          
           print(params);
    } catch (error) {
      print(
        error.toString(),
      );
    }
  }

```
 
 
 But the output is always the same: `BRANCH: {+clicked_branch_link: false, +is_first_session: false}`.  The referral link is not retrieved. Using other methods like getLastAttributedTouchData or getFirstReferringParams didn't help. Any ideas?

**Comment by RodrigoSMarques** [comment]
This message is informing you that the link you opened in your application is not a Branch deeplink.
Where did you create Quick Link? Through the dashboard?
Have you correctly configured all the domains that will be used by your application?

**Comment by Greismorr** [comment]
Yes, i've created It using the dashboard and made the Full setup with redirect to the stores. A link was generated with the scheme app.link.com and i put this domain It in my app Manifest.

When the app is installed, everything Works Fine. But when not installed the deep link ends with the redirect to the store, after the install the app opens and the output is:

`BRANCH: {+clicked_branch_link: false, +is_first_session: false}`

The referral link is not Retrieved.

**Comment by RodrigoSMarques** [comment]
which platform? iOS or Android?

**Comment by Greismorr** [comment]
Android. I didn't try on iOS yet

**Comment by RodrigoSMarques** [comment]
@Greismorr 
Como vi que você é brasileiro, vou escrever em pt-br para facilitar.

Se você quer recuperar o link após a instalação o comando correto é:

```dart
 Map<dynamic, dynamic> params = await FlutterBranchSdk.getFirstReferringParams();
```

Você pode obter a instrução [aqui]( [Map<dynamic, dynamic> params = await FlutterBranchSdk.getFirstReferringParams();](https://github.com/RodrigoSMarques/flutter_branch_sdk#retrieve-install-install-only-parameters)

O comando ```getLatestReferringParams``` funciona apenas se for a primeira execução do aplicativo.

Não entendi essa parte: _I've created a Quick Link with a parameter setted into the URL. The problem is retrieving the referral url when the user install the app._

Pode me dar um exemplo do link que você criou?

O que você adicionou no "Link Data"?

**Comment by Greismorr** [comment]
Opa, olá camarada!

O comando que você me deu ainda não é capaz de listar o link, retorna um map vazio. O que eu quis dizer sobre o Quick Link é que eu criei um pelo dashboard onde o único dado que eu preciso é passado diretamente pela URL:

`application.app.link/first-access/58348`

O dado que eu precisava recuperar após a instalação é a URL para que eu pudesse pegar o parâmetro dinâmico depois da última barra. No meu caso de uso, esse link deveria ser acessado por N usuários onde a única diferença seria esse parâmetro na URL. Pelo que entendi, associar esse dado com o LinkData resultaria em ter que criar um link diferente pela API do Branch.io toda vez que eu quisesse passar o link para um usuário.

Eu consegui obter o que queria implementando o serviço de redirect e de geração de URL manualmente em um website e salvando o endereço no clipboard do dispositivo quando houvesse um redirecionamento para alguma loja de aplicativo. Apesar de ser só um 'workaround', achei menos custoso do que criar um link para cada usuário via API do Branch.io.

**Comment by RodrigoSMarques** [comment]
Você criar uma URL dessa forma: ```application.app.link/first-access/58348``` explica porque o retorno da função ```FlutterBranchSdk.getLatestReferringParams``` sempre retorna: ```+clicked_branch_link: false``` e sem o map.

Isso não é uma URL válida para Branch. 
Até onde sei, não é possível passar parâmetros para a URL.
Se precisa passar parâmetros, você precisa adicionar através de ```link data```.  

Quando você adiciona valores eles são retornados no map da função ```FlutterBranchSdk.getLatestReferringParams```

**Comment by Greismorr** [comment]
A solução customizada que tentamos implementar aqui na empresa acabou não se mostrando tão eficaz (especialmente no iOS). Então acabei tentando dar outra chance ao Branch.io e foi a melhor decisão que eu poderia ter tomado. Não só resolveu todas as questões sem problemas como também configurou app links automaticamente.

A questão toda é que eu estava criando os links pelo dashboard, onde tem a opção de quick links. Depois que eu inseri os dados no link, a lógica passou a funcionar. Mas como eu precisava de dados customizados para cada usuário, bastou integrar minha API com a API do Branch e criar os links programaticamente. A partir daí, todos os cenários passaram a funcionar sem problemas, inclusive recuperando o link após a instalação tanto no Android quanto no iOS (e mesmo no Testflight).

No mais, parabéns pelo package!!!
