### ISSUE TITLE
pub get failed (1; So, because empty_project_flutter_no_web depends on flutter_branch_sdk ^6.6.0 which depends on js ^0.6.5, version solving failed.)

### ISSUE THREAD

**Issue by rob-gioia-branch** [RodrigoSMarques/flutter_branch_sdk#229]
Hey @RodrigoSMarques, Rob from Branch here with a question about the latest version of this SDK. 

**Describe the bug**
Upgrading to the latest version of the Branch Flutter SDK is failing with the following error:
```
Running "flutter pub get" in empty_project_flutter_no_web...     
Because flutter_branch_sdk >=3.0.0 depends on flutter_web_plugins from sdk which depends on js 0.6.4, flutter_branch_sdk >=3.0.0 requires js 0.6.4.
So, because empty_project_flutter_no_web depends on flutter_branch_sdk ^6.6.0 which depends on js ^0.6.5, version solving failed.
pub get failed (1; So, because empty_project_flutter_no_web depends on flutter_branch_sdk ^6.6.0 which depends on js ^0.6.5, version solving failed.)
```
I've tried doing this in:

- An existing project (project code + Branch SDK)
- An empty project (just Branch SDK)
- An empty project not for web (just Android + iOS, no web dependencies)
...but I still see this error for each one. 

**To Reproduce**
1. Create an empty Flutter project
2. Run `flutter pub add flutter_branch_sdk`
3. Notice that version 6.4 is the version added and not 6.6

**Expected behavior**
- Expecting the latest version, 6.6 to be added to the pubspec.yaml file upon running the command

**Screenshots**

![Screenshot 2023-06-15 at 10 33 16 AM](https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/87081315/3a4bccb7-c8b0-4070-9ade-f68b73dced56)

![Screenshot 2023-06-15 at 10 35 33 AM](https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/87081315/37174826-9365-4717-9841-50297d6da5f3)

Thank you for your help on this!

**Comment by RodrigoSMarques** [comment]
Hi @rob-gioia-branch 

You are not using a stable version of Flutter. You are using a version of the DEV channel.

Is there any reason to use this version? I suggest using the beta channel.

Regarding the error, testing in the latest stable version which is **3.10.5**, this error does not happen.

<img width="695" alt="Captura de Tela 2023-06-21 às 02 05 21" src="https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/17687286/16efcda2-a578-49b8-9372-7dfee754b50d">

The flutter version you are using ```is``` requiring a newer version of the JS package.
As the ```flutter_branch_sdk```  in version ```6.6.0``` uses an older version of the JS package, the error occurs.


1) Switch your flutter version to the **stable channel,** until I release a newer version of the package, to use the newer version of the JS package

2) Include the **dependency_overrides** statement in **pubspec.yaml** to force the use of the newest version of the **JS** package:

```dart
...
  flutter_branch_sdk: ^6.6.0

dependency_overrides:
  js: ^0.6.7
...
```

**Comment by rob-gioia-branch** [comment]
Hi @RodrigoSMarques those steps worked in successfully fixing the issue. Thank you!
