### ISSUE TITLE
iOS throwing NSCocoaErrorDomain error

### ISSUE THREAD

**Issue by karthik-reddy-8** [RodrigoSMarques/flutter_branch_sdk#230]
We have integrated this package and did necessary updates from platform side. Android is working fine but in iOS it is throwing below error in console.

`2023-07-25 23:37:05.990278+0530 Runner[57174:307332] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}`
`2023-07-25 23:37:05.990656+0530 Runner[57174:307283] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}`
`2023-07-25 23:37:05.991257+0530 Runner[57174:307283] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}`
`2023-07-25 23:37:05.991330+0530 Runner[57174:307298] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}`
`2023-07-25 23:37:05.991673+0530 Runner[57174:307283] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}`
`2023-07-25 23:37:05.991731+0530 Runner[57174:307298] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}`
`2023-07-25 23:37:05.997599+0530 Runner[57174:307298] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}`
`2023-07-25 23:37:06.006775+0530 Runner[57174:307298] [Client] Updating selectors after delegate addition failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}`

**Note:** We have firebase push notifications, analytics and crashlytics enabled and integrated to the same project.

**Comment by RodrigoSMarques** [comment]
A quick Google search shows that this message appears in several scenarios and appears to have nothing to do with the Branch SDK.

If it's something in the native SDK for iOS, they'll be able to guide you.

I suggest you open a support ticket for Branch at the link: [https://help.branch.io/using-branch/page/submit-a-ticket](https://help.branch.io/using-branch/page/submit-a-ticket)

**Comment by RodrigoSMarques** [comment]
[https://stackoverflow.com/questions/52455652/xcode-10-seems-to-break-com-apple-commcenter-coretelephony-xpc](https://stackoverflow.com/questions/52455652/xcode-10-seems-to-break-com-apple-commcenter-coretelephony-xpc)

**Comment by karthik-reddy-8** [comment]
Hello @RodrigoSMarques, i tried adding the CoreTelephony.framework. I landed on to the below error.

`Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
[unspecified] container_create_or_lookup_app_group_path_by_app_group_identifier: client is not entitled
[unspecified] container_create_or_lookup_app_group_path_by_app_group_identifier: client is not entitled
[unspecified] container_create_or_lookup_app_group_path_by_app_group_identifier: client is not entitled
2023-07-26 16:20:27.102 Runner[8888/0x16b927000] [lvl=3] -[MLKITx_GIPPseudonymousIDStore initializeStorage] Shared App Groups unavailable
[unspecified] container_create_or_lookup_app_group_path_by_app_group_identifier: client is not entitled
2023-07-26 16:20:27.557 Runner[8888/0x16c9c7000] [lvl=3] -[MLKITx_GIPPseudonymousIDStore initializeStorage] Shared App Groups unavailable
[unspecified] container_create_or_lookup_app_group_path_by_app_group_identifier: client is not entitled
2023-07-26 16:20:27.580 Runner[8888/0x16b927000] [lvl=3] -[MLKITx_GIPPseudonymousIDStore initializeStorage] Shared App Groups unavailable
[unspecified] container_create_or_lookup_app_group_path_by_app_group_identifier: client is not entitled
2023-07-26 16:20:27.895 Runner[8888/0x16b783000] [lvl=3] -[MLKITx_GIPPseudonymousIDStore initializeStorage] Shared App Groups unavailable
SKAdNetwork: Error while updating conversion value: Error Domain=SKANErrorDomain Code=10 "(null)"
[Attribution] updatePostbackConversionValue returned error: The operation couldn’t be completed. (SKANErrorDomain error 10.).
[Client] Updating selectors after delegate addition failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service with pid 89 named com.apple.commcenter.coretelephony.xpc was invalidated from this process." UserInfo={NSDebugDescription=The connection to service with pid 89 named com.apple.commcenter.coretelephony.xpc was invalidated from this process.}`

Any suggestion here please.

We did raised the ticket in help.branch.io

**Comment by karthik-reddy-8** [comment]
Solved by updating the AppDelegate.swift file application method

override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    FirebaseApp.configure()
    GeneratedPluginRegistrant.register(with: self)
     FlutterLocalNotificationsPlugin.setPluginRegistrantCallback { (registry) in
      GeneratedPluginRegistrant.register(with: registry)
      }
      if #available(iOS 10.0, *) {
      UNUserNotificationCenter.current().delegate = self as UNUserNotificationCenterDelegate
      }
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
