### ISSUE TITLE
SkAdNetwork question

### ISSUE THREAD

**Issue by ahmet-fennel** [RodrigoSMarques/flutter_branch_sdk#232]
So we are trying to use the SkAdNetwork to track attributions, in the branch documentation [here](https://help.branch.io/using-branch/docs/enable-skadnetwork-natively#7-test-skan-integration), it states that [Apple's StoreKit Framework](https://developer.apple.com/documentation/storekit) is a required step to use the SkAdNetwork

But this is not mentioned anywhere on this plugin, 
1. Is that completely accurate and if so does plugin automatically add the framework ? 
2. If not should we update the readme to indicate this step or a link to the readme about the SkAdNetwork

**Comment by RodrigoSMarques** [comment]
HI. I reviewed the links sent.

There is no mention of this in the plugin, as the implementation to use SkAdNetwork must be done in the native project.

I checked Branch plugins for other technologies and there are no instructions for that either.

If you want to use it in your project, you should open iOS project and add Apple's StoreKit Framework in it.

**Comment by ahmet-fennel** [comment]
For instance the Adjust plugin https://pub.dev/packages/adjust_sdk mentions "StoreKit.framework" in the readme which is very useful. 

Adding a section about the configuration (which i think only requires adding these frameworks) could be really helpful

**Comment by spideythewebhead** [comment]
Hi, I have a similar question as it seems that the SDK (Branch) is not recording conversions / events with SAN networks. 
For example FB has almost 0 events recorded for iOS (both pre 14 and 14+). Also it doesn't seem to map all the events with Google Ads.
Is anyone else facing the same issue?

**Comment by RodrigoSMarques** [comment]
> Hi, I have a similar question as it seems that the SDK (Branch) is not recording conversions / events with SAN networks.
> For example FB has almost 0 events recorded for iOS (both pre 14 and 14+). Also it doesn't seem to map all the events with Google Ads.
> Is anyone else facing the same issue?

Hi @spideythewebhead 

This package calls Branch Native SDK functions on each platform.

The problem reported is not in the Flutter package, but in the Native SDK.

Please open an issue in the platform repository:

- iOS: [https://github.com/BranchMetrics/ios-branch-deep-linking-attribution](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution)
- Android: [https://github.com/BranchMetrics/android-branch-deep-linking-attribution](https://github.com/BranchMetrics/android-branch-deep-linking-attribution)
