### ISSUE TITLE
Pass long URL when try creating Short URL in Offline

### ISSUE THREAD

**Issue by vishnunew** [RodrigoSMarques/flutter_branch_sdk#237]
**Describe the bug**
Currently Long URL is not passed when creating short URL in offline. Branch.Io does support that.  As per documentation it returns the Long URL if it fails to generate short URL. I have already checked that by debugging on Android it does return long URL in offline or failed to create URL.

**To Reproduce**
1. Create short URL in Offline
2. Check it returns null error

**Expected behavior**
It should pass the long URL if the URL is not null

**Screenshots**

**Smartphone (Please complete the following information. remove session if not platform):**
 - Flutter: version: 3.10.5
 - Package version: 6.6.0
 - OS: Both iOS and Android
 - Device: All device

 
 - **Additional context**

https://help.branch.io/developers-hub/docs/ios-full-reference#shortened-links
<img width="845" alt="Screenshot 2023-08-29 at 10 46 01 AM" src="https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/55532778/12d7be97-f307-4cd8-805d-80dc4bc1ac6e">

**Comment by RodrigoSMarques** [comment]
This package calls Branch Native SDK functions on each platform.

The problem reported is not in the Flutter package, but in the Native SDK.

Please open an issue in the platform repository:

- iOS: [https://github.com/BranchMetrics/ios-branch-deep-linking-attribution](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution)
- Android: [https://github.com/BranchMetrics/android-branch-deep-linking-attribution](https://github.com/BranchMetrics/android-branch-deep-linking-attribution)

**Comment by vishnunew** [comment]
@RodrigoSMarques I have debug this package on Android and did return Long URL when generating short URL in offline at this file. https://github.com/RodrigoSMarques/flutter_branch_sdk/blob/9aa33558b2a047fb49fd8e3f65524b8ef763fac7/android/src/main/java/br/com/rsmarques/flutter_branch_sdk/FlutterBranchSdkPlugin.java#L383
It also returns error but in the code it was not considering the URL but it did return URL from Branch SDK.

**Comment by RodrigoSMarques** [comment]
Strange. If the Branch SDK returns an error, the link will not be returned.

```dart
    buo.generateShortUrl(activity, linkProperties, new Branch.BranchLinkCreateListener() {
      @Override
      public void onLinkCreate(String url, BranchError error) {

        if (error == null) {
          LogUtils.debug(DEBUG_NAME, "Branch link to share: " + url);
          response.put("success", true);
          response.put("url", url);
        } else {
          response.put("success", false);
          response.put("errorCode", String.valueOf(error.getErrorCode()));
          response.put("errorMessage", error.getMessage());
        }
        result.success(response);
      }
    });
````

I need to debug, I'll do that later.

**Comment by RodrigoSMarques** [comment]
@vishnunew 

Debugging the code on iOS and Android, I found that even with the connectivity error, the url is generated.
I will release a new version with this fix.

**Comment by RodrigoSMarques** [comment]
Closed. Version 6.7.1 with fix released
