### ISSUE TITLE
Android validateSDKIntegration fails with Uri Scheme wildcard host

### ISSUE THREAD

**Issue by Alqueraf** [RodrigoSMarques/flutter_branch_sdk#241]
**Describe the bug**
When running `FlutterBranchSdk.validateSDKIntegration()`, step "6. Verifying intent for receiving URI scheme." fails when the intent `host` uses a wildcard `"*"`.
This contradicts the Android SDK documentation:
https://help.branch.io/developers-hub/docs/android-basic-integration#configure-app
```xml
<!-- If utilizing $deeplink_path please explicitly declare your hosts, or utilize a wildcard(*) -->
```
```
<data android:scheme="${branchScheme}" android:host="*" />
```

**To Reproduce**
1. Set your URI Scheme intent-filter to use host value '*' (ie: `<data android:scheme="${branchScheme}" android:host="*" />`)
2. Run Flutter method `FlutterBranchSdk.validateSDKIntegration()`.
3. Observe the code expects `open` as the host value.
4. Observe step 6 fails with error: `** ERROR ** : Uri scheme 'xxxxxx://' specified in Branch dashboard doesn't match with the deep link intent in manifest file`

**Expected behavior**
- A wildcard `"*"` value should be accepted for the URI host as stated in the documentation.
- Step 6 should PASS.

**Screenshots**
<img width="1145" alt="image" src="https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/6831557/f04d4aae-d720-4a58-9a9d-095b78bdba06">
<img width="973" alt="image" src="https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/6831557/932e8bde-aba6-4e04-852b-60b964c3aae3">

**Smartphone (Please complete the following information. remove session if not platform):**
 - Flutter: version: 3.13.1
 - Package version: 6.7.1
 - Device: Emulator

**Comment by RodrigoSMarques** [comment]
This package calls Branch Native SDK functions on each platform.
The problem reported is not in the Flutter package, but in the Native SDK.
Please open an issue in the platform repository:
* iOS: [https://github.com/BranchMetrics/ios-branch-deep-linking-attribution](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution)
* Android: [https://github.com/BranchMetrics/android-branch-deep-linking-attribution](https://github.com/BranchMetrics/android-branch-deep-linking-attribution)
