### ISSUE TITLE
Support for setting customer_event_alias for  BranchEvent

### ISSUE THREAD

**Issue by jf-branch** [RodrigoSMarques/flutter_branch_sdk#244]
**Feature Request**
The Branch v2 Events API and the native iOS SDKs support associating an event alias property to standard and custom events, but this does not seem exposed through the Flutter Event interface. 

iOS declaration of BranchEvent.alias: https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/blob/master/BranchSDK/BranchEvent.h#L78 

Android declartion of BranchEvent.setCustomerEventAlias : https://github.com/BranchMetrics/android-branch-deep-linking-attribution/blob/master/Branch-SDK/src/main/java/io/branch/referral/util/BranchEvent.java#L71 

Could we please request to support exposing setting of this parameter through flutter_event.dart's BranchEvent: https://github.com/RodrigoSMarques/flutter_branch_sdk/blob/master/lib/src/objects/branch_event.dart#L49 

Thank you! 
Best,
Justin

**Comment by RodrigoSMarques** [comment]
Hi @jf-branch 

I will analyze the code to understand how it works. Is there any documentation in the SDK guides that explains how this method works?

**Comment by RodrigoSMarques** [comment]
@jf-branch 

you can analyze this issue here: #168

**Comment by jf-branch** [comment]
@RodrigoSMarques not specifically for customer_event_alias, but the business value is as a subtype or a subname to better distinguish standard or larger events. But this API reference may help: https://help.branch.io/developers-hub/reference/events-api 

I.e I have a Subscription event, top level its SUBSCRIPTION, but if i wanted to distinguish what type of SUBSCRIPTION i can do so through customer_event_alias: 
i.e: 
Event Name: SUBSCRIPTION: 
customer_event_alias options: 
- one_month 
- three_months
- twelve_months 

etc, and then there are some mapping configurations we have when exporting data in which they can use the alias as a filtering field. 

but the API excepts it for v2/events at the top level for the key 'customer_event_alias', this is what the native SDKs send it as, when set as a property of BranchEvent 

and i will address: https://github.com/RodrigoSMarques/flutter_branch_sdk/issues/168

**Comment by RodrigoSMarques** [comment]
Hi @jf-branch 
The enhancement will be released in 6.9.0, tonight or tomorrow morning.
Development is complete and testing on iOS, Android and Web.

It will then be replicated in 7.0.0 which I will keep in beta for some time.

**Comment by jf-branch** [comment]
Amazing! Great work. Thank you so much!

**Comment by RodrigoSMarques** [comment]
@jf-branch 
Versions 6.9.0 and 7.0.0-beta.2 released
