### ISSUE TITLE
java.lang.InterruptedException on android real device 

### ISSUE THREAD

**Issue by heshesh2010** [RodrigoSMarques/flutter_branch_sdk#246]
Hi , in latest release I got error :

W/System.err(10768): java.lang.InterruptedException
W/System.err(10768): 	at java.lang.Thread.sleep(Native Method)
W/System.err(10768): 	at java.lang.Thread.sleep(Thread.java:450)
W/System.err(10768): 	at java.lang.Thread.sleep(Thread.java:355)
W/System.err(10768): 	at io.branch.referral.network.BranchRemoteInterfaceUrlConnection.doRestfulPost(BranchRemoteInterfaceUrlConnection.java:229)
W/System.err(10768): 	at io.branch.referral.network.BranchRemoteInterfaceUrlConnection.doRestfulPost(BranchRemoteInterfaceUrlConnection.java:57)
W/System.err(10768): 	at io.branch.referral.network.BranchRemoteInterface.make_restful_post(BranchRemoteInterface.java:141)
W/System.err(10768): 	at io.branch.referral.ServerRequestQueue$BranchPostTask.doInBackground(ServerRequestQueue.java:520)
W/System.err(10768): 	at io.branch.referral.ServerRequestQueue$BranchPostTask.doInBackground(ServerRequestQueue.java:491)
W/System.err(10768): 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
W/System.err(10768): 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
W/System.err(10768): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
W/System.err(10768): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
W/System.err(10768): 	at java.lang.Thread.run(Thread.java:1012)

**Comment by RodrigoSMarques** [comment]
which release? beta? 
which version of Android? 
When does the error occur? 

Please open a new issue with all the information requested to carry out the analysis. 
thanks
