### ISSUE TITLE
Long URLs data not available in data stream

### ISSUE THREAD

**Issue by marcotta** [RodrigoSMarques/flutter_branch_sdk#251]
**Describe the bug**
Using `getShortUrl` with a `BranchUniversalObject` while offline generates a Long URL.
The long URL contains query parameters like `feature` and `data`.
Tapping on Long URL opens the app, but none of the data is available via 
`StreamSubscription<T> listen(void onData(T event)?,
      {Function? onError, void onDone()?, bool? cancelOnError});` 
 The stream correctly reports the data when a Short URL is used

**To Reproduce**
1. Use SDK while offline
2. Create a Branch Universal Object
3. Use getShortUrl with the buo object created on step 2
4. Take long url from BranchResponse.result
5. Tap on the link from to launch the app
6. Check ` FlutterBranchSdk.initSession().listen((data) { })`

**Expected behavior**
Data should contain the data associated to the branch universal object created on step 2
`referring_link` should match the Long Url  

**Actual behaviour**
Buo object data is not available 
`referring_link` only contains the randomized_bundle_token 

**Smartphone (Please complete the following information. remove session if not platform):**
 - Flutter: version: [3.10.0]
 - Package version: [6.9.0]
 - OS: [Android 13]
 - Device: [Android Emulator, Samsung Galaxy A32]

**Comment by RodrigoSMarques** [comment]
This package calls Branch Native SDK functions on each platform.

The problem reported is not in the Flutter package, but in the Native SDK.

Please open an issue in the platform repository:

- iOS: [https://github.com/BranchMetrics/ios-branch-deep-linking-attribution](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution)
- Android: [https://github.com/BranchMetrics/android-branch-deep-linking-attribution](https://github.com/BranchMetrics/android-branch-deep-linking-attribution)

Or open a support ticket for Branch at the [link] (https://help.branch.io/using-branch/page/submit-a-ticket)

**Comment by RodrigoSMarques** [comment]
I believe you can even create the links offline, but an internet connection is needed to process the data.

**Comment by marcotta** [comment]
Thanks @RodrigoSMarques perhaps I am doing something wrong, 
the links are correctly produced offline, but I don't seem to have a way to handle them.

Example: 
A user creates a link offline and then shares the url with another user.
The second user taps on the very long link and the receiving app does not pass the data through the `FlutterBranchSdk.initSession().listen((data) { })` stream.
This means the app won't be able to handle the action associated to the data.

Is there some other method I should be using to retrieve the data?

**Comment by RodrigoSMarques** [comment]
@marcotta 

I'll do some tests and then I'll give you an answer

**Comment by RodrigoSMarques** [comment]
@marcotta 

Do you still have any questions about this issue?

**Comment by marcotta** [comment]
Hi @ro

> @marcotta
> 
> Do you still have any questions about this issue?

Thanks @RodrigoSMarques for getting back,  
As soon as I get a chance I will test again on version 7.0.2, I suppose this will include a new version of the Android native SDK. Hopefully it works there.
I am currently still using version 6.9.0 and on that version I am not able to retrieve any data forwarded via long urls.

**Comment by RodrigoSMarques** [comment]
@marcotta 

Why do you need to add a base64 parameter? Wouldn't it be easier to add an identifier for this base64 attribute and retrieve it in your application, instead of passing it as a parameter?

The problem reported is not in the Flutter plugin, but in the Branch Native SDK.

I suggest you open a support ticket for Branch.

Please open an issue in the platform repository:

- iOS: [https://github.com/BranchMetrics/ios-branch-deep-linking-attribution](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution)
- Android: [https://github.com/BranchMetrics/android-branch-deep-linking-attribution](https://github.com/BranchMetrics/android-branch-deep-linking-attribution)

Or open a support ticket for Branch at the [link](https://help.branch.io/using-branch/page/submit-a-ticket)

**Comment by marcotta** [comment]
Thanks @RodrigoSMarques 
I have created an issue on the [android sdk project] https://github.com/BranchMetrics/android-branch-deep-linking-attribution/issues/1179

**Comment by marcotta** [comment]
I have tested this issue on version 8.0.2 and it is not retrieving the data contained in the Branch Universal Object
the BUO data is contained in the url parameter `data` and this information is not made available in `_branchSdk.listSession().listen((data) {});`
