### ISSUE TITLE
int android.content.Intent.getFlags()

### ISSUE THREAD

**Issue by HarshNT** [RodrigoSMarques/flutter_branch_sdk#254]
**Error Logs**
E/MethodChannel#flutter_branch_sdk/message( 8335): Failed to handle method call
E/MethodChannel#flutter_branch_sdk/message( 8335): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Intent.getFlags()' on a null object reference
E/MethodChannel#flutter_branch_sdk/message( 8335): 	at android.app.ContextImpl.startActivity(ContextImpl.java:1122)
E/MethodChannel#flutter_branch_sdk/message( 8335): 	at android.app.ContextImpl.startActivity(ContextImpl.java:1103)
E/MethodChannel#flutter_branch_sdk/message( 8335): 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:436)
E/MethodChannel#flutter_branch_sdk/message( 8335): 	at br.com.rsmarques.flutter_branch_sdk.FlutterBranchSdkPlugin.setupBranch(FlutterBranchSdkPlugin.java:447)
E/MethodChannel#flutter_branch_sdk/message( 8335): 	at br.com.rsmarques.flutter_branch_sdk.FlutterBranchSdkPlugin.onMethodCall(FlutterBranchSdkPlugin.java:252)
E/MethodChannel#flutter_branch_sdk/message( 8335): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#flutter_branch_sdk/message( 8335): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#flutter_branch_sdk/message( 8335): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#flutter_branch_sdk/message( 8335): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#flutter_branch_sdk/message( 8335): 	at android.os.Handler.handleCallback(Handler.java:958)
E/MethodChannel#flutter_branch_sdk/message( 8335): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#flutter_branch_sdk/message( 8335): 	at android.os.Looper.loopOnce(Looper.java:205)
E/MethodChannel#flutter_branch_sdk/message( 8335): 	at android.os.Looper.loop(Looper.java:294)
E/MethodChannel#flutter_branch_sdk/message( 8335): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/MethodChannel#flutter_branch_sdk/message( 8335): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_branch_sdk/message( 8335): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/MethodChannel#flutter_branch_sdk/message( 8335): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

**Comment by RodrigoSMarques** [comment]
which version package?
which version of Android?
When does the error occur?

Please open a new issue with all the information requested to carry out the analysis.

thanks

**Comment by HarshNT** [comment]
flutter_branch_sdk: ^7.0.0

Android 13

Error occure when i use this   **await FlutterBranchSdk.init(
      useTestKey: false, enableLogging: false, disableTracking: false);** in main.dart.
