### ISSUE TITLE
Fatal error: Unexpectedly found nil while unwrapping an Optional value - flutter_branch_sdk: ^6.9.0

### ISSUE THREAD

**Issue by cardevisi** [RodrigoSMarques/flutter_branch_sdk#258]
**Describe the bug**
I'm trying to build a Flutter application for IOS, but I received this error.  More details below:

flutter_branch_sdk/SwiftFlutterBranchSdkPlugin.swift:311: Fatal error: Unexpectedly found nil while unwrapping an Optional value

**To Reproduce**
1. After pod install and melos update
2. I ran fvm flutter run
3. When the application was initialized in the simulator 

**Or the alternative way**

1. After pod install and melos update
2. I try to build directly in xcode

**Expected behavior**
I would like build without any problems.

**Screenshots**
![image](https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/755583/bdd4115e-0839-4a91-93ea-bb69b88c9b87)

**IOS Simulator: **
 - Flutter: version: 3.10.0
 - Package version: flutter_branch_sdk: ^6.9.0
 - OS: iOS17.0
 - Device: iPhone15 Simulator - IOS 17.0

**Comment by RodrigoSMarques** [comment]
I cannot reproduce the problem. I need more details.

I note that the error occurred in the `FlutterBranchSdk.trackContent` method.

I need the code example that you are using to initialize the BranchUniversalObject and that you are passing to the method.

Are you passing just one item or a Buo list?

**Comment by cardevisi** [comment]
Hi Rodrigo, thanks a lot! This is the way that we implemented the trackContent call. But after your comment we call another method Flutter **BranchSdk.trackContentWithoutBuo** and the problem solved.

![image](https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/755583/17ec0bdd-59d9-4115-9814-f47ef1c9aef3)
