### ISSUE TITLE
Application crashing on fresh installation via play store.

### ISSUE THREAD

**Issue by rajajain08** [RodrigoSMarques/flutter_branch_sdk#26]
My application is working fine in debugging mode and even in release mode. The problem arises when I'm trying to install my application via PlayStore.
When I follow the stack trace I found that the problem is with branchio plugin.
![stack](https://user-images.githubusercontent.com/19187138/78355892-2ef7ee80-75cc-11ea-9375-618a3d3eb189.png)
Opening the app for a second time is working fine.
I think there is some problem with the Branch Installation listener.

flutter_branch_sdk version : 0.2.0

**Comment by RodrigoSMarques** [comment]
Hi @rajajain08 
Check if your AndroidManifest.xml has the tags below

```xml
<receiver android:name="io.branch.referral.InstallListener" android:exported="true">
  <intent-filter>
    <action android:name="com.android.vending.INSTALL_REFERRER" />
  </intent-filter>
</receiver>
```
If it exists, remove and also consider updating the plugin to the latest version which is 0.4.0 which corrects some bugs and uses the latest version of the Branch SDK.

**Comment by rajajain08** [comment]
Thanks! I working now.
