### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by pankaj541998** [RodrigoSMarques/flutter_branch_sdk#261]
**Describe the bug**
PlatformException(error, Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?, null, android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/91595114/0c15c795-3285-40ab-b39e-988841b189b2)

**Smartphone (Please complete the following information. remove session if not platform):**
 - Flutter: version: [e.g. 2.2.3]
![image](https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/91595114/cdae9a22-0d03-4dac-b301-d3b53675af3c)

 - Package version: [e.g. 3.3.0]
 Latest Version
 - Device: [e.g. Oneplus 11R]
 
**Web (please complete the following information. remove session if not platform):**
 - Flutter: version: [e.g. 2.2.3]
 - Package version: [e.g. 3.3.0]
 - OS: [e.g. Windows, Mac, Linux]
 - Browser [e.g. chrome, safari, edge]
 
 - **Additional context**

Continuously showing same Exception i run the your example also but getting error.

Unhandled Exception: PlatformException(error, Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag.  

Please check the Screen shot mention 👎

![image](https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/91595114/c765e20e-c11d-4669-8287-d282b451ba63)

**Comment by RodrigoSMarques** [comment]
What is the Android version of the test device?

**Comment by pankaj541998** [comment]
I am using Android version 13. And the device Model Name OnePlus 11R.

**Comment by RodrigoSMarques** [comment]
@pankaj541998 

I cannot reproduce the error.

I don't have a physical device with Android 13. I'm using the emulator.

<img width="721" alt="Captura de Tela 2023-11-16 às 21 47 44" src="https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/17687286/cb41b2a1-835f-404d-9b57-6d039d480fa1">


Is your project using FlutterActivity or FlutterFramentActivity?

**Comment by pankaj541998** [comment]
The most recent or upcoming devices come equipped with the latest version. Consequently, how can we effectively utilize them? I currently employ FlutterActivity in my projects.

**Comment by pankaj541998** [comment]
Sorry i can't understand, can you elaborate this.

**Comment by pankaj541998** [comment]
Sure, let me know what i have to do ?
What you want me to just change the code provided above in your YAML file, right?

**Comment by RodrigoSMarques** [comment]
> Sure, let me know what i have to do ? What you want me to just change the code provided above in your YAML file, right?

correct. you need to update pubspec.yaml to use a version that is available on Github and not on pub.dev.

Thanks.

**Comment by RodrigoSMarques** [comment]
Fixed in version 7.0.2
