### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by jonmountjoy** [RodrigoSMarques/flutter_branch_sdk#267]
**Which problem is this feature request solving?**

I'd like to, at the very least, create links using MacOS.  Even better if I can react to them too.

Is it possible to extend this to MacOS?

**Comment by RodrigoSMarques** [comment]
I will do an analysis

**Comment by ductung-bfast** [comment]
@RodrigoSMarques We want macOS too. I think if you implement macOS support, we will be your customer immediately :D

**Comment by jonmountjoy** [comment]
The same goes for other platforms too really.  The great thing about Flutter is that allows you to create an app that runs in all these different environments, and ideally you need the libraries to support the same (I'm thinking of Windows next after MacOS).

**Comment by RodrigoSMarques** [comment]
Hello everyone, closing this issue.

I am not available to add support for Windows and MacOS.

If you can contribute, send a PR.
