### ISSUE TITLE
Indicate when error is thrown in init

### ISSUE THREAD

**Issue by apackin** [RodrigoSMarques/flutter_branch_sdk#270]
https://github.com/RodrigoSMarques/flutter_branch_sdk/blob/f5d2753727c5b8866b6d102771159fb43aae5abc/ios/Classes/SwiftFlutterBranchSdkPlugin.swift#L299

This code path includes `print("Branch InitSession error` to indicate when an error is thrown from this path because it's useful for debugging. It would be helpful for debugging production issues as well if this information was passed along.

Perhaps we can include something along the lines of "InitSession error" in the message passed to FlutterError?
As in `message: "InitSession error: \(err.localizedDescription)",` instead of just `message: err.localizedDescription,`

**Comment by RodrigoSMarques** [comment]
Thanks for the sugestion. I will include it in the next version of the package.

**Comment by RodrigoSMarques** [comment]
Fixed in version [7.0.2](https://pub.dev/packages/flutter_branch_sdk)
