### ISSUE TITLE
+clicked_branch_link is always false on freshly installed  iOS app

### ISSUE THREAD

**Issue by korolkir** [RodrigoSMarques/flutter_branch_sdk#273]
**Describe the bug**
+clicked_branch_link parameter is always false on freshly installed  iOS app and the data is not received. However exactly the same link works perfectly fine if the app is already installed. Issue is reproducable on several real devices. I already checked full setup, verify that both live key and live link is used, NativeLink is enabled. Checked troubleshooting doc, nothing helped.
I'm also calling FlutterBranchSdk.getFirstReferringParams() after 3 sec (as in the example app), these params are empty.

**To Reproduce**
1. Remove the App from the device
2. Click on link in Notes app (https://simulnow.app.link/DMuklp9DDFb), Deepview screen is opened.
3.  Install app from Xcode or Firebase distribution
4. App launches, +clicked_branch_link = false is received, no Data from link is received, getFirstReferringParams is empty.

**Expected behavior**
+clicked_branch_link should be true, data from link should be received.

**Screenshots**
<img width="1228" alt="Screenshot 2023-12-19 at 21 14 50" src="https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/14893992/4dc51b00-13e1-4ad9-adb5-c03dbc5228c7">
![photo_2023-12-19 21 18 44](https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/14893992/cb8655a9-1304-4860-a30d-0733262b53ae)

 - Flutter: version:  3.16.0
 - Package version: 7.0.1
 - OS: iOS 17.1.2 (21B101)
 - Xcode version 15.0.1 (15A507)
 - Device: iPhone11, Iphone 11 Pro Max

**Comment by RodrigoSMarques** [comment]
Is the prompt requesting access to the pasteboard displayed at application startup?

**Comment by korolkir** [comment]
Hello @RodrigoSMarques Thank you for quick reply!
Sometimes prompt is displayed, sometimes not. But even if it is displayed, I still has +clicked_branch_link = false
I checked the issue above, but unfortunately there is no solution mentioned in that issue, so it doesn't really help, I still got the problem as guys described

**Comment by korolkir** [comment]
I also noticed, when app is not installed and you click on link in Notes app, error message "Safari cannot open the page because the address is invalid" is displayed, but then Deepview page is opened. Can it be the reason of the issue?

**Comment by RodrigoSMarques** [comment]
@korolkir 

I suggest you open a support ticket with Branch to verify your project.

This package calls Branch Native SDK functions on each platform.

The problem reported is not in the Flutter package, but in the Native SDK.

Open a support ticket for Branch at the [link] (https://help.branch.io/using-branch/page/submit-a-ticket) or open an issue in the platform repository:

- iOS: [https://github.com/BranchMetrics/ios-branch-deep-linking-attribution](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution)

**Comment by korolkir** [comment]
@RodrigoSMarques 
Sure, I'll create a support ticket.

But are you able to reproduce the problem with your example APP? Or you can successfully receive deeplink on fresh iOS app install?

**Comment by RodrigoSMarques** [comment]
> @RodrigoSMarques Sure, I'll create a support ticket.
> 
> But are you able to reproduce the problem with your example APP? Or you can successfully receive deeplink on fresh iOS app install?

The sample app is not published in the store. 

I do the test, copying the link to the clipboard, removing it and when installing again, I am asked to access the clipboard and it recovers the data.

**Comment by korolkir** [comment]
The problem resolved. It was incorrect configuration of Native Link. Closing

**Comment by khang-dev** [comment]
@korolkir what was the incorrect configuration could you share ? I'm having the same problem
