### ISSUE TITLE
Documentation does not reflect git readme

### ISSUE THREAD

**Issue by stact** [RodrigoSMarques/flutter_branch_sdk#276]
**Describe the bug**
I'm trying to migrate Firebase Dynamic Links to Branch.io without success.
Some inconsistency between documentations.
For example it could be nice to have the complete configuration for flutter instead of redirecting to another iOS and Android native

**To Reproduce**
1. Create new empty project
2. Try to follow the documtation https://www.branch.io/guides/how-to-migrate-from-firebase-dynamic-links/
3. Spaghetti configuration :) 

**Expected behavior**
A clear documentation for configuring with Flutter

**Smartphone:**
 - Flutter: version: last version
 - Package version: last version
 - OS: last version
 - Device: iOS and Android
 
**Additional context**

**Comment by RodrigoSMarques** [comment]
The configuration for Dynamic Links is in the native project.

Branch defines as the necessary settings.

This plugin calls the native APIs.

Replicating the documentation could require frequent updates to the Flutter documentation to reflect changes made by Branch.

For this reason, the link to the official Branch documentation was inserted.

If you have questions about the instructions on the page https://www.branch.io/guides/how-to-migrate-from-firebase-dynamic-links/, please open an issue in the platform repository:

- iOS: [https://github.com/BranchMetrics/ios-branch-deep-linking-attribution](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution)
- Android: [https://github.com/BranchMetrics/android-branch-deep-linking-attribution](https://github.com/BranchMetrics/android-branch-deep-linking-attribution)

Or open a support ticket for Branch at the [link](https://help.branch.io/using-branch/page/submit-a-ticket)

**Comment by stact** [comment]
Thank you for your feedback @RodrigoSMarques I will open a ticket and keep you informed here if I have news

**Comment by stact** [comment]
<img width="458" alt="image" src="https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/9899166/ee740292-1614-463d-ae38-b5d85a8e1334">
