### ISSUE TITLE
7.0.3 depends on js ^0.7.0, conflicting with other common packages such as wakelock_plus

### ISSUE THREAD

**Issue by dgilperez** [RodrigoSMarques/flutter_branch_sdk#289]
7.0.3 depends on js ^0.7.0, conflicting with other common packages such as wakelock_plus, which depends on `^0.6.3`. 

While this is actually not a bug, would it be possible to relax this dependency?

**Comment by RodrigoSMarques** [comment]
Fixed in version [7.0.4](https://pub.dev/packages/flutter_branch_sdk)
