### ISSUE TITLE
Setting Fallback URL causing social share properties to not show.

### ISSUE THREAD

**Issue by StephanWalters** [RodrigoSMarques/flutter_branch_sdk#295]
**Describe the bug**
Setting the fallback url of a BranchUniversalObject is causing the Branch preview in social shares to not show. When I omit the link $fallback_url it works as expected.

```
final buo = BranchUniversalObject(
      canonicalIdentifier: 'product/${product.id}',
      canonicalUrl: 'https://$host/product/index.html?p=${product.id}',
      title: 'Check out ${product.name} on App',
      imageUrl: product.image,
      keywords: [
        AppConstants.appName,
        product.name,
      ],
      contentMetadata: BranchContentMetaData()
        ..addCustomMetadata('type', 'product')
        ..addCustomMetadata('id', product.id)
    );
    final lp = BranchLinkProperties(
      channel: 'app',
      feature: 'feature',
      stage: 'prod',
    );
lp.addControlParam(
        '\$fallback_url', 'http://$host/products/index.html?p=${product.id}');

BranchResponse response = await FlutterBranchSdk.showShareSheet(
      buo: buo,
      linkProperties: lp,
      androidMessageTitle:
          'Check out ${product.name} on app',
      androidSharingTitle: 'Share ${product.name}',
      messageText:
          'Check out ${product.name} '}',
    );
```

**To Reproduce**
1. Create BranchUniversalObject
2. Set fallbackUrl in LinkProperities
3. Show ShareSheet w/ bou and share.

**Expected behavior**
Preview should still show as i am setting the BranchUniversalObject title and image.

**Screenshots**

When I set the fallback url:
![IMG_8977](https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/4071276/dc8761be-24a7-48f4-9c44-c6e5f3e17f9e)
![IMG_8976](https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/4071276/a72fd2f0-0fcb-4c40-8bdd-a610ad40c53b)

Without setting the fallback url:
![IMG_8979](https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/4071276/ea0aa8b9-3a5e-48c0-820c-08b0b8747b40)
![IMG_8978](https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/4071276/5a64b7f9-c221-4a54-bced-0c2cec0529c7)

**Smartphone (Please complete the following information. remove session if not platform):**
 - Flutter: version: 3.16.0
 - Package version: ^6.7.0
 - OS:  iOS17.2
 - Device: iPhone 12
 - **Additional context**

**Comment by RodrigoSMarques** [comment]
Hi @StephanWalters .

This package calls Branch Native SDK functions on each platform.

The problem reported is not in the Flutter plugin, but in the Native SDK.

Please open an issue in the platform repository:

- iOS: [https://github.com/BranchMetrics/ios-branch-deep-linking-attribution](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution)
- Android: [https://github.com/BranchMetrics/android-branch-deep-linking-attribution](https://github.com/BranchMetrics/android-branch-deep-linking-attribution)

Or open a support ticket for Branch at the [link](https://help.branch.io/using-branch/page/submit-a-ticket)
