### ISSUE TITLE
Allow Call `setRequestMetadata` after `FlutterBranchSdk.init()` method

### ISSUE THREAD

**Issue by chenbokun97** [RodrigoSMarques/flutter_branch_sdk#297]
**Describe the bug**
When we trying to update a request metadata key after initialing brach sdk, it throws this error.
I've checked the code in flutter branch sdk, it asserts that this function are supposed to be called before init
While when I saw the implementation in native side, both support to call setRequestMetadata after init

**To Reproduce**
call await FlutterBranchSdk.init()
call FlutterBranchSdk.setRequestMetadata()

**Expected behavior**
should set request metadata successfully, or provide another api to update the metadata. Thanks.

**Smartphone:**
 - Flutter: version: 3.16.9
 - Package version: 7.0.4
 - OS: iOS & Android
 - Device:  iPhone15 & Google Pixel

**Comment by RodrigoSMarques** [comment]
Fixed in version [7.1.0](https://pub.dev/packages/flutter_branch_sdk)
