### ISSUE TITLE
Proper documentation for NativeLink™ Deferred Deep Linking

### ISSUE THREAD

**Issue by AristideVB** [RodrigoSMarques/flutter_branch_sdk#302]
**Which problem is this feature request solving?**

Currently the [documentation](https://help.branch.io/developers-hub/docs/ios-advanced-features#nativelink-deferred-deep-linking) for NativeLink support is specific to iOS.

We do not know which lines of Swift code need to be added to our Flutter app iOS part vs what is already handled by the Flutter SDK 

Also does 

```
<key>branch_check_pasteboard</key>
	<true/>
```

Still need to be added to `INFO.PLIST`

**Describe the solution you'd like**

We would love a more Flutter specific documentation for setting up NativeLink™

**Comment by RodrigoSMarques** [comment]
Hi @AristideVB 

The documentation already contains the reference that it is not necessary to perform any action in the native code (Swift),

[Here](https://github.com/RodrigoSMarques/flutter_branch_sdk?tab=readme-ov-file#nativelink-deferred-deep-linking)

<img width="872" alt="Captura de Tela 2024-03-13 às 08 11 52" src="https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/17687286/ec85fc7a-d7d4-413d-896a-dd1dd842a489">
