### ISSUE TITLE
Is it necessary to add dependencies?

### ISSUE THREAD

**Issue by desmeit** [RodrigoSMarques/flutter_branch_sdk#303]
In your docs you write:

```
Android Integration

Follow the steps:

[Configure App](https://help.branch.io/developers-hub/docs/android-basic-integration#4-configure-app)
```

Under "configure App" we have to add to the app-level build.gradle:

```
    // Required for all Android apps:
	implementation 'io.branch.sdk.android:library:5.10.0' // Check for latest version before hard-coding
    // Required if your app is in the Google Play Store (tip: avoid using bundled play services libs):
	implementation 'com.google.android.gms:play-services-ads-identifier:18.0.1'
	// Alternatively, use the following lib for getting the AAID:
	// implementation 'com.google.android.gms:play-services-ads:17.2.0'
```
:

But is this really necessary? But is that really necessary? Isn't the SDK already included in the Flutter plugin?

Same for iOS: 
Is it necessary to install Branch through CocoaPods?

Thanks for the clarification.

**Comment by RodrigoSMarques** [comment]
It is not necessary to add the Branch dependency to the project as the plugin performs these actions upon installation.

For this reason, the documentation link does not mention the [`Install Branch`](https://help.branch.io/developers-hub/docs/android-basic-integration#2-install-branch) and [`Add Dependencies`](https://help.branch.io/developers-hub/docs/android-basic-integration#3-add-dependencies) and others sections of the native documentation.

Same for iOS.
