### ISSUE TITLE
PlatformException on iOS after upgrade to flutter 3.19.3

### ISSUE THREAD

**Issue by arthurgiani** [RodrigoSMarques/flutter_branch_sdk#305]
**Describe the bug**
on iOS (android is fine), Branch SDK is returning the following error after call `await FlutterBranchSdk.init()`.

`PlatformException(1003, The network request was invalid., null, null)`

**To Reproduce**
1. Open the app with the respective branch sdk installed

**Expected behavior**
Successful Integration.

**Screenshots**
![image](https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/45671820/7df25bdd-f36b-40e2-a933-19e3773350e7)

**Smartphone (Please complete the following information. remove session if not platform):**
 - Flutter: version: [e.g. 3.19.3]
 - Package version: [e.g. 7.1.0]
 - Device: [e.g. iPhone15 Pro Max, Google Pixel 4 API]
 
 **Additional Context**
 
![image](https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/45671820/2e4648ff-d6e7-4b0f-9d5d-fc315742e5c5)

**Comment by RodrigoSMarques** [comment]
This error message has no relation to the flutter update. 

This message is returned by the native SDK in Obj-c. 

Run the application directly through XCode and send the execution log displayed in the console. 

in the FlutterBranchSdk.init method use enableLogging = true.

**Comment by arthurgiani** [comment]
> This error message has no relation to the flutter update.
> 
> This message is returned by the native SDK in Obj-c.
> 
> Run the application directly through XCode and send the execution log displayed in the console.
> 
> in the FlutterBranchSdk.init method use enableLogging = true.

This error is not being displayed if I run my project on my previous version (3.16.0). That's why I said it started to break after my upgrade to 3.19.3.


**Version 3.16.0 running through Xcode**
- Nothing happens

**Version 3.19.3 running through Xcode**

![Screenshot 2024-03-21 at 10 52 28](https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/45671820/0507f5f0-d471-4c54-8c0c-4fd1fd1490c1)

**Comment by RodrigoSMarques** [comment]
Have you downgraded to a previous version of Flutter and made sure that the error does not occur in this version?

Is the error returned right after call `FlutterBranchSdk.init()`?

Are there any SDK commands being called before or after `FlutterBranchSdk.init()`?

This package calls Branch Native SDK functions on each platform.

The problem reported is not in the Flutter plugin, but in the Native SDK.

Depending on the action in your application, this problem should be checked by the Branch team, responsible for the iOS SDK.

**Comment by arthurgiani** [comment]
> Have you downgraded to a previous version of Flutter and made sure that the error does not occur in this version?
> Yes. Running ok on 3.16.0

> Is the error returned right after call `FlutterBranchSdk.init()`?
> The error is being displayed after FlutterBranchSdk.listSession()

> Are there any SDK commands being called before or after `FlutterBranchSdk.init()`?
> No.
 
> This package calls Branch Native SDK functions on each platform.
> 
> The problem reported is not in the Flutter plugin, but in the Native SDK.
> 
> Depending on the action in your application, this problem should be checked by the Branch team, responsible for the iOS SDK.

**Comment by arthurgiani** [comment]
> Have you downgraded to a previous version of Flutter and made sure that the error does not occur in this version?
> 
> Is the error returned right after call `FlutterBranchSdk.init()`?
> 
> Are there any SDK commands being called before or after `FlutterBranchSdk.init()`?
> 
> This package calls Branch Native SDK functions on each platform.
> 
> The problem reported is not in the Flutter plugin, but in the Native SDK.
> 
> Depending on the action in your application, this problem should be checked by the Branch team, responsible for the iOS SDK.

1 - Yes
2 - The error is being displayed after FlutterBranchSdk.listSession()
3 - No. init is the first triggered method.

**Comment by arthurgiani** [comment]
Nothing on this?

**Comment by arthurgiani** [comment]
This issue no longer happens on flutter 3.19.6, but now the following issue #317 is happening.
