### ISSUE TITLE
Retrieve Origin Path from NativeLink™ on iOS

### ISSUE THREAD

**Issue by AristideVB** [RodrigoSMarques/flutter_branch_sdk#310]
**Describe the bug**

When opening a QuickLink with NativeLink feature on iOS QuickLink path is lost & replaced by a generic path.

I'm able to retrieve queryParams with `flutter_branch_sdk` but origin path is lost

**To Reproduce**
1. Go to https://dashboard.branch.io/configuration/general
2. Enable NativeLink™ feature on iOS
3. Go to https://dashboard.branch.io/quick-links/manager 
4. Create a QuickLink with path a path for example `https://branchster.app.link/onboarding`
5. Open the link on iOS & copy the link to clip board as suggest & install app
6. The link copied to clip board is `https://branchster-alternate.app.link/XEiAZjL0THb?....`

8. Where did the origin path go ? 
 In Flutter I'm not able to retrieve it even by calling `await FlutterBranchSdk.getFirstReferringParams();`

**Expected behavior**

I should be able to retrieve the origin path from the branch_flutter_sdk or the origin path should be kept in the NativeLink copied to clip board
 
 **Additional context**
<details>
<summary>Click to see my code</summary>

```dart 
  void _listenToDeepLinks() {
    FlutterBranchSdk.listSession().listen(
      (data) async {
        if (data.containsKey('+clicked_branch_link') &&
            data['+clicked_branch_link'] == true) {
          final deepLinkUri = Uri.parse(data['~referring_link'] as String);

          final Map<dynamic, dynamic> params =
              await FlutterBranchSdk.getFirstReferringParams();

          print('params ${params}');

          Future.delayed(const Duration(seconds: 3), () {
            _deepLinkSubject.add(deepLinkUri);
          });
        }
      },
      onError: (error) =>
          _deepLinkSubject.addError(DeepLinkClientFailure('Branch.io Error')),
    );
  }
```
</details>

**Comment by RodrigoSMarques** [comment]
Hi @AristideVB 

I didn't understand. do you want to retrieve the url of the first clicked link?

**Comment by AristideVB** [comment]
@RodrigoSMarques I don't understand why my quick link path `onboarding` from my link `https://branchster.app.link/onboarding` is transformed into a generated /XEiAZjL0THb path when using Native Link feature `https://branchster-alternate.app.link/XEiAZjL0THb`

**Comment by RodrigoSMarques** [comment]
@AristideVB 

This plugin calls Branch Native SDK functions on each platform.

The problem reported is not in the Flutter plugin, but in the Native SDK.

Please open an issue in the platform repository:

- iOS: https://github.com/BranchMetrics/ios-branch-deep-linking-attribution

Or open a support ticket for Branch at the [link](https://help.branch.io/using-branch/page/submit-a-ticket)

**Comment by RodrigoSMarques** [comment]
But do you need the url? Can't you insert some data into the onboarding link to know if the user clicked on it?

**Comment by RodrigoSMarques** [comment]
Checking the Branch documentation, in the SDK return structure we have the "~referring_link" property.
Maybe it will return what you need.

[Data structure ](https://help.branch.io/using-branch/docs/creating-a-deep-link#data-structure)

**Comment by RodrigoSMarques** [comment]
@AristideVB 

see the example below.

You can use the code: 

```dart
inal Map<dynamic, dynamic> params = await FlutterBranchSdk.getFirstReferringParams();
```

``
<img width="1710" alt="Captura de Tela 2024-04-19 às 21 14 53" src="https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/17687286/f951eab9-834d-494a-918a-2bb2563f0772">

**Comment by AristideVB** [comment]
Hello @RodrigoSMarques thank you for you answer but I've still yet not had any response from the support team & in your example you are getting the generated NativeLink path `RXfpQBa5Vlb` and not your quick link path...
