### ISSUE TITLE
Issue with Branch.io Integration on Apple 14 pro

### ISSUE THREAD

**Issue by wdcs-nadimansari** [RodrigoSMarques/flutter_branch_sdk#314]
**Describe the bug**
The main issue I am facing is that the FlutterBranchSdk.listSession().listen() method, which is used to retrieve session data, does not seem to be triggering the onData callback consistently on iOS 14 devices. This prevents me from properly tracking user sessions and handling deep links within the app. I am facing this very unexpectedly, Sometimes I am not getting a callback of onData method inside FlutterBranchSdk.listSession().

`FlutterBranchSdk.listSession().listen(
    (data) async {
        // In some cases on Apple 14 Pro, this block is not triggering.
    }
);`

**Expected behavior**
The listen method must get called each time so app can listen Deep-link and take action on it.

**Smartphone (Please complete the following information. remove session if not platform):**
 - Flutter: version: 3.19.3
 - Package version: 7.3.0
 - OS: iOS 17.4.1
 - Device:  Apple 14 pro
 
 - **Additional context**

Deep-link is working well with Android and Apple 7 devices but i am facing issue with iOS 14 only.

**Comment by RodrigoSMarques** [comment]
Please provide more details.

In which cases the link does not work:
At installation? After the application installed?

Is the problem only on iOS 14.0? Would the iOS version be 14.5?

**Comment by wdcs-vivekmakvana** [comment]
Steps to reproduce :

- Run app in release mode on Apple device /// iOS version : 17.4.1
- Check deep-link with foreground and background its works fine.
- Now kill the app and navigate with the same link but `FlutterBranchSdk.listSession().listen` not triggering sometimes.

**Comment by RodrigoSMarques** [comment]
@wdcs-nadimansari 
Please downgrade to version 6.9.0 and give it a test.
Remember to comment out the call to the `FlutterBranchSdk.init()` method;

If it works, this problem is already being addressed in version 8.0 that will be available in the next few days.

It was a bug added in version 7.0.0

**Comment by wdcs-vivekmakvana** [comment]
@RodrigoSMarques 

I downgraded package to 6.9.0 and facing issue in Android now but In iOS its working fine.

Issue : Getting listen twice in `FlutterBranchSdk.initSession().listen` and also referred this documentation : https://help.branch.io/faq/docs/android-app-calls-branch-multiple-times-when-resuming
I have already followed this step.

**Comment by wdcs-vivekmakvana** [comment]
@RodrigoSMarques 

Downgraded package to 6.9.0 and in iOS its working fine But now I am facing issue regarding getting listen twice in Android.

`FlutterBranchSdk.initSession().listen`

Also followed this [document](https://help.branch.io/faq/docs/android-app-calls-branch-multiple-times-when-resuming).

**Comment by RodrigoSMarques** [comment]
> @RodrigoSMarques
> 
> I downgraded package to 6.9.0 and facing issue in Android now but In iOS its working fine.
> 
> Issue : Getting listen twice in `FlutterBranchSdk.initSession().listen` and also referred this documentation : https://help.branch.io/faq/docs/android-app-calls-branch-multiple-times-when-resuming I have already followed this step.

Ok. So the change that I will make available in the next few days will also solve the problem on IOS 14.

**Comment by wdcs-vivekmakvana** [comment]
We are facing issue in production, Can you please give us date for SDK release?

**Comment by RodrigoSMarques** [comment]
Hey guys.

Version 8.0.0 released.

Take the tests and report the results.

**Comment by wdcs-vivekmakvana** [comment]
Hello @RodrigoSMarques... Thank you for your support, Now its working fine.
