### ISSUE TITLE
getShortUrl throws Expected a value of type 'String', but got one of type 'NativeError'

### ISSUE THREAD

**Issue by gonzasosa** [RodrigoSMarques/flutter_branch_sdk#315]
Hello, Im having problems while creating short URLs on web platforms (iOS and Android works fine). The method throws the following error: 
`Error: Expected a value of type 'String', but got one of type 'NativeError'`

1. Setup `flutter_branch_sdk` for web
2. Create a short link calling `FlutterBranchSdk.getShortUrl()` (first time works fine)
3. Create a short link calling `FlutterBranchSdk.getShortUrl()` (again) 

**Expected behavior**
Create a short link on web platforms.

**Screenshots**
![Screenshot 2024-04-26 at 12 24 55](https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/66737000/91b650db-75a1-4269-afa8-e86be7bedcf4)
![Screenshot 2024-04-26 at 12 56 48](https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/66737000/d9f46069-2b79-4bcf-b7d9-4c2b5f7a056f)

**Web (please complete the following information. remove session if not platform):**
 - Flutter: version: 3.16.9
 - Package version: 7.3.0
 - OS: Mac
 - Browser: Chrome
 - Version 124.0.6367.61
 
**Additional context**
The `alias` I use to create the short link is the same in both executions, it looks like `booking/:bookingId`.

**Comment by RodrigoSMarques** [comment]
As described in the [documentation](https://github.com/RodrigoSMarques/flutter_branch_sdk?tab=readme-ov-file#create-link-reference-branchlinkproperties), the alias `parameter` must be unique.

![image](https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/17687286/45177fa9-3b8b-4abf-a69a-b9bb495d82d0)

If you comment out the `alias` parameter, is the link generated?


Perhaps the Branch Native SDK does not return an error when the link is generated in duplicate on iOS/Android and when generated on the Web an error is generated.

If you can do the test, but I will check.

**Comment by gonzasosa** [comment]
> As described in the [documentation](https://github.com/RodrigoSMarques/flutter_branch_sdk?tab=readme-ov-file#create-link-reference-branchlinkproperties), the alias `parameter` must be unique.
> 
> ![image](https://private-user-images.githubusercontent.com/17687286/326047754-45177fa9-3b8b-4abf-a69a-b9bb495d82d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxNTY0OTcsIm5iZiI6MTcxNDE1NjE5NywicGF0aCI6Ii8xNzY4NzI4Ni8zMjYwNDc3NTQtNDUxNzdmYTktM2I4Yi00YWJmLWE2OWEtYjliYjQ5NWQ4MmQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDE4Mjk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyYzQyMmJkNTliN2JkNGI4YjIzYWIwMmEzZTBjNjI2NDI4NWJmNjRkNmJhZDI2MzZiNTBlMmU1YWUxODM2ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NQn606KaDcNvo6YOWYVcXgDabMu_uoGEngLFgv7LtkY)
> 
> If you comment out the `alias` parameter, is the link generated?
> 
> Perhaps the Branch Native SDK does not return an error when the link is generated in duplicate on iOS/Android and when generated on the Web an error is generated.
> 
> If you can do the test, but I will check.

Thanks for the quick response!

After commenting out the alias it worked fine for all platforms 👍🏻 

I did try on iOS and Android with the same alias and the native SDK doesn't throw an error but instead returns successfully, but web does throw the error mentioned before. Hope this can help you to fix it.

Thanks for the great job, Im closing this issue.

**Comment by RodrigoSMarques** [comment]
Hi @gonzasosa 

I will do the test and report to Branch, which is responsible for the SDK, that there is a difference in behavior between the platforms.
