### ISSUE TITLE
Not getting link after fresh install

### ISSUE THREAD

**Issue by deepss1** [RodrigoSMarques/flutter_branch_sdk#316]
**Describe the bug**
initSession function does not execute for fresh install with version `7.3.0`

listSession with version `6.9.0` used to work well

And LATD does not return anything for 6.9.0 and 7.3.0 in release

**To Reproduce**
1. Uninstall the app
2. Click on a branch.io link
3. Install the app
4. `initSession` does not execute

**Expected behavior**
Expect the `initSession` to execute and get the link in the data with `first_session` as `true`

**Smartphone (Please complete the following information. remove session if not platform):**
 - Flutter: version: 3.13.9
 - Package version: 7.3.0
 - OS: iOS 17
 - Device: iPhone 13 mini, iPhone 15 Pro Max, iPhone 15, iPhone 13 Pro
 
 - **Additional context**

Things that I have tried to resolve the issue : 
1. Use 3 seconds delay for execute the initSession function
2. Use 3 seconds delay before trying to get the first ref params, and latest ref params
3. Tried asking for Tracking permission before trying to execute initSession
4. Ensured that the pasteboard permissions are added to Info.plist

Purpose : 
Get the link the app was installed with, or get the campaign id of the facebook ad via which the user was redirected to install the app.

To be noted : 
The function executes when trying to run for the second time

**Comment by RodrigoSMarques** [comment]
Hi @deepss1 

The problem has been identified and a new version will be released in the next few days.

From version 6.9 to 7.0, the SDK initialization was changed to allow the test key to be used via code via the `FlutterBranchSdk.init` function.

This change impacted the correct initialization of the SDK.

Version 8.0 will return the previous mode.

I will be grateful if you can help with testing.

**Comment by deepss1** [comment]
> Hi @deepss1 
> 
> The problem has been identified and a new version will be released in the next few days.
> 
> From version 6.9 to 7.0, the SDK initialization was changed to allow the test key to be used via code via the `FlutterBranchSdk.init` function.
> 
> This change impacted the correct initialization of the SDK.
> 
> Version 8.0 will return the previous mode.
> 
> I will be grateful if you can help with testing.

Thanks for confirming.

I can surely help with testing, loop me in when the version is ready.

Currently, I have made some changes in a forked version to initialise the old way.

On the iOS side, I only moved the `checkPasteboard` function to be executed as soon as the app starts and rest all resides in the `setupBranch` function and is initialised from the code.

This solved the issue for me.

**Comment by deepss1** [comment]
> @deepss1 
> 
> Version 8.0.0 released.
> 
> Take the tests and report the results.

Sure, I will be testing it out soon with iOS and share the results.
