### ISSUE TITLE
[iOS] - SDK not validating the credentials when FlutterBranchSdk.validateSDKIntegration() is called.

### ISSUE THREAD

**Issue by arthurgiani** [RodrigoSMarques/flutter_branch_sdk#317]
**Describe the bug**
When running FlutterBranchSdk.validateSDKIntegration() on the main app method, branch SDK is not being able to retrieve the proper credentials.

**To Reproduce**
1. Run FlutterBranchSdk.validateSDKIntegration()
2. See the screenshot below

**Expected behavior**

**Screenshots**
![Screenshot 2024-04-30 at 11 27 13](https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/45671820/10c0fb6f-dd71-4466-90a7-d1edf219e396)

![Screenshot 2024-04-30 at 11 40 43](https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/45671820/a15ea7df-1ab1-4244-b4d9-7416db6a5722)

**Smartphone (Please complete the following information. remove session if not platform):**
 - Flutter: version: [3.19.6]
 - Package version: [e.g. 7.3.0]
 - OS: [e.g. iOS17.4, iPhone 15 Pro Max]
 - Device: [iPhone 15 Pro Max]
 
 - **Additional context**

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.4.1 23E224 darwin-arm64, locale en-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.88.1)
[✓] Connected device (3 available)
[✓] Network resources

**Comment by RodrigoSMarques** [comment]
You need to validate the settings on the dashboard, as stated in the message.

Review the settings in INFO.PLIST

This package calls Branch Native SDK functions on each platform, the problem reported is not in the Flutter plugin, but in the Native SDK.

Please open an issue in the platform repository:

- iOS: [https://github.com/BranchMetrics/ios-branch-deep-linking-attribution](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution)
- Android: [https://github.com/BranchMetrics/android-branch-deep-linking-attribution](https://github.com/BranchMetrics/android-branch-deep-linking-attribution)

Or open a support ticket for Branch at the [link](https://help.branch.io/using-branch/page/submit-a-ticket)

**Comment by vasa137** [comment]
Hey @arthurgiani any luck with this?

**Comment by vasa137** [comment]
The solution which works for me is defining both keys in Info.plist. I have multiple app flavors so I wanted just to provider either test or live key based on flavor. Unfortunately, library will not work if you don't specify both keys, no matter which flavor you use.

![image](https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/12261779/02551f2e-bd9d-4294-9469-d86f0a68b3ad)
