### ISSUE TITLE
Troubleshooting implementation of Android SDK and Flutter SDK

### ISSUE THREAD

**Issue by cmurraye** [RodrigoSMarques/flutter_branch_sdk#319]
Shoprunner has made the updates requested however adding implementation *"com.google.android.gms:play-services-ads:17.2.0”* is causing their app to crash.  Please see the below response from the team.  Is someone available to get on a call to work through what's actually required?

Adding  implementation "com.google.android.gms:play-services-ads:17.2.0” is causing our app to crash – upon looking into the error further, it seems like we need to include meta data in our android manifest file. For example….
 
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="[com.yourpackage.name](http://com.yourpackage.name/)">
 
    <application
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name">
        
        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-xxxxxxxxxxxxxxxx~yyyyyyyyyy"/>
 
        
    </application>
</manifest>
 
 
However, I do not see this step in any of the branch documentation. This is our current app level build gradle dependency list
 
 
dependencies {
    implementation "io.branch.sdk.android:library:5.10.2"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation "com.google.android.gms:play-services-ads-identifier:18.0.1"
    implementation "com.google.android.gms:play-services-ads:17.2.0” ?--------- ADDING THIS CAUSED OUR APP TO CRASH
    implementation "com.google.android.gms:play-services-appset:16.0.2"
    implementation "com.squareup.okhttp3:okhttp:4.9.3"
    implementation "com.iterable:iterableapi:3.4.13"
    implementation "com.google.firebase:firebase-messaging:23.1.2"
}
 
Please see attached build gradle and android manifest files. The above line has since been removed in the actual file in order to resolve app crashes. If we could get on a call that would be great. The Branch documentation and whether or not to use the flutter SDK documentation or the android SDK documentation continues to be a bit confusing. There seems to be a lot of overlapping requirements between the two as opposed to ONE sdk documentation being the valid source of truth.

**Comment by RodrigoSMarques** [comment]
It is not necessary to perform any package installation procedures in the project, as the plugin [performs these steps](https://github.com/RodrigoSMarques/flutter_branch_sdk?tab=readme-ov-file#android-integration).

![image](https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/17687286/64be1ae7-4b9e-47c9-a727-39a8c68fa51c)

The plugin installs [com.google.android.gms:play-services-ads-identifier:18.0.1](https://github.com/RodrigoSMarques/flutter_branch_sdk/blob/3dbada4a073f31f9012585c8f232c56057423d69/android/build.gradle#L53)

The [Branch SDK for Android documentation says that using](https://help.branch.io/developers-hub/docs/android-basic-integration#2-install-branch) 'com.google.android.gms:play-services-ads:17.2.0' is an alternative if not using 'com.google.android.gms:play-services-ads -identifier:18.0.1'

It is not necessary to install both.

Either way, you don't need to worry about this as the plugin performs this installation.

**Comment by RodrigoSMarques** [comment]
applies when installing the Flutter plugin. 

it is the plugin that defines which version to use and the necessary dependencies. 

imagine the plugin is prepared for one version and you install another. 

the risk of incompatibility is great.
