### ISSUE TITLE
listener getting data 2 times in package - flutter_branch_sdk: ^6.9.0 operating system - android flutter - 3.19.6 device - samsung m30

### ISSUE THREAD

**Issue by DeekanshuSaini** [RodrigoSMarques/flutter_branch_sdk#330]
FlutterBranchSdk.initSession().listen((data) async {
print(data);
});
This method prints data 2 times whenever i click on deep link.

**Comment by DeekanshuSaini** [comment]
@RodrigoSMarques please review this asap.

**Comment by RodrigoSMarques** [comment]
What version of the package? Which Operating System? Which version of Flutter? Which device?

Fill in the issue opening template, otherwise it will be closed.

**Comment by DeekanshuSaini** [comment]
package - flutter_branch_sdk: ^6.9.0
operating system - android
flutter - 3.19.6
device - samsung m30

**Comment by RodrigoSMarques** [comment]
Did you test on version 8.0.2?

**Comment by RodrigoSMarques** [comment]
In `AndroidManifest.xml` the property `android:launchMode="singleTask" `?

**Comment by DeekanshuSaini** [comment]
not yet i have done the configuration according to the 6.9.0 as it fits compatible with the other libraries in my project. Can u please suggest any solution in this version.

**Comment by DeekanshuSaini** [comment]
In AndroidManifest.xml the property android:launchMode="singleTask" ?

yes we have done this.

**Comment by RodrigoSMarques** [comment]
I need log from Logcat for Android for analysis.

But if there is an error, the correction will be made in the newer version and not in 6.9.

**Comment by RodrigoSMarques** [comment]
> @RodrigoSMarques I faced something like this with version 7.1.0 and after added the `android:launchMode="singleTask"` it starts to work but only for debug mode in release mode doesn't work and when you print the data is showing this: `{+clicked_branch_link: false, +is_first_session: false}`

Update to the latest version 8.0.2

**Comment by E2-venkat** [comment]
Facing the same issue sometimes branch SDK listening for the link multiple times in both Android and ios @RodrigoSMarques flutter branch SDK version: 7.3.0

**Comment by RodrigoSMarques** [comment]
> Facing the same issue sometimes branch SDK listening for the link multiple times in both Android and ios @RodrigoSMarques flutter branch SDK version: 7.3.0

Update to the latest version 8.0.2

**Comment by mahee510** [comment]
The problem is not limited to Android. There is always an issue with this on both iOS and Android devices. For my project, I used flutter_branch_sdk: 7.3.0.

**Comment by RodrigoSMarques** [comment]
> @RodrigoSMarques The problem is not limited to Android. There is always an issue with this on both iOS and Android devices. For my project, I used flutter_branch_sdk: 7.3.0.

Update to the latest version 8.0.2

**Comment by mahee510** [comment]
> > @RodrigoSMarques The problem is not limited to Android. There is always an issue with this on both iOS and Android devices. For my project, I used flutter_branch_sdk: 7.3.0.
> 
> Update to the latest version 8.0.2

There is no indication in the change log that you are using version 8.0.2.
