### ISSUE TITLE
App not listen data on ios when app is killed.

### ISSUE THREAD

**Issue by UmerTaptap** [RodrigoSMarques/flutter_branch_sdk#335]
**Describe the bug**
Not Listening data in ios when app is killed.

**To Reproduce**
1. Close the app
2. Open the app through any branch io deep link.

**Expected behavior**
The app should listen to data and navigate to a specified screen.

**Smartphone (Please complete the following information. remove session if not platform):**
 - Flutter: version: [3.19.2]
 - Package version: [7.0.1]
 - OS: [iOS17.0,]
 - Device: [iPhone15 Pro Max]

**Comment by RodrigoSMarques** [comment]
Update to the latest available version (8.0.2).
Problem fixed in this version.
