### ISSUE TITLE
iOS 16 non_branch_link not work on flutter_branch_sdk: 8.0.2

### ISSUE THREAD

**Issue by sleepingkit** [RodrigoSMarques/flutter_branch_sdk#337]
**Describe the bug**
The issue appears to be specific to iOS 16, as iOS 15 and iOS 17 are working fine.

The value is not as expected when opening a deeplink while the app is killed or in the background.

Code:
```dart
FlutterBranchSdk.listSession().listen((value) {
});

FlutterBranchSdk.getFirstReferringParams().then((value) {
});
```

**Expected behavior**
The expected behavior is for the "non_branch_link" value to be equal to the deeplink.

**Smartphone:**
 - Flutter: version: 3.16.9
 - Package version: 8.0.2
 - OS: iOS16.6

**Comment by RodrigoSMarques** [comment]
I didn't understand the problem

**Comment by sleepingkit** [comment]
I don't know why, it works fine suddenly.
