### ISSUE TITLE
Changing the return value in didFinishLaunchingWithOptions crashes the application from SDK version above 8.0.0

### ISSUE THREAD

**Issue by klim-branch** [RodrigoSMarques/flutter_branch_sdk#338]
Hi @RodrigoSMarques this is Kun from the Branch integration team!

**Describe the bug**
When the customer make return value change in didFinishLaunchingWithOptions method of the AppDelegate class the app crashes without any logs on flutter-sdk-version >=8.0.0

**To Reproduce**
Change the return value to true didFinishLaunchingWithOptions method

`
@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    return true
  }
}
`

![image](https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/98570215/2248942b-8afe-44e8-b508-b18e0a79a687)

**Screenshots**

If you build an app with return true as mentioned above and click on a branch link ,  it would open the app and crash without any proper logs

Video Behaviour : 
https://drive.google.com/file/d/1mp3svEGk4ul9VHYHQuFzxtwRgLqthrll/view?usp=sharing

Example Testing Link used: 
https://musicwiki.app.link/Senhang
https://musicwiki.app.link/DRb6YE9a1Jb

**Additional Context**
- This issue is happening only from the SDK version above 8.0.0. Previous versions such as 7.1.0 does not appears to have this issue.

- From the netcore SDK, it is a requirement to return true. Therefore, there is no walkaround for this current solution.

- I will send out the testing code base via email. Let me know if you are okay with it.

Please let me know if you need anything from my end!

**Comment by RodrigoSMarques** [comment]
Hi @klim-branch 

I will check!

**Comment by RodrigoSMarques** [comment]
Hi @klim-branch 

New version available: 8.0.4

**Comment by klim-branch** [comment]
Amazing! Let me test from our side as well! @RodrigoSMarques I will share the update below.

**Comment by klim-branch** [comment]
Confirming the issue has been resolved! Thank you for the support @RodrigoSMarques.
