### ISSUE TITLE
Trouble initializing Branch.   Tracking is disabled. Requested operation cannot be completed when tracking is disabled

### ISSUE THREAD

**Issue by qirong-zhang-ext** [RodrigoSMarques/flutter_branch_sdk#339]
**Describe the bug**
Set disable tracking with true, then cold lunch the Android App, will get log like:
```shell
D/FlutterBranchSDK(27451): BranchReferralInitListener - error: Trouble initializing Branch.   Tracking is disabled. Requested operation cannot be completed when tracking is disabled
```

**To Reproduce**
1. call this on main function:
```dart
await FlutterBranchSdk.init();
FlutterBranchSdk.disableTracking(true);
```

2. call this when home page init:
```dart
void addBranchDeepLinkCallback() {
    FlutterBranchSdk.listSession().listen(
      handleBranchData,
      onError: (error) {
        _logService.sendLog(
          LEVEL.WARN,
          'FlutterBranchSdk InitSession error: $error',
        );
      },
    );
  }
```

3. Just start the app

**Expected behavior**
Should init sdk successfully without error log.

**Screenshots**

**Smartphone (Please complete the following information. remove session if not platform):**
 - Flutter: version: 3.16.9
 - Package version: 8.0.1 (Android device will not work for 8.0.2)
 - OS: Android 14
 - Device: Google Pixel 3a / 6a
 
 - **Additional context**
log detail:
```shell
D/FlutterBranchSDK(27451): triggered onActivityStarted: com.tomoloyalty.yuu.MainActivity
D/FlutterBranchSDK(27451): triggered SessionBuilder init
D/FlutterBranchSDK(27451): triggered onNewIntent
D/FlutterBranchSDK(27451): triggered onActivityResumed: com.tomoloyalty.yuu.MainActivity
D/FlutterBranchSDK(27451): triggered onInitFinished
D/FlutterBranchSDK(27451): BranchReferralInitListener - error: Trouble initializing Branch.   Tracking is disabled. Requested operation cannot be completed when tracking is disabled
I/flutter (27451): [4000] FlutterBranchSdk InitSession error: PlatformException(-117, Trouble initializing Branch.   Tracking is disabled. Requested operation cannot be completed when tracking is disabled, null, null)
```

**Comment by RodrigoSMarques** [comment]
I don't understand what you want.

The native Branch SDK on Android returns an error when the SDK is not successfully initialized.

The plugin is capturing this error and sending it to Flutter.

In Flutter, you capture the error and handle it according to your application's business logic.

The plugin cannot ignore the error and continue processing.

**Comment by qirong-zhang-ext** [comment]
Hi @RodrigoSMarques,

Thanks for your reply!

Just want to confirm if this error will block any functionality of Branch. But seems like this error throwed by native SDK instead of plugin.

Want to know if this error is an expected behavior when disabled the tracking?

Thanks again.

**Comment by qirong-zhang-ext** [comment]
Hi @RodrigoSMarques,

Thanks a lot for your information! 

Then I will close this issue.🫡
