### ISSUE TITLE
Andorid cannot open deeplink for 8.0.2

### ISSUE THREAD

**Issue by qirong-zhang-ext** [RodrigoSMarques/flutter_branch_sdk#341]
**Describe the bug**
Thanks a lot for your package, it helps us a lot. There is a issue may need your help.

All functions works well for version 8.0.1, after upgrade to version 8.0.2 Android cannot open the deeplink.

The case very similar to #325, the onInitFinish callback seems not be called, even though I add the `branch.json` file to Android project.

**Smartphone (Please complete the following information. remove session if not platform):**
 - Flutter: version: 3.16.9
 - Package version: 8.0.1 (Android device will not work for 8.0.2)
 - OS: Android 14
 - Device: Google Pixel 3a / 6a
 
 - **Additional context**
log detail:
```shell
D/FlutterBranchSDK(20233): triggered onAttachedToEngine
D/FlutterBranchSDK(20233): triggered setupChannels
D/FlutterBranchSDK(20233): SDK Init
D/FlutterBranchSDK(20233): triggered onAttachedToActivity
D/FlutterBranchSDK(20233): triggered setActivity
D/FlutterBranchSDK(20233): triggered onActivityStarted: com.tomoloyalty.yuu.MainActivity
D/FlutterBranchSDK(20233): triggered SessionBuilder init
D/FlutterBranchSDK(20233): triggered onActivityResumed: com.tomoloyalty.yuu.MainActivity
D/FlutterBranchSDK(20233): triggered setupBranch
D/FlutterBranchSDK(20233): notifyNativeToInit()
D/FlutterBranchSDK(20233): triggered setTrackingDisabled
D/FlutterBranchSDK(20233): triggered onAttachedToEngine
D/FlutterBranchSDK(20233): triggered setupChannels
D/FlutterBranchSDK(20233): SDK Init
D/FlutterBranchSDK(20233): triggered onListen

# move app to background
D/FlutterBranchSDK(20233): triggered onActivityPaused: com.tomoloyalty.yuu.MainActivity
D/FlutterBranchSDK(20233): triggered onActivityStopped: com.tomoloyalty.yuu.MainActivity

# click deeplink and back to app
D/FlutterBranchSDK(20233): triggered onActivityStarted: com.tomoloyalty.yuu.MainActivity
D/FlutterBranchSDK(20233): triggered SessionBuilder init
D/FlutterBranchSDK(20233): triggered onNewIntent
D/FlutterBranchSDK(20233): triggered onActivityResumed: com.tomoloyalty.yuu.MainActivity
```

Thanks a lot!

**Comment by RodrigoSMarques** [comment]
Hi @qirong-zhang-ext 

Remove the `branch.json` file from your project.

In issue #325, it was just an instruction to try to identify the problem. The SDK adds this file automatically, so it is not in the configuration instructions.

Has your default Activity in the Native code (Kotlin/Java) been changed? Does it use FlutterActivity or FlutterFragmentActivity?

I identified that you are using **DisableTracking**. I answered you in issue #339. In these scenarios, retrieving the deeplink data will not work.

**Comment by qirong-zhang-ext** [comment]
Hi @RodrigoSMarques, in case you know some root cause, could you please have a quick look for this issue from native side? https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution/issues/731

with `disableTracking` is `true`, it will work sometimes but sometimes not, thanks a lot for your help!

**Comment by RodrigoSMarques** [comment]
This is a behavior on the native side of the SDK.

I don't know if it is working.

I suggest you open an issue in the Android SDK repository: [https://github.com/BranchMetrics/android-branch-deep-linking-attribution](https://github.com/BranchMetrics/android-branch-deep-linking-attribution)

**Comment by RodrigoSMarques** [comment]
When you call disableTracking (true or false), this is persisted in some SharedPreferences of the Native SDK.

It takes effect after you restart the application. For this reason, when you opened the application it worked and after calling disableTracking and opening the application again it no longer works.

But the Branch team can give you accurate information.
