### ISSUE TITLE
Branch SDK asks for paste permission everytime the app is opened.

### ISSUE THREAD

**Issue by korzonkiee** [RodrigoSMarques/flutter_branch_sdk#345]
**Describe the bug**
Branch SDK asks for paste permission everytime the app is opened.

**To Reproduce**
1. Copy link.
2. Open the Flutter example app, see that it requests paste permission popup. 
3. Kill the app.
4. Copy link.
5. Open the Flutter example app, see that it requests paste permission popup again.  

**Expected behavior**
Branch SDK should only ask for paste permission after app was installed.

**Current behavior**
Branch SDK asks for paste permission everytime the app is opened.
 
**Screenshots**

| Step 1: Copy link | Step 2: Open app (permission request) | Step 3: Kill app | Step 4: Copy link | Step 5: Open app (permission request) |
| --- | --- | --- | --- | --- |
| ![CleanShot 2024-07-01 at 16 14 22@2x](https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/26259846/a3d53e07-a2e4-4b6e-834b-8e9cb8c823ce) | ![CleanShot 2024-07-01 at 16 14 22@2x](https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/26259846/a3d53e07-a2e4-4b6e-834b-8e9cb8c823ce) | ![CleanShot 2024-07-01 at 16 14 41@2x](https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/26259846/f0d7dffd-eb72-4e8b-bfbe-ebf54a63a269) | ![CleanShot 2024-07-01 at 16 13 57@2x](https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/26259846/ad0439e3-41f2-4c9d-93a4-979815612e33) | ![CleanShot 2024-07-01 at 16 14 22@2x](https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/26259846/a3d53e07-a2e4-4b6e-834b-8e9cb8c823ce) |

**Comment by RodrigoSMarques** [comment]
Please do not remove the additional information that is requested when opening the issue, otherwise your issue will be closed due to lack of detailed information.

Which package version? Which operating system version? Which Flutter version?

**Comment by RodrigoSMarques** [comment]
I ran the test with the sample application and I can't reproduce the problem. Clipboard authorization is only requested during installation.

The print below is the code instruction that requests authorization only during installation

<img width="1141" alt="image" src="https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/17687286/00a8d03a-d62b-4c55-8bda-51c210c21f39">

**Comment by korzonkiee** [comment]
> Please do not remove the additional information that is requested when opening the issue, otherwise your issue will be closed due to lack of detailed information.
> 
> Which package version? Which operating system version? Which Flutter version?

Hey @RodrigoSMarques, thank you so much for your reply. Sorry for not providing all the details right away.

**Smartphone (Please complete the following information. remove session if not platform):**
 - Flutter: version: 3.16.0
 - Package version: 8.0.2
 - OS: iOS 17.5.1
 - Device: iPhone 12 Pro

**Comment by korzonkiee** [comment]
> I ran the test with the sample application and I can't reproduce the problem. Clipboard authorization is only requested during installation.
> 
> The print below is the code instruction that requests authorization only during installation
> 
> <img alt="image" width="1141" src="https://private-user-images.githubusercontent.com/17687286/346248955-00a8d03a-d62b-4c55-8bda-51c210c21f39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MTk5OTAsIm5iZiI6MTcyMDQxOTY5MCwicGF0aCI6Ii8xNzY4NzI4Ni8zNDYyNDg5NTUtMDBhOGQwM2EtZDYyYi00YzU1LThiZGEtNTFjMjEwYzIxZjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDA2MjEzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxMzg5OTRlMTM0ZGRlYmQwYTQwMGE1NGE5NzdiMGZjZDQ3NWFiMmFlMWEyMTM2NGUyOGE1ZTY4MzI0ZWQwOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SVUuYQ-CR5huI28bZGqXAF_Ww5DHXYTr0i6wB_6kPJE">

Thanks for spending time to investigate this.

I skimmed through the code that you highlighted and it looks to me that this `checkPasteboardOnInstall` function gets called every time the app is opened because the [application(_:didFinishLaunchingWithOptions:)](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1622921-application) callback fires upon each app launch. I also verified that by setting a breakpoint in Xcode and launching the app a bunch of times.

Moreover, I checked what does the `checkPasteboardOnInstall` function do and it just sets the `checkOnInstall` flag to `YES`.

So if I understand correctly, every time the app is opened, the Flutter SDK tells the iOS Branch SDK to check the pasteboard.

---

Regarding your tests — are you sure you copy the link again before opening the app as described in my steps to reproduce section?

When I do the following:
1. Copy link.
2. Install app.
3. Get pasteboard permission prompt.
4. Tap "Allow paste".
5. Close app (swipe up to kill it).
6. Open app.

Then I am not getting the paste permission popup upon opening the app. See video [here](https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/26259846/b2cd8878-0b36-484d-8d84-c01191d9605c). 

However, when I do the following steps:
1. Copy link.
2. Install app.
3. Get pasteboard permission prompt.
4. Tap "Allow paste".
5. Close app (swipe up to kill it).
6. **Copy link.**
7. Open app.

Then I am getting the paste permission popup upon opening the app. See video [here](https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/26259846/0f515c6e-c18a-42a2-993a-8f2e371e9674).

**Comment by RodrigoSMarques** [comment]
This plugin follows the implementation guidelines of the Branch SDK for **checkPasteboardOnInstall**, which can be found [here](https://help.branch.io/developers-hub/docs/ios-advanced-features#basic-example)

This package calls Branch Native SDK functions on each platform.

The problem reported is not in the Flutter plugin, but in the Native SDK.

I suggest you open issue in the platform repository:

- iOS: [https://github.com/BranchMetrics/ios-branch-deep-linking-attribution](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution)
- Android: [https://github.com/BranchMetrics/android-branch-deep-linking-attribution](https://github.com/BranchMetrics/android-branch-deep-linking-attribution)

Or open a support ticket for Branch at the [link](https://help.branch.io/using-branch/page/submit-a-ticket)

**Comment by korzonkiee** [comment]
I just created an issue in the Branch iOS SDK repository: https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/issues/1412.

I will close this one.

Thanks @RodrigoSMarques!
