### ISSUE TITLE
Downgrade the JS plugin version from 0.7.1 to 0.6.7

### ISSUE THREAD

**Issue by pawanpal-branch** [RodrigoSMarques/flutter_branch_sdk#346]
In an app we are attempting to upgrade the Flutter SDK to the latest version, 8.0.3, to incorporate breaking changes in the SDK. During the upgrade, we encountered an issue with the JS version. Our SDK supports JS version 0.7.1 and above ([link](https://github.com/RodrigoSMarques/flutter_branch_sdk/blob/8a7ef32904fd247df7caeb4186236afee1925da5/pubspec.yaml#L16)). However, other third-party libraries used by the clients are not compatible with this latest version.

**Which problem is this feature request solving?**
Used by apps which has a dependency on older JS versions.

**Describe the solution you'd like**
Change the version to `^0.6.7`

**Comment by RodrigoSMarques** [comment]
Use `dependency_overrides` in `pubspec.yaml` to meet your project requirements.

```dart
dependency_overrides:
    js: ^0.6.7
```
