### ISSUE TITLE
crash on ios plugin v8.0.3

### ISSUE THREAD

**Issue by heshesh2010** [RodrigoSMarques/flutter_branch_sdk#347]
Hi , when I create share link on ios real device i got the attached error in xcode log

![Screenshot 2024-07-06 at 1 12 07 AM](https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/16393042/746f8e33-c97e-4edc-81bd-423a6056cdbb)

flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-x64, locale en-EG)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.90.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

**Comment by RodrigoSMarques** [comment]
Please do not remove the additional information that is requested when opening the issue, otherwise your issue will be closed due to lack of detailed information.

Which package version? Which operating system version? 

Did you call `FlutterBranchSdk.validateSDKIntegration()` in your project? Did the result return successfully?

From your screenshot, both the `error` and` ur`l variables are null. This condition should never occur.

Your project has some configuration error.

**Comment by heshesh2010** [comment]
> Please do not remove the additional information that is requested when opening the issue, otherwise your issue will be closed due to lack of detailed information.
> 
> Which package version? Which operating system version?
> 
> Did you call `FlutterBranchSdk.validateSDKIntegration()` in your project? Did the result return successfully?
> 
> From your screenshot, both the `error` and` ur`l variables are null. This condition should never occur.
> 
> Your project has some configuration error.

hi, 

running on plugin v8.0.3 
ios device v : 17.5.1 

Did you call `FlutterBranchSdk.validateSDKIntegration()` in your project? Did the result return successfully?
yes, see the screenshot 
![IMG_4667](https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/16393042/68e6eea4-e852-41dd-85ff-dd3e0b4d454f)

**Comment by RodrigoSMarques** [comment]
your project's uri scheme is strange. should be displayed as in the example

![image](https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/17687286/b5f44b74-c6b3-4211-866d-f01efd9cf8b1)

**Comment by heshesh2010** [comment]
Hi ,

It was working before and here is branch dashboard configs 

![image](https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/16393042/338e444f-1691-4a16-a622-26534242d707)

**Comment by RodrigoSMarques** [comment]
In my opinion, https is not a schema for an application. it should be the name of the Application or similar to the name. This may be causing an error in the branch's SDK. my first suggestion would be to review the Dashboard and project settings to change this.

**Comment by RodrigoSMarques** [comment]
If the problem persists after the change, you will have to open an issue with Branch. As the SDK is returning an error, only they can evaluate it.

**Comment by heshesh2010** [comment]
> If the problem persists after the change, you will have to open an issue with Branch. As the SDK is returning an error, only they can evaluate it.

changed the url scheme and I got same error

**Comment by RodrigoSMarques** [comment]
Code correction made to avoid crash if the URL is not returned

Available in version 8.0.4
