### ISSUE TITLE
Possiblity to retrieve initial Link Datas on first install/launch

### ISSUE THREAD

**Issue by chamartt** [RodrigoSMarques/flutter_branch_sdk#349]
**Which problem is this feature request solving?**

At the moment, we only have a listener `listSession` in order to get the Link Datas of a Quick Link.
That means that the app has to be openned once before clicking on the link, in order to catch the datas in the listener.

But, if the user don't have the app when he press the Quick Link, he's redirected on the Store, and when he opens the app for the first time, we don't have a way to retrieve datas of the initial link.

I openned a ticket (#00389220) with the Support Branch Team and made a video call, then they ask me to open en FR here.

**Describe the solution you'd like**

As Firebase Dynamic Links offers on the Flutter SDK, it would be useful to have a getInitialLink method, on order to get the link (and Link Datas associated) who actually redirect the user to the store (as the user could don't have the application when he press the link)

This is the Firebase methods we are using right now for this use case : https://firebase.google.com/docs/dynamic-links/flutter/receive#terminated_state

So, as you can see, they offers two ways to catch link, as you are offering only one:

- a Future method to get the initial link & datas
- a listener to be triggered when the user has already open the app once.

It could be amazing that you can integrate the first way as well, as Firebase Dynamic Links will shut down next year, a lot of customers will turn to you to continue to use Dynamic/Quick Links and achieve this extremly simple use-case.

**Can you submit a pull request?**

No.

Thank you in advance!

**Comment by RodrigoSMarques** [comment]
Hi @chamartt 

On the first launch of the app, the initial link data is made available in the `listSession` method.

On iOS you need to configure [NativeLink™ Deferred Deep Linking](https://help.branch.io/developers-hub/docs/ios-advanced-features#nativelink-deferred-deep-linking)

You can also retrieve the first link data via the [`FlutterBranchSdk.getFirstReferringParams`](https://github.com/RodrigoSMarques/flutter_branch_sdk?tab=readme-ov-file#retrieve-install-install-only-parameters) method.

**Comment by RodrigoSMarques** [comment]
@chamartt 

You can find an example of the data returned by getFirstReferringParams or listen [here](https://help.branch.io/using-branch/docs/creating-a-deep-link#reserved-prefixes).

You can find it for testing here:

- [https://help.branch.io/developers-hub/docs/ios-testing](https://help.branch.io/developers-hub/docs/ios-testing)
- [https://help.branch.io/developers-hub/docs/android-testing](https://help.branch.io/developers-hub/docs/android-testing)

You can do some testing using the sample application using the link below: 
[https://flutterbranchsdk.test-app.link/Bxr14Nm2jLb](https://flutterbranchsdk.test-app.link/Bxr14Nm2jLb)

**Comment by chamartt** [comment]
@RodrigoSMarques 

By test, I mean that I want to:
- Create Quick Link (with Link Datas)
- Uninstall my app
- Click on the link from my device
- Open my Flutter Project in Debug mode, in order to put some breakpoints in my code and check `getFirstReferringParams` & `listSession`

I tried to create link, uninstall my app, click on the link from my device, but even with `?bnc_validate=true` it opens the Play Store (so not my code)

Is there a way to do that ? Why is `?bnc_validate=true` used for ? What is the difference with a link without that ?

> You can find an structure of the data returned by getFirstReferringParams, getLatestReferringParams or listen [here](https://help.branch.io/using-branch/docs/creating-a-deep-link#reserved-prefixes).

I don't see any return exemple, only some reserved prefixes.

> You can do some testing using the sample application using the link below:
https://flutterbranchsdk.test-app.link/Bxr14Nm2jLb

This link does not seems to have Link Datas: when I press Get First Parameters, no datas are returned.

For the context, my use-case is extremly simple: create link with Link Datas in order to redirect users (who has app installed or not) to a specific page. 
That's why I need to catch the datas of the initial link (for the people who didn't have when they pressed the link) and test it on my VS Code project in order to redirect correctly depending the structure of the datas returned by `getFirstReferringParams`, `getLatestReferringParams `or `listSession`

Thanks in advance for your answer.

**Comment by RodrigoSMarques** [comment]
> @RodrigoSMarques
> 
> By test, I mean that I want to:
> 
> * Create Quick Link (with Link Datas)
> * Uninstall my app
> * Click on the link from my device
> * Open my Flutter Project in Debug mode, in order to put some breakpoints in my code and check `getFirstReferringParams` & `listSession`
> 
> I tried to create link, uninstall my app, click on the link from my device, but even with `?bnc_validate=true` it opens the Play Store (so not my code)
> 
> Is there a way to do that ? Why is `?bnc_validate=true` used for ? What is the difference with a link without that ?
> 

I have never performed installation tests with Android, only with iOS.

You may be able to test on Android this way:

adb shell am start -a android.intent.action.VIEW \
-c android.intent.category.BROWSABLE \
-d "https://flutterbranchsdk.test-app.link/MEYEwhnkMub"

Replace "https://flutterbranchsdk.test-app.link/MEYEwhnkMub" replace with your url.

> > You can find an structure of the data returned by getFirstReferringParams, getLatestReferringParams or listen [here](https://help.branch.io/using-branch/docs/creating-a-deep-link#reserved-prefixes).
> 
> I don't see any return exemple, only some reserved prefixes.
> 

Yes. That is the example of the structure returned. The data will depend on your application.

> > You can do some testing using the sample application using the link below:
> > https://flutterbranchsdk.test-app.link/Bxr14Nm2jLb
> 
> This link does not seems to have Link Datas: when I press Get First Parameters, no datas are returned.
> 

Yes, but if you click on Get Latest you will see the result similar to what you would see if you had clicked on Get First.

> For the context, my use-case is extremly simple: create link with Link Datas in order to redirect users (who has app installed or not) to a specific page. That's why I need to catch the datas of the initial link (for the people who didn't have when they pressed the link) and test it on my VS Code project in order to redirect correctly depending the structure of the datas returned by `getFirstReferringParams`, `getLatestReferringParams `or `listSession`
> 

The data that will be returned will be according to what you add.

The data that will be returned will be according to what you add to the `BranchUniversalObject` using the `addCustomMetadata` method.

Download the [sample application](https://github.com/RodrigoSMarques/flutter_branch_sdk/tree/master/example) and do some testing with it.
> Thanks in advance for your answer.

**Comment by RodrigoSMarques** [comment]
As I mentioned earlier.

If you have the `listen` method in your code, when the application is installed or when the user opens the application later, this method will always be called.

You don't need to worry about whether it is the first or last parameter. Write the code when listen is called.

This is how I handle it in my applications.

**Comment by chamartt** [comment]
Thank you for this complete answer !
