### ISSUE TITLE
Facing issue in using quick links to open the app for ios

### ISSUE THREAD

**Issue by Aswinjiitak** [RodrigoSMarques/flutter_branch_sdk#350]
Im using quick links to open app if not installed, in Android its working fine, but in the case of ios the app is not opening if the app is installed, instead of that while clicking the link it directly going to the safari 

Url schemes setup are done as per the instructions of the official docs, 

In main.dart the validation was success too, after validation success i removed the validationSdk method, now there is only init is called.

What should I do , is it a mistake from my side ?

**Comment by RodrigoSMarques** [comment]
Probably yes.

Some configuration in `INFO.PLIST` must be incorrect.

Have you validated the configuration with [`FlutterBranchSdk.validateSDKIntegration()`](https://github.com/RodrigoSMarques/flutter_branch_sdk?tab=readme-ov-file#test-branch-integration)?


Check the problems page for solutions [here](https://help.branch.io/developers-hub/docs/ios-troubleshooting#app-does-not-open)

**Comment by Aswinjiitak** [comment]
@RodrigoSMarques 
Yes i validated the configuration with FlutterBranchSdk.validatedSDKIntegration() and it was success, later i removed that, now only FlutterBranchSdk.init() is there in the main.dart.

May is it the problem of using quicklinks rather than generated link?

**Comment by RodrigoSMarques** [comment]
@Aswinjiitak 
Check the iOS Troubleshooting [here](https://help.branch.io/developers-hub/docs/ios-troubleshooting#app-does-not-open)

Also check out the instructions for testing on iOS [here](https://help.branch.io/developers-hub/docs/ios-testing)

**Comment by Aswinjiitak** [comment]
@RodrigoSMarques 
Sorry for asking again, I have a doubt again

The domain link passed the AASA validation,

The app is still not published on app store yet, we are testing the app using some other custom, so it also a reason for the issue im facing now?

**Comment by RodrigoSMarques** [comment]
> @RodrigoSMarques Sorry for asking again, I have a doubt again
> 
> The domain link passed the AASA validation,
> 
> The app is still not published on app store yet, we are testing the app using some other custom, so it also a reason for the issue im facing now?

The app does not need to be published to test.

Have you checked the instructions for testing on iOS?

**Comment by Aswinjiitak** [comment]
![IMG_0541](https://github.com/user-attachments/assets/5c6dc5bb-9a43-457e-a18d-f9ed865bc442)
Sometimes it shows a pop up like this to open the app @RodrigoSMarques 
Mostly it will not shows

**Comment by Aswinjiitak** [comment]
![IMG_0541](https://github.com/user-attachments/assets/6cb31510-5c27-4475-bb3f-24bf77fe1c59)
Sometimes this popup will come up to open the app, but mostly it wont come up @RodrigoSMarques

**Comment by RodrigoSMarques** [comment]
@Aswinjiitak 

This is a behavior of the native code or Branch SDK and not of the Flutter plugin.

In this case, I suggest you open an issue directly in the iOS repository about this issue.

- iOS: [https://github.com/BranchMetrics/ios-branch-deep-linking-attribution](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution)

Or open a support ticket for Branch at the [link](https://help.branch.io/using-branch/page/submit-a-ticket)

**Comment by Aswinjiitak** [comment]
@RodrigoSMarques 
This issue has been resolved by adding the redirection link for the quick links as web URLs, instead of adding it on the dashboard. Now the iOS redirection is working fine and perfectly.
<img width="314" alt="Screenshot 2024-07-18 at 9 17 09 AM" src="https://github.com/user-attachments/assets/3473b32e-6bee-40c9-b0d7-477d16033a03">

**Comment by Aswinjiitak** [comment]
@RodrigoSMarques  So, if we are using quick links then we should follow this, instead of using default urls setup on dashboard

**Comment by RodrigoSMarques** [comment]
> @RodrigoSMarques So, if we are using quick links then we should follow this, instead of using default urls setup on dashboard

I developed the Flutter plugin to call the Branch SDK.

I can't confirm how Branch services work.

I've never needed to add redirect URLs in my projects.

It may be a configuration issue in your project. Branch support can help you with this.

**Comment by Aswinjiitak** [comment]
@RodrigoSMarques  Hence the issue is fixed, so im closing this.
Thank You for the support!
