### ISSUE TITLE
Not able to correctly read deeplink in ios devices

### ISSUE THREAD

**Issue by rohnsht** [RodrigoSMarques/flutter_branch_sdk#354]
**Describe the bug**
I create a deeplink in branch which works properly with android. However, when I try to test the deep link in ios it doesn't treat the link as deeplink. I have added the log below:
` 
DeepLink Data: {+clicked_branch_link: false, +non_branch_link: https://gihui.test-app.link/sBSzHAHTtLb, +is_first_session: false}
`

**Expected behavior**
The app should recognise the above link as a branch_link

**Screenshot**
![IMG_0140](https://github.com/user-attachments/assets/b19ec7b1-aec3-4690-87b7-05b29ef8456c)

**Smartphone (Please complete the following information. remove session if not platform):**
 - Flutter: version: 3.22.3
 - Package version: 8.0.4
 - OS: ios 16.6
 - Device: iphone 8

**Comment by RodrigoSMarques** [comment]
@rohnsht 
Is your project's uri scheme `'<null>'`?

**Comment by RodrigoSMarques** [comment]
![image](https://github.com/user-attachments/assets/ba8f4656-75cd-45d9-9825-683e49741d7b)

**Comment by rohnsht** [comment]
@RodrigoSMarques 
I have added UriScheme in both branch dashboard and IosProject but it still says "<null>". I have no idea why this is hapenning.

**Comment by RodrigoSMarques** [comment]
this is related to your INFO.PLIST configuration. you should review it.

**Comment by rohnsht** [comment]
@RodrigoSMarques 

 This is the setup in INFO.PLIST for my project. Could you tell me what might be the issue? Thanks

`
<key>CFBundleURLTypes</key>
<array>
<dict>
	<key>CFBundleTypeRole</key>
	<string>Editor</string>
	<key>CFBundleURLName</key>
	<string>com.stampmedia.stampme</string>
	<key>CFBundleURLSchemes</key>
	<array>
		<string>stampme</string>
	</array>
</dict>
<dict>
	<key>CFBundleTypeRole</key>
	<string>Editor</string>
	<key>CFBundleURLSchemes</key>
	<array>
		<string>com.googleusercontent.apps.xxxxxxxxxx</string>
	</array>
</dict>
</array>
<key>branch_key</key>
<dict>
<key>live</key>
<string>key_live_xxxxxxxxxxx</string>
<key>test</key>
<string>key_test_xxxxxxxxxxxx</string>
</dict>
<key>branch_universal_link_domains</key>
<array>
<string>xxxx.app.link</string>
<string>xxxx-alternate.app.link</string>
<string>xxxx.test-app.link</string>
</array>
`

**Comment by RodrigoSMarques** [comment]
@rohnsht 

Visually, I did not find any problems with your configuration in INFO.PLIST. 

Also check the configuration of the [Associated Domains](https://help.branch.io/developers-hub/docs/ios-basic-integration#3-configure-associated-domains)


If the issue persists, I suggest opening a support ticket directly with Branch at the  [link](https://help.branch.io/using-branch/page/submit-a-ticket)

They can better support you with this configuration. It is not specific to Flutter but to the native layer.

**Comment by rohnsht** [comment]
I needed to add `Branch.setUseTestBranchKey(true)` in AppDelegate to use Branch Test Key which solved the issue. Thanks @RodrigoSMarques

**Comment by RodrigoSMarques** [comment]
> I needed to add `Branch.setUseTestBranchKey(true)` in AppDelegate to use Branch Test Key which solved the issue. Thanks @RodrigoSMarques
@rohnsht 

There is no need for you to add this directly in your native code.

You have instructions for that [here]( https://github.com/RodrigoSMarques/flutter_branch_sdk?tab=readme-ov-file#configuring-the-project-to-use-branch-test-key)
