### ISSUE TITLE
Data not being passed to Branch Listener on Android while app is in background 

### ISSUE THREAD

**Issue by ConnorDykes** [RodrigoSMarques/flutter_branch_sdk#360]
This only happens on Android in Release build . When I tap a Branch link while my app in in the background it opens the app but does not pass the data through . the Branch session listener is saying "+clicked_branch_link" = false. When I close the app completely the link will work fine and open the app and pass the data. The links works perfectly fine on iOS in release build and Android in debug but not in release.

**To Reproduce**

1. build android in release mode
2. put app in background 
3. click a branch link
4. no data passed 

**Expected behavior**
It should pas the data through to the app and +clicked_branch _link should be true

**Screenshots**

**Mobile (Please complete the following information. remove session if not Mobile):**

 - Flutter: version: [e.g. 2.2.3]
 - flutter_branch_sdk: ^7.1.0
 - Android 13
 -  Device: Samsung Galaxy A15. 
 

 - **Additional context**

**Comment by ConnorDykes** [comment]
I resolved the issue by updating to 8.1.0, sorry .

**Comment by preetpatel21** [comment]
i get the same issue it works in my debug app but when i release the app it's not working.

i am using 7.1.0
