### ISSUE TITLE
Migrate to dart:js_interop to support Webassamebly

### ISSUE THREAD

**Issue by hnvn** [RodrigoSMarques/flutter_branch_sdk#361]
**Which problem is this feature request solving?**

 Flutter recently support to run Flutter web in WebAssembly mode, in order to support this feature, Dart codes need to be migrated from `dart:html` and `package:js` to `package:web` and `dart:js_interop`.
https://docs.flutter.dev/platform-integration/web/wasm

**Describe the solution you'd like**

Re-write `lib/src/web/branch_js.dart` by using `dart:js_interop`

**Can you submit a pull request?**

Yes. I will create a PR for it

**Comment by RodrigoSMarques** [comment]
Available in Release 8.2.0
