### ISSUE TITLE
Unable to resolve host "api2.branch.io": No address associated with hostname

### ISSUE THREAD

**Issue by vladRudenua23** [RodrigoSMarques/flutter_branch_sdk#363]
Branch Networking Error: 
E/BranchSDK(26642): URL: https://api2.branch.io/v1/open
E/BranchSDK(26642): Response Code: -1
E/BranchSDK(26642): Response Message: 
E/BranchSDK(26642): Caught exception type: java.net.UnknownHostException
E/BranchSDK(26642): Retry number: 0
E/BranchSDK(26642): requestId: 
E/BranchSDK(26642): Final attempt: false
E/BranchSDK(26642): Object: io.branch.referral.network.BranchRemoteInterfaceUrlConnection@c9f3cd
E/BranchSDK(26642): Exception Message: Unable to resolve host "api2.branch.io": No address associated with hostname
E/BranchSDK(26642): Stacktrace: java.net.UnknownHostException: Unable to resolve host "api2.branch.io": No address associated with hostname

this issue only happens on Samsung s24 ultra 

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.5 23F79 darwin-arm64, locale ru-BY)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[!] Android Studio (version unknown)
    ✗ Unable to determine Android Studio version.
[✓] VS Code (version 1.84.2)
[✓] Connected device (5 available)
[✓] Network resources

! Doctor found issues in 1 category.

**Comment by RodrigoSMarques** [comment]
When opening an issue, fill in all the requested information.

Do not delete any sessions. Without this information, it is not possible to analyze the problem in detail and reproduce it.


This package calls Branch Native SDK functions on each platform.

The problem reported is not in the Flutter plugin, but in the Native SDK.

Please open an issue in the platform repository:

- iOS: [https://github.com/BranchMetrics/ios-branch-deep-linking-attribution](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution)
- Android: [https://github.com/BranchMetrics/android-branch-deep-linking-attribution](https://github.com/BranchMetrics/android-branch-deep-linking-attribution)

Or open a support ticket for Branch at the [link](https://help.branch.io/using-branch/page/submit-a-ticket)
