### ISSUE TITLE
Branch io link does not listen when called from telegram in-app browser

### ISSUE THREAD

**Issue by RizwanAhmed11** [RodrigoSMarques/flutter_branch_sdk#374]
Keep the template and provide all requested information:

**Describe the bug**
i receive a deep link of branch io through telegram after clicking, it does open the app but does not get the data, it seems like it does no listen to the link data because of the telegram in-app browser.  but if i open it in google chrome or any other browser it does work fine. In short The `.listen` is not getting triggered with proper data from Telegram in-app browser

**To Reproduce**
1. click the branch io link from telegram while in-app browser is ON

**Expected behavior**
when in-app browser is On from telegram it should behave same as link is been called from google chrome

**Mobile (Please complete the following information. remove session if not Mobile):**
 - Flutter: 3.19.0
 - flutter_branch_sdk version: ^8.0.2
 - OS: any android version
 - Device: any

**Comment by RodrigoSMarques** [comment]
This behavior has nothing to do with the plugin. I believe it is some configuration in your project. No problem here.

https://github.com/user-attachments/assets/8e1c503f-873b-4581-93f2-2bab9219b7cf

**Comment by RizwanAhmed11** [comment]
The issue is in Android, iOS works fine. The app does open but the `.listen` not called and this condition never match
`if (data.containsKey('+clicked_branch_link') && data['+clicked_branch_link'] == true)`

**Comment by RodrigoSMarques** [comment]
> @RodrigoSMarques The issue is in Android side, iOS works fine. The app does open but the `.listen` not called and this condition never match `if (data.containsKey('+clicked_branch_link') && data['+clicked_branch_link'] == true)`

the plugin is not receiving the call from the Native SDK.

So the problem is in the SDK and not in the plugin.

I suggest opening an issue in the Android Branch repository.

* Android: [https://github.com/BranchMetrics/android-branch-deep-linking-attribution](https://github.com/BranchMetrics/android-branch-deep-linking-attribution)

**Comment by RodrigoSMarques** [comment]
Issue closed. I identified the open issue in the Branch SDK Android repository.
