### ISSUE TITLE
Better exception types for handling exception and errors

### ISSUE THREAD

**Issue by E2-Mahendran** [RodrigoSMarques/flutter_branch_sdk#378]
It is recommended to ensure that only PlatformExceptions are thrown for any exceptions. It throws more specific exceptions for improved error handling. For instance, when encountering internet connection issues, consider throwing a **_SocketException_** instead of a **_PlatformException_**. Similarly, employing a custom **_InvalidLink_** exception for handling invalid links would contribute to better exception tracking and management.

**Comment by RodrigoSMarques** [comment]
@E2-Mahendran 

All PlatformExceptions are returned from an exception generated by the Branch SDK.

I do not have a map of all possible errors that the Branch SDK can return, so it is not possible to categorize them.

That is why the plugin will always return a PlatformException

**Comment by E2-Mahendran** [comment]
Thank you for your response.
