### ISSUE TITLE
Opening from text message does not work

### ISSUE THREAD

**Issue by smedic** [RodrigoSMarques/flutter_branch_sdk#38]
I am trying to open link sent in text message:

I see it like `http://<name>.app.link/<ID>`
when I open it by using test app, I see something like this (pressing getLastParameters)

`{ +clicked_branch_link: false, +is_first_session: false, +non_branch_link: <name>://google/link/?dismiss=1&is_weak_match=1}`

Any idea what is happening here?
One more question: how to set **setUseTestBranchKey** ?
I did that in iOS but it doesn't help.. 

Also listen() is never called... Nor error..

Thanks!

**Comment by RodrigoSMarques** [comment]
Hi @smedic 
Are you using iOS? Am I right?

I used it via SMS and I had no problems. Try a test using Notes.
You cannot use setUseTestBranchKey.
You need to update the Info.plist file to place the test key.
The guidance is here: https://github.com/RodrigoSMarques/flutter_branch_sdk#ios-integration
Try calling: FlutterBranchSdk.validateSDKIntegration ();
If there is an integration error it will be demonstrated.

**Comment by smedic** [comment]
I am using both Android and iOS. For now, checking in iOS.
Everything is set, worked in iOS Branch.io, but now I am switching to Flutter and cannot make it work.

Now, when I open link mentioned above, I check getLastParameters and again, same message...
FlutterBranchSdk.validateSDKIntegration ()
this passes fine. Also adding bnc_validate= true says it is invitation link..

Check this out.. How to extract deep link value from this?
Why listen is never called ? 
![IMG_4009](https://user-images.githubusercontent.com/10304831/88457378-20d52300-ce86-11ea-94d9-ed589a472c86.PNG)

**Comment by smedic** [comment]
Found it, identity field. I am blind! Thanks for this great library! Starred

**Comment by smedic** [comment]
@RodrigoSMarques When I open app from SMS, I can see code. But when I close app, uninstall it, and start it from Xcode or by selecting from the menu, I can fetch params with FlutterBranchSdk.getFirstReferringParams(); again.
Why is that? I haven't clicked on text message. 
How to get only on link click?

**Comment by smedic** [comment]
What is the proper flow for getting 'identity' of a person that has sent invitation to someone?
I think that getFirstReferringParams is not proper method.

**Comment by RodrigoSMarques** [comment]
Hi @smedic 

Sorry for the delay to reply.
My mac is in trouble and I'm out of a computer this weekend.
Which version of iOS are you testing?

The best parameter is FlutterBranchSdk.getFirstReferringParams ()

When you use FlutterBranchSdk.setIdentity, Branch internally creates the invitation relationship, but I don't know if you can get this information.

I suggest that you use an addCustomMetadata to put the user id in the share link and then retrieve this metadata.

Tests on iOS are more complex to run. Read the guidelines on this page: https://help.branch.io/developers-hub/docs/ios-testing

I suggest you do the tests on Android devices.
Install the APK without opening the app, then open the app using the share link.

**Comment by smedic** [comment]
Thanks for reply! 
I wonder why to use getFirstReferringParams instead of getLatestReferringParams?
If I enter the app by clicking on 1 invitation link, and then close the app, click on another invitation link, first link will be saved if we use getFirstReferringParams, but we need second one.

**Comment by RodrigoSMarques** [comment]
Hi @smedic 
If the valid invitation is always from the last click, then use getLatestReferringParams ().

It depends on what you want.
