### ISSUE TITLE
Link not working [Google console]

### ISSUE THREAD

**Issue by PhuCG** [RodrigoSMarques/flutter_branch_sdk#380]
**Describe the bug**
I deploy a production version to google console and they reported that the domains when configured were not working.

**To Reproduce**
1. Setup like docs
2. Test on device Live and Test [Working]
3. Check with `.well-known/assetlinks.json` [Working]
4. Check on https://developers.google.com/digital-asset-links/tools/generator [Working]

But, when i just open link domain page result is not found. 

**Screenshots**
![Untitled design](https://github.com/user-attachments/assets/b360ea58-cb95-418a-8b16-2429ff13b3cf)
![Screenshot 2024-09-17 at 10 14 26](https://github.com/user-attachments/assets/cdff0701-b6c8-4cd8-a52c-4d0286d3f055)

**Mobile (Please complete the following information. remove session if not Mobile):**
 - Flutter: version: 3.24.2
 - flutter_branch_sdk version: 7.1.0

**Comment by RodrigoSMarques** [comment]
This package calls Branch Native SDK functions on each platform.

The problem reported is not in the Flutter plugin, but in the Native SDK.

Please open an issue in the platform repository:

- iOS: [https://github.com/BranchMetrics/ios-branch-deep-linking-attribution](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution)
- Android: [https://github.com/BranchMetrics/android-branch-deep-linking-attribution](https://github.com/BranchMetrics/android-branch-deep-linking-attribution)

Or open a support ticket for Branch at the [link](https://help.branch.io/using-branch/page/submit-a-ticket)
