### ISSUE TITLE
Facebook App "App not linked to Ad Partner"

### ISSUE THREAD

**Issue by FantaMagier** [RodrigoSMarques/flutter_branch_sdk#383]
Hey, I have installed and used Branch.io correctly. I also receive the first events in the meta dashboard such as installation and usage. But when I want to use an ad for app installs and select my app in the Play Store, it always says "App not linked to the advertising network" like with all other apps. I have already linked the data source to my network but even that doesn't change anything. What else do I need to set?

**Comment by RodrigoSMarques** [comment]
This package calls Branch Native SDK functions on each platform.

The problem reported is not in the Flutter plugin, but in the Native SDK.

Open a support ticket for Branch at the [link](https://help.branch.io/using-branch/page/submit-a-ticket) or open an issue in the platform repository:

- iOS: [https://github.com/BranchMetrics/ios-branch-deep-linking-attribution](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution)
- Android: [https://github.com/BranchMetrics/android-branch-deep-linking-attribution](https://github.com/BranchMetrics/android-branch-deep-linking-attribution)
