### ISSUE TITLE
App crashed when open ios with link on cold state

### ISSUE THREAD

**Issue by tkddbf7348** [RodrigoSMarques/flutter_branch_sdk#384]
The same phenomenon as issue #382  is happening in ios. In my case, I see the issue even in release mode.

**Comment by tkddbf7348** [comment]
It works well when you click on a link in Gmail.

Links pressed in places like messenger app (ex: kakaotalk in South Korea) do not turn on the app (App scheme)

The configuration settings are the same as issue 382.

**Comment by RodrigoSMarques** [comment]
When opening an issue, fill in all the requested information.

Do not delete any sessions. 

Without this information, it is not possible to analyze the problem in detail and reproduce it.

If the requested information is not provided, the issue will be closed.

**Comment by RodrigoSMarques** [comment]
> It works well when you click on a link in Gmail.
> 
> Links pressed in places like messenger app (ex: kakaotalk in South Korea) do not turn on the app (App scheme)
> 
> The configuration settings are the same as issue 382.


Expected behavior on each app and platform.

https://help.branch.io/using-branch/docs/creating-a-deep-link#expected-link-behavior

**Comment by tkddbf7348** [comment]
Thank you for your response, I didn't find the link you provided.
First of all, I'll keep the issue closed.
Is there a way to handle it in case you automatically enter a link in the browser from the web view like KakaoTalk?

**Comment by RodrigoSMarques** [comment]
> @RodrigoSMarques Thank you for your response, I didn't find the link you provided.
> First of all, I'll keep the issue closed.
> Is there a way to handle it in case you automatically enter a link in the browser from the web view like KakaoTalk?
> The app opens right after you go to DeepView, so I don't know what to do.

This package calls Branch Native SDK functions on each platform.

I suggest you open a support ticket for Branch at the [link](https://help.branch.io/using-branch/page/submit-a-ticket):

This is a question about the Branch SDK and not about this plugin in Flutter.

They will be able to guide you better.
