### ISSUE TITLE
Call DisableTracking after FlutterBranchSdk.init

### ISSUE THREAD

**Issue by DouglasCeron** [RodrigoSMarques/flutter_branch_sdk#385]
Keep the template and provide all requested information:

**Describe the bug**

I am using a third party that handles user consent preferences enabling or disabling all libs I have in the project.
After opening the app I can see this on the logs
`flutter: 'package:flutter_branch_sdk/src/flutter_branch_sdk_method_channel.dart': Failed assertion: line 77 pos 12: 'isInitialized': Call `disableTracking` after `FlutterBranchSdk.init()` method`. 

I am setting false when calling the FlutterBranchSdk.disableTracking(false) method, which is acceptable, following the Branch documentation. 

[Branch Doc](https://help.branch.io/developers-hub/docs/flutter-sdk-full-reference#disabletracking)

And, on the fix version 8.0.2, It looks like it was solved:
`🐛 Bug Fixes 
Fix Enable and Disable Tracking on FlutterBranchSdk.init() method`

**To Reproduce**
1. Initialize the BanchSdk
2. call FlutterBranchSdk.disableTracking(false) setting 'false' as param
3. The log will display '`flutter: 'package:flutter_branch_sdk/src/flutter_branch_sdk_method_channel.dart': Failed assertion: line 77 pos 12: 'isInitialized': Call `disableTracking` after `FlutterBranchSdk.init()` method`. '

**Expected behavior**
Not having this error on the log after calling the FlutterBranchSdk.disableTracking() method

**Mobile (Please complete the following information. remove session if not Mobile):**
 - Flutter: version: 3.24.0 - channel stable
 - flutter_branch_sdk version: 8.2.0
 - OS: MacOS 14.2
 - Device: [iPhone14]
 

 - **Additional context**

**Comment by RodrigoSMarques** [comment]
The `FlutterBranchSdk.disableTracking` method must be called after initialization, i.e. after calling await `FlutterBranchSdk.init()`.

From the message and my test, you are calling first.

Incorrect
```dart
  FlutterBranchSdk.disableTracking(true);
  await FlutterBranchSdk.init(enableLogging: true, disableTracking: false);
```

Correct
```dart
  await FlutterBranchSdk.init(enableLogging: true, disableTracking: false);
  FlutterBranchSdk.disableTracking(true);
```

or

```dart
  await FlutterBranchSdk.init(enableLogging: true, disableTracking: true);
```

**Comment by DouglasCeron** [comment]
You are right. 
Thanks again
