### ISSUE TITLE
FlutterBranchSdk.initSession().listen never called

### ISSUE THREAD

**Issue by smedic** [RodrigoSMarques/flutter_branch_sdk#39]
Should FlutterBranchSdk.initSession().listen be called at app startup?

I am using your lib for a while, and for some reason, it's not reliable. Sometimes I get referrerId in Flutter project, sometimes I don't. 
I use getFirstReferringParams and getLatestReferringParams. Both, because sometimes getFirstReferringParams does not return anything.

I try to fetch the ID in main app class. I saw some conversations about that, and they say it's too early, or we should wait for 'listen' in branch.io but my listen is never called.

Thanks!

**Comment by RodrigoSMarques** [comment]
Hi @smedic .

Are you testing on iOS or Android? Which version?

I have an application published with the plugin and using it without any problem.

I developed the sample app that is complete and functional. You can simply run it without any changes to test.

**Comment by smedic** [comment]
I tried and it works. 
But in my app, initSession is never called in iOS. In Android, it gets called
If I leave the app without killing, in next session I see identity acquired from invitation link.

**Comment by RodrigoSMarques** [comment]
Let me ask you again: What version of iOS and Android?

Is your ios app published? Did you make all the settings for iOS on the Dashboard?



Video of a Flutter project running on iOS 

https://youtu.be/TajSpOUkmvs <https://youtu.be/TajSpOUkmvs>

Retrieves the parameters in foreground and background. No problem.


In my BaseScreen():

class BaseScreen extends StatefulWidget {
  @override
  _BaseScreenState createState() => _BaseScreenState();
}

StreamSubscription<Map> streamSubscriptionDeepLink;

class _BaseScreenState extends State<BaseScreen>
    with SingleTickerProviderStateMixin {

@override
void initState() {
  super.initState();
  listenDynamicLinks();
}

void listenDynamicLinks() async {
  streamSubscriptionDeepLink = FlutterBranchSdk.initSession().listen((data) {
    print('listenDynamicLinks - DeepLink Data: $data');
    if (data.containsKey('+clicked_branch_link') &&
        data['+clicked_branch_link'] == true) {
      if (data.containsKey('TIPO') && data['TIPO'] == 'ESTABEL') {
        getDataEstabelecimento((data['ESTABELECIMENTO']));
      }

      if (data.containsKey('TIPO') && data['TIPO'] == 'PROMO') {
        getDataPromocao(data['CATEGORIAID'], data['PROMOCAOID']);
      }

      if (data.containsKey('TIPO') && data['TIPO'] == 'CATEGORIA') {
        getDataCategoria(data['CATEGORIA_CODIGO'], data['CATEGORIA_TITULO']);
      }
    }
  }, onError: (error) {
    PlatformException platformException = error as PlatformException;
    print(
        'InitSession error: ${platformException.code} - ${platformException.message}');
  });
}

@override
void dispose() {
  super.dispose();
  streamSubscriptionDeepLink.cancel();
}

Whenever the link is clicked, the listenDynamicLinks method is called and I can retrieve the parameters.

With the app in background or foreground, the method will always be called and retrieve the link data

**Comment by smedic** [comment]
This work flawlessly in full Flutter project, but I have iOS project with package in Flutter. 
Looks like that is the source of my issue.

Thanks for help!
