### ISSUE TITLE
Branch io does not give values if we open a link from telegram or any other messenger

### ISSUE THREAD

**Issue by Alex-esc1** [RodrigoSMarques/flutter_branch_sdk#395]
Keep the template and provide all requested information:

**Describe the bug**
When following a Branch link via Telegram or other messengers, the app receives incorrect data from the URL. Instead of a clean, user-friendly URL, the app gets a URL with a long, encoded query string like:
example://open/?_branch_referrer=H4sIAAAAAAAAA8soKSkottLXT8rMycmtTErMy9YrSS0u0U0sKNDLyczL1s9Nj3QxKg6qSgpIso+PTypKzEvOiE/LyS+Pz0yxNTS2NDEzsjA3NTMwMzM2NrY0M1CrK0pNSy0qysxLB6rOLy9OLbJ1zijKz00FANNNFaZrAAAA&link_click_id=1394595892493711698

However, if the same link is opened through a browser, the app receives the correct link as expected, such as:
https://pay-stage.example.com/c/YM535M?_branch_match_id=1387758733193324537&_branch_referrer=H4sIAAAAAAAAA8soKSkottLXT8rMycmtTErMy9YrSS0u0U0sKNDLyczL1i9M8Qnyd3F0TQpIsq8rSk1LLSrKzEuPTyrKLy9OLbJ1zijKz00FADLKQkJGAAAA

Additionally, if the app is closed and reopened, the Branch SDK processes the links correctly.

**To Reproduce**

1. Send a Branch link via Telegram (or any other messenger) to a mobile device.
2. Tap the link to open it in the app.
3. Observe the URL received by the app.
4. Close and reopen the app.
5. Observe that the correct URL is now processed.

**Expected behavior**
When the app is launched via a Branch link, the app should receive the clean, user-friendly link in the form:
https://pay-stage.example.com/c/YM535M
The link should be the same whether it is opened through a browser or a messenger.

**Screenshots**

**Mobile (Please complete the following information. remove session if not Mobile):**
 - Flutter: version: [3.24.5]
 - flutter_branch_sdk version: [8.2.0]
 - OS: [e.g. iOS18.0, Android 15]
 - Device: [iPhone15, Google Pixel]
 
 - **Additional context**

This issue only occurs when launching the app via a Branch link from a messenger (like Telegram).
The issue does not occur when launching via a browser.
Closing and reopening the app allows Branch to correctly process the link.
The incorrect URL contains an encoded _branch_referrer and link_click_id, while the expected URL is clean.
This bug may be related to how the Branch SDK handles deferred deep linking or link processing during cold starts when launched from third-party apps like messengers.

**Comment by RodrigoSMarques** [comment]
When opening an issue, fill in all the requested information.

Do not delete any sessions. 

Without this information, it is not possible to analyze the problem in detail and reproduce it.

If the requested information is not provided, the issue will be closed.

**Comment by RodrigoSMarques** [comment]
Note that one is a URI schemes and the other is a Universal Links/App Links that direct to the same content.

**Comment by Alex-esc1** [comment]
@RodrigoSMarques I've filled in the details

**Comment by RodrigoSMarques** [comment]
@Alex-esc1 

This package calls Branch Native SDK functions on each platform.

The problem reported is not in the Flutter plugin, but in the Native SDK.

Open a support ticket for Branch at the [link](https://help.branch.io/using-branch/page/submit-a-ticket) or open an issue in the platform repository:

- iOS: [https://github.com/BranchMetrics/ios-branch-deep-linking-attribution](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution)
- Android: [https://github.com/BranchMetrics/android-branch-deep-linking-attribution](https://github.com/BranchMetrics/android-branch-deep-linking-attribution)


Note:
I identified [this issue](https://github.com/BranchMetrics/android-branch-deep-linking-attribution/issues/1217) and it was opened. I believe it is the same problem reported by you.

**Comment by Alex-esc1** [comment]
@RodrigoSMarques, Thank you, I'm closing the ticket then
