### ISSUE TITLE
Issue creating shortlink with Branch SDK in offline mode on Android

### ISSUE THREAD

**Issue by PhuCG** [RodrigoSMarques/flutter_branch_sdk#396]
I'm experiencing an issue while using flutter_branch_sdk to create shortlinks in my Flutter application. The problem occurs when the application is offline on Android emulator.

**Development Environment:**
Flutter version: `3.24.5`
Branch SDK version: `8.0.2`
Device: `Android Emulator (API 34)`
Operating System: `macOS 14.5`

**Detailed Description:**
When I try to create a shortlink using FlutterBranchSdk.getShortUrl, the application fails to generate the link when there's no network connection. I've checked issue #237 on GitHub and noticed that this issue was reported and marked as fixed. However, I'm still experiencing this issue with the current SDK version.

**Steps to Reproduce:**
1. Run the application on Android emulator
2. Disconnect network on the emulator
3. Call FlutterBranchSdk.getShortUrl function
4. Observe that the shortlink is not generated

**Expected Behavior:**
The application should be able to create shortlinks even without network connection, or at least not encounter serious errors.

**Additional Information:**
I have updated to the latest version of flutter_branch_sdk
The issue doesn't occur when network connection is available
Looking forward to receiving support from the development team to resolve this issue. Thank you!

**Comment by RodrigoSMarques** [comment]
Hi
Enablel log in the `init` method and check what message is displayed in the console.

**Comment by RodrigoSMarques** [comment]
I tested it here and as expected, it generated a long link with all the parameters in the URL

```
2024-12-10 11:57:58.808  7000-7000  BranchSDK               br....es.flutter_branch_sdk_example  V  onPostExecuteInner io.branch.referral.ServerRequestQueue$BranchPostTask@af637b0 io.branch.referral.ServerResponse@1ed8629
2024-12-10 11:57:58.808  7000-7000  BranchSDK               br....es.flutter_branch_sdk_example  V  onRequestFailed Unable to resolve host "api2.branch.io": No address associated with hostname
2024-12-10 11:57:58.813  7000-7000  FlutterBranchSDK        br....es.flutter_branch_sdk_example  D  Branch link to share: https://flutterbranchsdk.test-app.link?%24randomized_bundle_token=1357160584130684996&tags=one&tags=two&tags=three&channel=share&feature=sharing&stage=new+share&campaign=campaign&type=0&duration=0&source=android&data=eyIkb2dfdGl0bGUiOiJGbHV0dGVyIEJyYW5jaCBQbHVnaW4gLSAyMDI0LTEyLTEwIDExOjU3OjU1IiwiJGNhbm9uaWNhbF9pZGVudGlmaWVyIjoiZmx1dHRlclwvYnJhbmNoXzk4ZDhlYWFjLTJiZDktNGU5Zi05NWI1LTllZTIwNGYyNzk1MiIsIiRrZXl3b3JkcyI6WyJQbHVnaW4iLCJCcmFuY2giLCJGbHV0dGVyIl0sIiRvZ19kZXNjcmlwdGlvbiI6IkZsdXR0ZXIgQnJhbmNoIERlc2NyaXB0aW9uIC0gMjAyNC0xMi0xMCAxMTo1Nzo1NSIsIiRvZ19pbWFnZV91cmwiOiJodHRwczpcL1wvcmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbVwvUm9kcmlnb1NNYXJxdWVzXC9mbHV0dGVyX2JyYW5jaF9zZGtcL21hc3RlclwvYXNzZXRzXC9icmFuY2hfbG9nb19xcmNvZGUuanBlZyIsIiRleHBfZGF0ZSI6IjE3NjUzNzg2NzU2NTEiLCIkcHVibGljbHlfaW5kZXhhYmxlIjoidHJ1ZSIsImN1c3RvbV9udW1iZXIiOiIxMjM0NSIsImN1c3RvbV9pbnRlZ2VyIjoiMCIsImN1c3RvbV9kb3VibGUiOiIwLjAiLCIkaW9zX25hdGl2ZWxpbmsiOiJ0cnVlIiwiJHVyaV9yZWRpcmVjdF9tb2RlIjoiMSIsIiRtYXRjaF9kdXJhdGlvbiI6IjcyMDAifQ%3D%3D
2024-12-10 11:57:58.818  7000-7000  BranchSDK               br....es.flutter_branch_sdk_example  V  processNextQueueItem onPostExecuteInner


```

**Comment by PhuCG** [comment]
Thank you for your response. However, I need to clarify my issue:
The problem is specifically about generating a short link, not a long link. While the SDK does generate a long link in offline mode as you demonstrated, my requirement is to get a short link using `getShortUrl()`.

**To be more specific:**

1. When online, `getShortUrl(`) correctly returns a short link (like https://xxxx.app.link/abcd123)
2. When offline, instead of getting a short link, it returns a long URL with parameters
According to issue #237, there was a fix for offline short link generation. However, in my testing with version 8.0.2, I'm still unable to get short links when offline.
As requested, here are the logs from the console:
```
V/BranchSDK( 7616): onActivityPaused, activity = com.corylab.ahaspeak.MainActivity@99526f8
D/FlutterBranchSDK( 7616): triggered onActivityPaused: com.corylab.ahaspeak.MainActivity
V/BranchSDK( 7616): onActivityResumed, activity = com.corylab.ahaspeak.MainActivity@99526f8
V/BranchSDK( 7616): onIntentReady com.corylab.ahaspeak.MainActivity@99526f8 removing INTENT_PENDING_WAIT_LOCK
V/BranchSDK( 7616): Read params uri: null bypassCurrentActivityIntentState: false intent state: READY
V/BranchSDK( 7616): extractExternalUriAndIntentExtras null com.corylab.ahaspeak.MainActivity@99526f8
V/BranchSDK( 7616): isIntentParamsAlreadyConsumed false
D/BranchSDK( 7616): Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
V/BranchSDK( 7616): extractBranchLinkFromIntentExtra com.corylab.ahaspeak.MainActivity@99526f8
V/BranchSDK( 7616): isIntentParamsAlreadyConsumed false
V/BranchSDK( 7616): processNextQueueItem onIntentReady
V/BranchSDK( 7616): Queue is: 
D/FlutterBranchSDK( 7616): triggered onActivityResumed: com.corylab.ahaspeak.MainActivity
```
Could you please confirm:
1. Is it possible to generate short links in offline mode?
2. If yes, what additional configuration might be needed?
3. If no, is this a limitation of the Branch.io SDK?
Thank you for your help!

**Comment by RodrigoSMarques** [comment]
> Thank you for your response. However, I need to clarify my issue: The problem is specifically about generating a short link, not a long link. While the SDK does generate a long link in offline mode as you demonstrated, my requirement is to get a short link using `getShortUrl()`.
> 
> **To be more specific:**
> 
> 1. When online, `getShortUrl(`) correctly returns a short link (like https://xxxx.app.link/abcd123)
> 2. When offline, instead of getting a short link, it returns a long URL with parameters
>    According to issue [Pass long URL when try creating Short URL in Offline #237](https://github.com/RodrigoSMarques/flutter_branch_sdk/issues/237), there was a fix for offline short link generation. However, in my testing with version 8.0.2, I'm still unable to get short links when offline.
> 
> As requested, here are the logs from the console:
> 
> ```
> V/BranchSDK( 7616): onActivityPaused, activity = com.corylab.ahaspeak.MainActivity@99526f8
> D/FlutterBranchSDK( 7616): triggered onActivityPaused: com.corylab.ahaspeak.MainActivity
> V/BranchSDK( 7616): onActivityResumed, activity = com.corylab.ahaspeak.MainActivity@99526f8
> V/BranchSDK( 7616): onIntentReady com.corylab.ahaspeak.MainActivity@99526f8 removing INTENT_PENDING_WAIT_LOCK
> V/BranchSDK( 7616): Read params uri: null bypassCurrentActivityIntentState: false intent state: READY
> V/BranchSDK( 7616): extractExternalUriAndIntentExtras null com.corylab.ahaspeak.MainActivity@99526f8
> V/BranchSDK( 7616): isIntentParamsAlreadyConsumed false
> D/BranchSDK( 7616): Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
> V/BranchSDK( 7616): extractBranchLinkFromIntentExtra com.corylab.ahaspeak.MainActivity@99526f8
> V/BranchSDK( 7616): isIntentParamsAlreadyConsumed false
> V/BranchSDK( 7616): processNextQueueItem onIntentReady
> V/BranchSDK( 7616): Queue is: 
> D/FlutterBranchSDK( 7616): triggered onActivityResumed: com.corylab.ahaspeak.MainActivity
> ```
> 
> Could you please confirm:
> 
> 1. Is it possible to generate short links in offline mode?
> 2. If yes, what additional configuration might be needed?
> 3. If no, is this a limitation of the Branch.io SDK?
> 
> Thank you for your help!

The Branch SDK is responsible for generating the URL, not the plugin.

In offline mode, long links are generated because the URL needs to contain the link data, since the data was not sent to the API.

The scenario reported in the issue is different. When the link was generated in offline mode, the plugin did not return because an error was generated when sending it to the API. 

The fix was made, so that in case of an error, the generated URL is returned.

**Comment by RodrigoSMarques** [comment]
About [long links](https://help.branch.io/using-branch/docs/creating-a-deep-link#long-links)

**Comment by PhuCG** [comment]
Thank you @RodrigoSMarques for explaining the offline behavior of Branch SDK and clarifying that long URLs are expected when offline. Your guidance has been very helpful.
