### ISSUE TITLE
flutter_deeplinking_enable default value changed

### ISSUE THREAD

**Issue by renzullomichele** [RodrigoSMarques/flutter_branch_sdk#397]
As described [here](https://docs.google.com/document/d/1TUhaEhNdi2BUgKWQFEbOzJgmUAlLJwIAhnFfZraKgQs/edit?tab=t.0), looks like in flutter 3.27, by default, flutter_deeplinking is opted-in (true)

```MD
Set deep linking flag to true by default by @hannah-hyj in [52350](https://github.com/flutter/engine/pull/52350)
```
so flutter is "favored" over third-party plugins that intercepts like flutter_branch_sdk (or uni_links...).  
I haven't tested yet flutter 3.27, but if is true, as mentioned in the migration documentation, it should be set to false in the AndroidManifest or Plist for iOS, so that flutter interception is not used, and Branch one is the preference.

**Comment by RodrigoSMarques** [comment]
When opening an issue, fill in all the requested information.

Do not delete any sessions. 

Without this information, it is not possible to analyze the problem in detail and reproduce it.

If the requested information is not provided, the issue will be closed.

**Comment by RodrigoSMarques** [comment]
Is this issue a statement or a question?

**Comment by renzullomichele** [comment]
It is a question, I haven't had the chance to test it personally yet, since it was released yesterday and from just reading the changelog I spotted this. The migration mentioned that many third party plugins might be affected

**Comment by hnvn** [comment]
I've experienced the issue that deeplink doesn't work after upgrading to flutter 3.27, I wonder that this change is effected to flutter_branch_sdk plugin because everything is ok if I downgrade to flutter 3.24

**Comment by hnvn** [comment]
I can confirm that after add `<meta-data android:name="flutter_deeplinking_enabled" android:value="false" />` to `AndroidManifest` the issue is gone

**Comment by RodrigoSMarques** [comment]
I will update the plugin documentation to include this note.

Thanks

**Comment by RodrigoSMarques** [comment]
Updated documentation

**Comment by TuanDM21** [comment]
Hi @RodrigoSMarques!
Could you please clarify deeplinking, Branch.io, and the associated SDK? I have reviewed the documentation, but I would like to know if I still need to install the SDK if my deeplink is only intended to trigger emails in the registration flow. 
I'm having a problem where the deeplink doesn't navigate to the correct screen on Android, but it works fine on iOS
