### ISSUE TITLE
How to customize Branch.io link preview with small icon/fee display?

### ISSUE THREAD

**Issue by PhuCG** [RodrigoSMarques/flutter_branch_sdk#398]
Hi Branch.io team,

I'm implementing Branch.io deep linking in my Flutter application and I'd like to customize the link preview to display a small icon/fee on the left side similar to LetMeSpeak app's implementation.

Current implementation:
I'm using Flutter Branch SDK with the following configuration:
```
    return BranchUniversalObject(
      canonicalIdentifier: 'flutter/branch',
      title: 'AhaSpeak - Language Learning',
      imageUrl:
          'https://www.garethjmsaunders.co.uk/wp-content/uploads/2017/10/share-logo.jpg',
      contentDescription:
          'Learn English speaking through real-life scenarios with smart AI conversations.',
      contentMetadata: BranchContentMetaData()
        ..addCustomMetadata('custom_date_created', dateString),
      expirationDateInMilliSec: expiredDate.millisecondsSinceEpoch,
    );
```
Get short url
```
    final response = await FlutterBranchSdk.getShortUrl(
      buo: buo,
      linkProperties: lp,
    );
```

What I've tried:
- Added og_image_url with 48x48px app icon (https://storage.ahaspeak.app/aha_speak_app_icon.png)
- But the small icon still doesn't appear in the preview

Environment details:
- Flutter version: 3.24.5 (stable)
- Dart version: 3.5.4
- flutter_branch_sdk: [version của bạn]

Expected result:
I want to achieve a link preview similar to LetMeSpeak app where there's a small icon/fee display on the left side of the preview card.

Questions:
1. Is it possible to customize the link preview to add such elements?
2. What parameters or configurations should I use to achieve this?
3. Are there any specific requirements or limitations for this kind of customization?

I've attached a screenshot of LetMeSpeak's implementation for reference.

Letmespeak
![Screenshot 2024-12-14 at 11 17 48](https://github.com/user-attachments/assets/6cee37c1-9436-4d8d-87af-4c4b82a06027)
My app
![Screenshot 2024-12-14 at 11 17 42](https://github.com/user-attachments/assets/103d2542-fc9e-4e54-99ab-5cb3054c1797)

Thank you for your help!

**Comment by RodrigoSMarques** [comment]
URL Preview is a paid feature of Branch:

More information here:

[How long does it take for new images to appear on social media preview once updated?](https://help.branch.io/faq/docs/how-long-does-it-take-for-new-images-to-appear-on-social-media-preview-once-updated)

**Comment by RodrigoSMarques** [comment]
<img width="998" alt="image" src="https://github.com/user-attachments/assets/cd73294b-fb9b-4abc-81e2-6a351a0c4011" />
