### ISSUE TITLE
Sdk not working with latest version

### ISSUE THREAD

**Issue by martinpelli** [RodrigoSMarques/flutter_branch_sdk#405]
Keep the template and provide all requested information:

**Describe the bug**
When trying to compile the app with flutter 3.27.1 and flutter_branch_sdk 8.3.1 there are some Swift errors

```
Error (Xcode): 'FlutterBranchSdkPlugin' has different definitions in different modules; first difference is definition in module 'flutter_branch_sdk.Swift' found 2 referenced protocols
/build/ios/Debug-development-iphonesimulator/flutter_branch_sdk/flutter_branch_sdk.framework/Headers/flutter_branch_sdk-Swift.h:317:11

Modules Issue (Xcode): Definition of 'FlutterBranchSdkPlugin' must be imported from module 'flutter_branch_sdk.Swift' before it is required
/ios/Runner/GeneratedPluginRegistrant.m:161:3
```
**To Reproduce**
1. Upgrade to latest  Flutter version
2. Install flutter_branch_sdk as dependency in pubspec.yaml
3. Try to compile to iOS

**Expected behavior**
It should compile

**Mobile (Please complete the following information. remove session if not Mobile):**
 - Flutter: version: 3.27.1
 - flutter_branch_sdk version: 8.3.1
 - OS: MacOS Sequoia 15.1.1
 - Device: iPhone 15 pro simulator

**Comment by RodrigoSMarques** [comment]
Did you run a flutter clean on your project before building?

**Comment by martinpelli** [comment]
yes but after you mention, I also did a `pod deintegrate` and with this one worked.
