### ISSUE TITLE
Using FlutterFragmentActivity instead of FlutterActivity

### ISSUE THREAD

**Issue by ganeshrvel** [RodrigoSMarques/flutter_branch_sdk#59]
One of the other package integration is messing up with the Branch SDK integration in our app.

The other plugin requires the `MainActivity` to extend the `FlutterFragmentActivity`, doing which Branch SDK breaks. 
Is there any workaround to use the Branch SDK with `MainActivity` extending the `FlutterFragmentActivity`?

Cheers!

**Comment by RodrigoSMarques** [comment]
HI @ganeshrvel .
Can you give more details about the problem?
I know that some plugins need FlutterFragmentActivity, but I didn't have to change any projects that already contain the Branch SDK

**Comment by ganeshrvel** [comment]
Truecaller SDK requires FlutterFragmentActivity 

https://github.com/truecaller/flutter-sdk

**Comment by RodrigoSMarques** [comment]
OK.  But what is the problem?  display any error messages?  any action not taken?  please provide more details for analysis.

**Comment by ganeshrvel** [comment]
If I use FlutterFragmentActivity then branch sdk doesn't recieve data when the app is on terminated state (when exited from the app). But truecaller SDK works, no error whatsover.


If I use FlutterActivity truecaller SDK doesn't work but branch works just fine. It recieves data even when it's terminated.

**Comment by ryder247** [comment]
Thanks @RodrigoSMarques for this awesome package, I also have the same same problem where the [local_auth](https://pub.dev/packages/local_auth#android-integration) package  plugin requires the use of a FlutterFragmentActivity as opposed to FlutterActivity. As of now this plugin does not return any data for me because i also need the local_auth  to work.
if its possible to implent FlutterFragmentActivity in MainActivity.kt. That will be helpful.

**Comment by RodrigoSMarques** [comment]
Hello guys.
I will have to investigate. I didn't know about this problem.
I have to include local_auth in a project that has this package, but I haven't done it yet.

I believe that nothing is needed in the package, perhaps some FlutterFragmentActivity method that should be overridden.

I will have to investigate.

**Comment by RodrigoSMarques** [comment]
Hello guys.
I opened the flutter_branch_sdk sample project, changed it to use FlutterFragmentActivity.

I put the project to work and it continues to function normally.

Below print the changed code and the execution log after clicking the link.

![Captura de Tela 2020-10-13 às 22 33 12](https://user-images.githubusercontent.com/17687286/95933203-5eba5700-0da4-11eb-8064-cf12544a4f22.png)

![Captura de Tela 2020-10-13 às 22 43 31](https://user-images.githubusercontent.com/17687286/95933794-c7560380-0da5-11eb-93f2-b3396cd18a87.png)

![Captura de Tela 2020-10-13 às 22 32 27](https://user-images.githubusercontent.com/17687286/95933200-5c57fd00-0da4-11eb-9d83-52badce870db.png)

I also added local_auth to the project

**Comment by ryder247** [comment]
Can you please try it release mode too?

**Comment by ayush221b** [comment]
@RodrigoSMarques Have you tried clicking on the deeplink when the app is terminated? After changing to FlutterFragmentActivity we got the deeplinks to work when the app was already open but it doesn't work when the app is terminated.

**Comment by RodrigoSMarques** [comment]
I did not generate in release mode, but it really is not working when opening the app.
Works only with the open app.

I believe that it is necessary to override some method of FragmentActiviy, but I have to investigate.

**Comment by RodrigoSMarques** [comment]
Hello guys.
I did some tests.
BranchSDK must be initialized in the Activity's onStart event, as per Branch's documentation.
In Flutter this event is the onActivityStarted of ActivityLifecycleCallbacks in FlutterActivity.

When FlutterFragmentActivity is used, this event is not called in the Activity and therefore the Branch Listen does not work.

If the application is open, clicking the onActivityStarted link is triggered.
But if the application is opened by deeplink, it is not triggered.

I don't know how this can be handled.

**Comment by ganeshrvel** [comment]
raised a PR for this issue: https://github.com/RodrigoSMarques/flutter_branch_sdk/pull/61

**Comment by RodrigoSMarques** [comment]
The PR #61 was not accepted.
If changes are applied, projects that use FlutterActivity will stop working. The change cannot be used in both cases.
I did tests and realized that sometimes FlutterFragmentActivity may not work, because BranchSDK also needs the Activity Lifecycle (onActivityStarted) and it is not called.

**Comment by RodrigoSMarques** [comment]
Released version 3.3.0 with support for FlutterFragmentActivity
