### ISSUE TITLE
[Crash] MainThread Issue.

### ISSUE THREAD

**Issue by wooxist** [RodrigoSMarques/flutter_branch_sdk#69]
1.3.0 has crash on android

Please refer below log.

io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread (FlutterJNI.java:36)
io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage (FlutterJNI.java)
io.flutter.embedding.engine.dart.DartMessenger.send (DartMessenger.java:60)
io.flutter.embedding.engine.dart.DartExecutor$DefaultBinaryMessenger.send (DartExecutor.java:3)
io.flutter.embedding.engine.dart.DartExecutor.send (DartExecutor.java:2)
io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler$EventSinkImplementation.error (EventChannel.java:49)
br.com.rsmarques.flutter_branch_sdk.FlutterBranchSdkPlugin$1.onInitFinished (FlutterBranchSdkPlugin.java:147)
io.branch.referral.ServerRequestRegisterOpen.handleFailure (ServerRequestRegisterOpen.java:55)
io.branch.referral.Branch$1.run (Branch.java:50)

**Comment by RodrigoSMarques** [comment]
Insufficient information for analysis:
At what time does the error occur? When opening the app, when opening a link?
Any version of the flutter?
Which Android version of the device?
A project created in recent versions of Flutter or is it an old project?

**Comment by wooxist** [comment]
I think it's occured share generated links or initSession().
And it's not 100% issue but there are many crashes (4%~5% of users)
flutter version is latest stable version(1.22.5).

**Comment by SpencerLindemuth** [comment]
I'm facing the same issue as well. Lots of crashes, but also unsure about reproduction. My user breadcrumbs point to it happening as soon as the app launches and enters foreground, right on initialization.

**Comment by RodrigoSMarques** [comment]
Hi @SpencerLindemuth  and @wooxist 

I was unable to reproduce the error and I have no problems with my project.

I identified this issue here:
https://github.com/flutter/flutter/issues/34993

Solution: "Handle event channel in main thread"

I will upload the change to the bugfix branch. Do you qualify to test?

**Comment by SpencerLindemuth** [comment]
Yes, I was finally able to reproduce I believe. I have to run in release mode so my logging is limited, but when opening the app, then leaving and clicking a branch link, when it resumes I receive 
`W/FlutterJNI(17970): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: af-events. Response ID: 0`
In the terminal, which I assume is probably the same error.

**Comment by RodrigoSMarques** [comment]
Hi @SpencerLindemuth and @wooxist 
Can you do tests on the new version, before the release?

In **pubspec.yaml**

```xml
  #flutter_branch_sdk: ^1.3.0
  flutter_branch_sdk:
    git:
      url: https://github.com/RodrigoSMarques/flutter_branch_sdk.git
      ref: bugfix
```
Thanks.

**Comment by wooxist** [comment]
We need time to collect crash report. please wait few days.

**Comment by SpencerLindemuth** [comment]
Successfully suppresses detached JNI message for me!

**Comment by RodrigoSMarques** [comment]
Hi @SpencerLindemuth 
Thanks for you Feedback.

I will make the new release available on 01/04/2021

**Comment by wooxist** [comment]
I think it's fixed all.
We have no crash more.
Thanks.

**Comment by RodrigoSMarques** [comment]
Hi @wooxist 
Thanks for the feedback. I will provide the release version

**Comment by RodrigoSMarques** [comment]
New release 1.3.1
https://pub.dev/packages/flutter_branch_sdk/versions/1.3.1
