### ISSUE TITLE
[Android] - app crashed when click on back button

### ISSUE THREAD

**Issue by uyit14** [RodrigoSMarques/flutter_branch_sdk#83]
When i open another app from my app and then click default back button to go back my app -> crash
D/AndroidRuntime(26074): Shutting down VM
E/AndroidRuntime(26074): FATAL EXCEPTION: main
E/AndroidRuntime(26074): Process: com.cosmosum.nonprod.staging, PID: 26074
E/AndroidRuntime(26074): java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.EventChannel$EventSink.success(java.lang.Object)' on a null object reference
E/AndroidRuntime(26074): 	at br.com.rsmarques.flutter_branch_sdk.FlutterBranchSdkPlugin$MainThreadEventSink$1.run(FlutterBranchSdkPlugin.java:691)
E/AndroidRuntime(26074): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(26074): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(26074): 	at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime(26074): 	at android.app.ActivityThread.main(ActivityThread.java:8129)
E/AndroidRuntime(26074): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(26074): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
E/AndroidRuntime(26074): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
I/System.out(26074): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(26074): (HTTPLog)-Static: isSBSettingEnabled false

**Comment by RodrigoSMarques** [comment]
I didn't understand: "When I open another app from my app and then click default back button to go back my app".

Can you give me an example of an application being opened so I can try to reproduce the error?

**Comment by uyit14** [comment]
This is flow:
1. At "My App" click on a phone_number  to open Phone app (the code is: launch('tel:${"84357xxxxxx"}');) -> Phone app opened
2. Click OS back button -> app crash with below information.

**Comment by uyit14** [comment]
I added below code to FlutterBranchSdkPlugin.java and crash is not happen now.
`        public void success(final Object o) {
            handler.post(new Runnable() {
                @Override
                public void run() {
                    if (eventSink != null) {
                        eventSink.success(o);
                    }
                }
            });
        }`

**Comment by RodrigoSMarques** [comment]
Hi @uyit14 

A new release was planned tomorrow because of the new version of the SDK for iOS, I will include this fix in this release.

Thanks.

**Comment by uyit14** [comment]
@RodrigoSMarques Thanks alot.
