### ISSUE TITLE
Question about minimal example for app install attribution

### ISSUE THREAD

**Issue by arjunbansal** [RodrigoSMarques/flutter_branch_sdk#85]
I have implemented `flutter_branch_sdk` in my app and `FlutterBranchSdk.validateSDKIntegration();` is passing on both iOS and Android. 

As a first example, I would like to just have app install attribution (i.e., I don't need Deeplink into content into the app). What's the minimal initialization of `flutter_branch_sdk` needed in the Dart code to be able to have this information routed back to Branch?

Do I need a `FlutterBranchSdk.initSession()` in `main.dart`, or something else? Thanks!

**Comment by RodrigoSMarques** [comment]
If you don't use deeplink, FlutterBranchSdk.initSession () is not necessary.

I don't know if Branch creates automatic events using only the SDK in the app. I never looked at how attribution works.
Tests are required.

I would record an app opening event, for example, to say that the app was opened.

```dart
BranchEvent eventCustom = BranchEvent.customEvent('open_app');
FlutterBranchSdk.trackContentWithoutBuo(branchEvent: eventCustom);
```

**Comment by arjunbansal** [comment]
Thanks, I was able to get this to work with adding the following line:
```dart
var params = await FlutterBranchSdk.getFirstReferringParams();
```

Not sure if it was strictly needed though.
