### ISSUE TITLE
Conflicting documentation

### ISSUE THREAD

**Issue by pfiaux** [RodrigoSMarques/flutter_branch_sdk#88]
In the README.md the description for `getFirstReferringParams` and `getLatestReferringParams` seems to be inverted (headers look correct).

For `getFirstReferringParams`:

https://github.com/RodrigoSMarques/flutter_branch_sdk#retrieve-install-install-only-parameters

> These session parameters will be available at any point later on with this command. If no parameters are available then Branch will return an empty dictionary. This refreshes with every new session (app installs AND app opens).

https://help.branch.io/developers-hub/docs/ios-full-reference#retrieve-install-install-only-parameters

> If you ever want to access the original session params (the parameters passed in for the first install event only)

**Comment by RodrigoSMarques** [comment]
Hi @pfiaux 
You are correct the description is reversed.
I will adjust in the next release.
Thank you for identifying this.

**Comment by RodrigoSMarques** [comment]
Fix in pr #89
