### ISSUE TITLE
Question about Facebook app install ads on Android

### ISSUE THREAD

**Issue by arjunbansal** [RodrigoSMarques/flutter_branch_sdk#90]
We have app install attribution working for organic links on both iOS and Android.

However, for Facebook app install ads, the paid attribution is only working for iOS and not for Android (we see the install events, but they don't get attributed as paid within Branch, and don't show up as installs on the FB side either). We followed the steps [here](https://help.branch.io/using-branch/docs/facebook-app-install-ads) 

Wondering if anyone here has run into the same issue and has pointers?

**Comment by RodrigoSMarques** [comment]
Did you open a ticket for Branch support?
Reported that it is configured and not working?

**Comment by arjunbansal** [comment]
Yes, I have a parallel thread there also, but so far they've only pointed me to [this suggestion](https://help.branch.io/faq/docs/not-collecting-advertising-id) which didn't resolve the issue.

**Comment by shashwatadi** [comment]
Same for me. Any luck with this or alternate method that you are using @arjunbansal ?

**Comment by arjunbansal** [comment]
Feedback from Branch support was that the AAID doesn't seem to be getting populated. Does the flutter SDK populate that field and if so where in the code does that happen?

**Comment by RodrigoSMarques** [comment]
I don't know about any methods in the SDK. I believe that this is done automatically.

Check this link: [https://help.branch.io/developers-hub/docs/android-full-reference#proguard-settings-for-leveraging-branchs-pooled-matching](https://help.branch.io/developers-hub/docs/android-full-reference#proguard-settings-for-leveraging-branchs-pooled-matching)

**Comment by mayurdhurpate** [comment]
Facing issue with Facebook App Install Ads too.  Could this be the cause?

[Branch documentation](enableFacebookAppLinkCheck) recommends calling `Branch.getAutoInstance(this).enableFacebookAppLinkCheck()` for Java and `[[Branch getInstance] registerFacebookDeepLinkingClass:[FBSDKAppLinkUtility class]]` for iOS after integrating Facebook SDK for getting deferred deep link from Facebook SDK on the client side. 

I don't see these calls being made in the `flutter_branch_sdk` hence the deferred deep links are not captured.

**Comment by RodrigoSMarques** [comment]
The plugin does not have these methods.
They are not in the main documentation:
https://help.branch.io/developers-hub/docs/android-full-reference
https://help.branch.io/developers-hub/docs/ios-full-reference

I need to evaluate, as these methods must be called before initSession, which is a problem in the current package structure.

One solution is to edit the native code, import the Branch SDK and call the methods as stated in the documentation.

**Comment by mayurdhurpate** [comment]
Hi @RodrigoSMarques, could this be of any help, this is how RN package added the support: https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/pull/551

**Comment by RodrigoSMarques** [comment]
Hey guys.

In the next few days I will be implementing the Facebook Ads in the plugin.

I will need your help to perform the test.

**Comment by arjunbansal** [comment]
We found out that Flutter [automatically imports Proguard](https://github.com/flutter/flutter/pull/39986), so we were able to fix this issue by including the `--no-shrink` flag in the `flutter build` command.

I'll close this since the original issue is resolved. Thanks for your help.

**Comment by Umar1312** [comment]
@arjunbansal Hey, Can you please mention the steps taken to get attribution data on the Branch Dashboard. We have not been able to get it working even after doing the aforementioned steps.
