### ISSUE TITLE
Add INITIATE_STREAM and COMPLETE_STREAM as Standard events

### ISSUE THREAD

**Issue by mayurdhurpate** [RodrigoSMarques/flutter_branch_sdk#93]
These were added to Android SDK as standard events in v5.0.6.: 
https://github.com/BranchMetrics/android-branch-deep-linking-attribution/releases/tag/5.0.6

Calling these events as custom events results is 404, and weirdly goes to a infinite for loop freezing the whole app.

**Comment by RodrigoSMarques** [comment]
I will check. I need to check if they have been added to the iOS SDK.

**Comment by RodrigoSMarques** [comment]
@mayurdhurpate 

Branch iOS SDK does not contain these events.

[Android SDK](https://github.com/BranchMetrics/android-branch-deep-linking-attribution/blob/master/Branch-SDK/src/main/java/io/branch/referral/util/BRANCH_STANDARD_EVENT.java)

[iOS SDK](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/blob/master/Branch-SDK/BranchEvent.m)

We will have to wait.

**Comment by RodrigoSMarques** [comment]
I contacted Branch support and there is no provision for Branch to add these methods in the iOS SDK.
